// AUTO-GENERATED by AIVIC logic-scaffolder (3-stage per-function gen)
// slug: it-1-2
// 関数: approveInvoiceAndDistribute, validateAndDistributeInvoice, validateInvoiceFormat

export interface InvoiceApprovalRequest {
    invoiceId: string;
    accountId: string;
    approverUserId: string;
    invoiceData: {
        invoiceId: string;
        customerId: string;
        customerName: string;
        customerEmail: string;
        invoiceAmount: number;
        invoiceDueDate: string;
        invoiceDetails: Array<{
            lineItemId: string;
            description: string;
            quantity: number;
            unitPrice: number;
            lineTotal: number;
        }>;
        dealStatus: string;
        invoiceIssueDate: string;
        accountId: string;
        status: string;
        createdAt: string;
    };
}
export interface InvoiceApprovalResult {
    approvalStatus: string;
    invoiceId: string;
    approvedAt: string;
    distribution: {
        success: boolean;
        format: string;
        deliveryChannel: string;
        customerId: string;
        customerName: string;
        customerEmail: string;
        distributedAt: string;
        downloadUrl: string;
        documentUrl: string;
        distributionId: string;
    };
    invoiceDetails: {
        amount: number;
        dueDate: string;
        issueDate: string;
        lineItems: Array<{
            description: string;
            quantity: number;
            unitPrice: number;
            lineTotal: number;
        }>;
    };
}
export interface InvoiceDistributionData {
    invoiceId: string;
    customerId: string;
    customerName: string;
    amount: number;
    invoiceDate: string;
    dueDate: string;
    portalEmail: string;
    items: Array<{
        itemId: string;
        description: string;
        quantity: number;
        unitPrice: number;
        amount: number;
    }>;
    status: string;
}
export interface InvoiceDistributionResult {
    success: boolean;
    invoiceId: string;
    distributedTo: string;
    distributedAt: string;
    status: string;
}
export interface InvoiceFormatValidationResult {
    isValid: boolean;
    errors: string[];
}


/* AIVIC_FUNCTION_BUNDLE_START owner=approveInvoiceAndDistribute exports=approveInvoiceAndDistribute */
const __aivicBundle_1_approveInvoiceAndDistribute = (() => {
  async function approveInvoiceAndDistribute(
    request: InvoiceApprovalRequest
  ): Promise<InvoiceApprovalResult> {
    const {
      invoiceId,
      accountId,
      approverUserId,
      invoiceData,
    } = request;
  
    const approvalTimestamp = new Date().toISOString();
  
    const approvalResponse = await fetch(
      `/api/invoices/${invoiceId}/approve`,
      {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          invoiceId,
          accountId,
          approverUserId,
          approvedAt: approvalTimestamp,
        }),
      }
    );
  
    if (!approvalResponse.ok) {
      throw new Error(`Invoice approval failed: ${approvalResponse.status}`);
    }
  
    const distributionTimestamp = new Date().toISOString();
  
    const distributionResponse = await fetch(
      `/api/distribution/${invoiceId}/dispatch`,
      {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          invoiceId,
          customerId: invoiceData.customerId,
          customerName: invoiceData.customerName,
          customerEmail: invoiceData.customerEmail,
          amount: invoiceData.invoiceAmount,
          invoiceDate: invoiceData.invoiceIssueDate,
          dueDate: invoiceData.invoiceDueDate,
          format: 'unified',
          deliveryChannel: 'customer_portal',
        }),
      }
    );
  
    if (!distributionResponse.ok) {
      throw new Error(`Invoice distribution failed: ${distributionResponse.status}`);
    }
  
    const distributionData = await distributionResponse.json();
  
    const result: InvoiceApprovalResult = {
      approvalStatus: '承認済み',
      invoiceId,
      approvedAt: approvalTimestamp,
      distribution: {
        success: true,
        format: 'unified',
        deliveryChannel: 'customer_portal',
        customerId: invoiceData.customerId,
        customerName: invoiceData.customerName,
        customerEmail: invoiceData.customerEmail,
        distributedAt: distributionData.distributedAt || distributionTimestamp,
        downloadUrl: distributionData.downloadUrl || `https://portal.example.com/invoices/${invoiceId}/download`,
        documentUrl: distributionData.documentUrl || `https://portal.example.com/invoices/${invoiceId}`,
        distributionId: distributionData.distributionId || `DIST-${Date.now()}`,
      },
      invoiceDetails: {
        amount: invoiceData.invoiceAmount,
        dueDate: invoiceData.invoiceDueDate,
        issueDate: invoiceData.invoiceIssueDate,
        lineItems: invoiceData.invoiceDetails.map((item) => ({
          description: item.description,
          quantity: item.quantity,
          unitPrice: item.unitPrice,
          lineTotal: item.lineTotal,
        })),
      },
    };
  
    return result;
  }
  return { approveInvoiceAndDistribute };
})();
export const approveInvoiceAndDistribute = __aivicBundle_1_approveInvoiceAndDistribute.approveInvoiceAndDistribute;
/* AIVIC_FUNCTION_BUNDLE_END owner=approveInvoiceAndDistribute */

/* AIVIC_FUNCTION_BUNDLE_START owner=validateAndDistributeInvoice exports=validateAndDistributeInvoice */
const __aivicBundle_2_validateAndDistributeInvoice = (() => {
  function validateAndDistributeInvoice(invoiceData: InvoiceDistributionData): InvoiceDistributionResult {
    if (invoiceData["customerId"] === undefined || invoiceData["customerId"] === null) { throw new Error("customerId is required"); }
    if (invoiceData["customerName"] === undefined || invoiceData["customerName"] === null) { throw new Error("customerName is required"); }
    if (invoiceData["amount"] === undefined || invoiceData["amount"] === null) { throw new Error("amount is required"); }
    if (invoiceData["invoiceDate"] === undefined || invoiceData["invoiceDate"] === null) { throw new Error("invoiceDate is required"); }
    if (invoiceData["dueDate"] === undefined || invoiceData["dueDate"] === null) { throw new Error("dueDate is required"); }
    if (invoiceData["items"] === undefined || invoiceData["items"] === null) { throw new Error("items is required"); }
    if (invoiceData["status"] === undefined || invoiceData["status"] === null) { throw new Error("status is required"); }
    if (!invoiceData.portalEmail || invoiceData.portalEmail === '') {
      throw new Error('メールアドレスが設定されていません');
    }
  
    const distributedAt = new Date().toISOString();
  
    return {
      success: true,
      invoiceId: invoiceData.invoiceId,
      distributedTo: invoiceData.portalEmail,
      distributedAt: distributedAt,
      status: 'distributed'
    };
  }
  return { validateAndDistributeInvoice };
})();
export const validateAndDistributeInvoice = __aivicBundle_2_validateAndDistributeInvoice.validateAndDistributeInvoice;
/* AIVIC_FUNCTION_BUNDLE_END owner=validateAndDistributeInvoice */

/* AIVIC_FUNCTION_BUNDLE_START owner=validateInvoiceFormat exports=validateInvoiceFormat */
const __aivicBundle_3_validateInvoiceFormat = (() => {
  function validateInvoiceFormat(invoiceTemplate: {
    invoiceNumber: string;
    customerId: string;
    customerName: string;
    issueDate: string;
    amount: number | string;
    taxAmount: number;
    totalAmount: number;
    dueDate: string;
    items: Array<{
      itemName: string;
      quantity: number;
      unitPrice: number;
      lineTotal: number;
    }>;
  }): void {
    // amountフィールドが数値でない場合はエラーをthrow
    if (typeof invoiceTemplate.amount !== "number") {
      throw new Error("金額フィールドが不正な形式です。金額は数値である必要があります。");
    }
  
    // 必須フィールドの存在確認
    if (!invoiceTemplate.invoiceNumber) {
      throw new Error("請求書番号は必須です。");
    }
  
    if (!invoiceTemplate.customerId) {
      throw new Error("顧客IDは必須です。");
    }
  
    if (!invoiceTemplate.customerName) {
      throw new Error("顧客名は必須です。");
    }
  
    if (!invoiceTemplate.issueDate) {
      throw new Error("発行日は必須です。");
    }
  
    if (invoiceTemplate.taxAmount === undefined || invoiceTemplate.taxAmount === null) {
      throw new Error("税金額は必須です。");
    }
  
    if (invoiceTemplate.totalAmount === undefined || invoiceTemplate.totalAmount === null) {
      throw new Error("合計金額は必須です。");
    }
  
    if (!invoiceTemplate.dueDate) {
      throw new Error("支払期限は必須です。");
    }
  
    if (!Array.isArray(invoiceTemplate.items)) {
      throw new Error("請求書明細は配列である必要があります。");
    }
  
    // 明細の検証
    for (const item of invoiceTemplate.items) {
      if (!item.itemName) {
        throw new Error("明細の商品名は必須です。");
      }
  
      if (typeof item.quantity !== "number" || item.quantity < 0) {
        throw new Error("明細の数量は0以上の数値である必要があります。");
      }
  
      if (typeof item.unitPrice !== "number" || item.unitPrice < 0) {
        throw new Error("明細の単価は0以上の数値である必要があります。");
      }
  
      if (typeof item.lineTotal !== "number" || item.lineTotal < 0) {
        throw new Error("明細の小計は0以上の数値である必要があります。");
      }
    }
  }
  return { validateInvoiceFormat };
})();
export const validateInvoiceFormat = __aivicBundle_3_validateInvoiceFormat.validateInvoiceFormat;
/* AIVIC_FUNCTION_BUNDLE_END owner=validateInvoiceFormat */
