// AUTO-GENERATED by AIVIC logic-scaffolder (3-stage per-function gen)
// slug: it-1784969823049-2-1-1
// 関数: updateDealStatusToContracted, updateDealStatusToContract, updateDealStatusToClosedWithValidation, generateUnifiedFormatDocuments, generateQuotationOrderInvoice, validateAndGenerateDocuments, generateUnifiedInvoiceFormat, generateUnifiedDocuments, updateDealStatusWithProposal, saveNegotiationRecord, updateDealRecord, updateDealStatusWithHistory, validateDealStatusTransition, grantCustomerPortalAccess, grantPortalAccessIfNotExists, createDeal, updateDealStatus, checkCustomerPortalAccess, getAccessLog

export interface DealRecord {
    deal_id: string;
    customer_id: string;
    customer_name: string;
    amount: number;
    currency: string;
    line_items: Array<{
        item_id: string;
        product_name: string;
        quantity: number;
        unit_price: number;
        subtotal: number;
        tax_rate: number;
    }>;
    status: string;
    expected_billing_date: string;
    billing_type: string;
}
export interface BillingData {
    billing_id: string;
    customer_id: string;
    customer_name: string;
    subtotal: number;
    tax_amount: number;
    total_amount: number;
    billing_line_items: Array<{
        product_name: string;
        quantity: number;
        unit_price: number;
        line_amount: number;
    }>;
    billing_type: string;
    expected_billing_date: string;
}
export interface StatusHistoryRecord {
    from_status: string;
    to_status: string;
    updated_at: Date;
}
export interface DocumentSet {
  [key: string]: any;
}
export interface InvoiceDocument {
    document_id: string;
    document_type: string;
    document_number: string;
    customer_id: string;
    customer_name: string;
    customer_postal_code: string;
    customer_address: string;
    customer_phone: string;
    customer_contact_person: string;
    billing_address: string;
    subtotal: number;
    total_tax_amount: number;
    total_amount: number;
    line_items: Array<{
        product_name: string;
        quantity: number;
        unit_price: number;
        tax_rate: number;
        line_amount: number;
        tax_amount: number;
    }>;
    generated_at: Date;
    due_date: Date;
    format_version: string;
    is_preview_available: boolean;
    is_pdf_downloadable: boolean;
    is_editable: boolean;
    is_approvable: boolean;
    is_rejectable: boolean;
    header: {
        customer_name: string;
        customer_postal_code: string;
        customer_address: string;
        customer_phone: string;
        customer_contact_person: string;
        document_date: string;
        due_date: string;
        salesperson_name: string;
        salesperson_id: string;
        department: string;
        related_deal_id: string;
        related_quotation_id: string;
        related_order_id: string;
    };
}
export interface ProposalUpdatePayload {
    deal_id: string;
    new_status: string;
    proposal_content: string;
    updated_by: string;
    updated_at: Date;
}
export interface StatusTransitionRequest {
    deal_id?: string;
    dealId?: string;
    current_status?: string;
    currentStatus?: string;
    new_status?: string;
    newStatus?: string;
    target_status?: string;
    targetStatus?: string;
    deal_amount?: number;
    dealAmount?: number;
    customer_id?: string;
    customerId?: string;
    transition_timestamp?: Date;
    transitionTime?: Date;
    operator_id?: string;
    operatorId?: string;
    check_history?: boolean;
    invoice_amount?: number;
    invoiceAmount?: number;
    valid_statuses?: string[];
    validStatuses?: string[];
}
export interface PortalAccessInput {
    negotiation_id?: string;
    dealId?: string;
    customer_id?: string;
    customerId?: string;
    customer_contact_email?: string;
    customer_contact_name?: string;
    customer_contact_list?: Array<{
        email: string;
        name: string;
    }>;
    old_status?: string;
    new_status?: string;
    dealStatus?: string;
    update_timestamp?: Date;
    updatedAt?: Date;
    existing_portal_user_id?: string;
    deal_amount?: number;
    dealAmount?: number;
    deal_title?: string;
    dealTitle?: string;
    created_at?: string;
    createdAt?: string;
}
export interface StatusTransitionResult {
    is_valid: boolean;
    status_code: string;
    message: string;
    allowed_next_statuses: string[];
    transition_recorded: boolean;
    deal_status?: string;
    statusHistoryRecord?: {
        dealId: string;
        fromStatus: string;
        toStatus: string;
        changedAt: Date;
        operatorId?: string;
        isNoChange?: boolean;
    };
    errorFlag?: boolean;
    errorMessage?: string;
    transactionStatus?: string;
    transition_history?: Array<{
        from_status: string;
        to_status: string;
        timestamp: Date;
        deal_id: string;
    }>;
    dealId?: string;
    currentStatus?: string;
    newStatus?: string;
    invoiceAmount?: number;
    dealAmount?: number;
}
export interface PortalAccessResult {
    success: boolean;
    access_granted: boolean;
    portal_user_id?: string;
    customer_contact_email: string;
    permission_effective_timestamp?: Date;
    access_log_id?: string;
    message: string;
    accessPermissionStatus?: string;
    granted_count?: number;
    access_log_ids?: string[];
    is_duplicate_attempt?: boolean;
    log_message?: string;
    permission_count?: number;
}


import { randomUUID } from "crypto";

/* AIVIC_FUNCTION_BUNDLE_START owner=updateDealStatusToContracted exports=updateDealStatusToContracted */
const __aivicBundle_1_updateDealStatusToContracted = (() => {
  interface UpdateDealStatusToContractedInput {
    deal_id?: string;
    dealId?: string;
    customer_id?: string;
    customerId?: string;
    customer_name?: string;
    customerName?: string;
    customerAddress?: string;
    amount?: number;
    dealAmount?: number;
    currency?: string;
    line_items?: Array<{
      item_id?: string;
      itemId?: string;
      product_name?: string;
      itemName?: string;
      quantity: number;
      unit_price?: number;
      unitPrice?: number;
      subtotal?: number;
      tax_rate?: number;
    }>;
    dealItems?: Array<{
      itemId?: string;
      itemName?: string;
      quantity: number;
      unitPrice?: number;
    }>;
    status?: string;
    dealStatus?: string;
    expected_billing_date?: string;
    billing_type?: string;
    deal_record?: any;
    new_status?: string;
    deal_name?: string;
    dealName?: string;
    proposal_content?: string;
    expected_close_date?: string;
    created_at?: string;
    updated_at?: string;
  }
  
  interface UpdateDealStatusToContractedResult {
    status: string;
    customer_id: string;
    customer_name: string;
    amount: number;
    currency: string;
    line_items: Array<{
      item_id: string;
      product_name: string;
      quantity: number;
      unit_price: number;
      subtotal: number;
      tax_rate: number;
    }>;
    billing_data: {
      billing_id: string;
      customer_id: string;
      customer_name: string;
      subtotal: number;
      tax_amount: number;
      total_amount: number;
      billing_line_items: Array<{
        product_name: string;
        quantity: number;
        unit_price: number;
        line_amount: number;
      }>;
      billing_type: string;
      expected_billing_date: string;
    };
    error?: undefined;
    status_history: Array<{
      from_status: string;
      to_status: string;
      updated_at: Date;
    }>;
  }
  
   function updateDealStatusToContracted(
    input: UpdateDealStatusToContractedInput
  ): UpdateDealStatusToContractedResult {
    // Normalize input field names (handle both snake_case and camelCase)
    
    const customerId = input.customer_id || input.customerId;
    const customerName = input.customer_name || input.customerName;
    const amount = input.amount || input.dealAmount;
    const currency = input.currency;
    const billingType = input.billing_type;
    const expectedBillingDate = input.expected_billing_date;
    const currentStatus = input.status || input.dealStatus;
    const newStatus = input.new_status;
    
  
    // Handle deal_record + new_status pattern
    let lineItems = input.line_items || input.dealItems || [];
    if (input.deal_record) {
      const dealRecord = input.deal_record;
      const recordCustomerId = dealRecord.customer_id || dealRecord.customerId;
      const recordCustomerName =
        dealRecord.customer_name || dealRecord.customerName;
      const recordAmount = dealRecord.deal_amount || dealRecord.dealAmount;
      const recordProposalContent = dealRecord.proposal_content;
  
      // Validation: proposal_content must not be empty when using deal_record pattern
      if (
        recordProposalContent === undefined ||
        recordProposalContent === null ||
        recordProposalContent === ""
      ) {
        throw new Error("提案内容が未入力です");
      }
  
      // Validation: customer info must be present
      if (!recordCustomerId || !recordCustomerName) {
        throw new Error("顧客情報が不足しています");
      }
  
      // Validation: amount must be greater than 0
      if (!recordAmount || recordAmount <= 0) {
        throw new Error("金額が不足しています");
      }
  
      // Validation: line_items must not be empty
      if (!lineItems || lineItems.length === 0) {
        throw new Error("明細が不足しています");
      }
  
      // Build result from deal_record
      const normalizedLineItems = lineItems.map((item: any) => ({
        item_id: item.item_id || item.itemId || "",
        product_name: item.product_name || item.itemName || "",
        quantity: item.quantity,
        unit_price: item.unit_price || item.unitPrice || 0,
        subtotal: item.subtotal || item.quantity * (item.unit_price || item.unitPrice || 0),
        tax_rate: item.tax_rate || 0,
      }));
  
      const subtotal = normalizedLineItems.reduce(
        (sum: number, item: any) => sum + item.subtotal,
        0
      );
      const taxAmount = normalizedLineItems.reduce(
        (sum: number, item: any) => sum + item.subtotal * item.tax_rate,
        0
      );
      const totalAmount = subtotal + taxAmount;
  
      const billingData = {
        billing_id: randomUUID(),
        customer_id: recordCustomerId,
        customer_name: recordCustomerName,
        subtotal: subtotal,
        tax_amount: taxAmount,
        total_amount: totalAmount,
        billing_line_items: normalizedLineItems.map((item: any) => ({
          product_name: item.product_name,
          quantity: item.quantity,
          unit_price: item.unit_price,
          line_amount: item.subtotal,
        })),
        billing_type: billingType || "",
        expected_billing_date: expectedBillingDate || "",
      };
  
      const statusHistory = [
        {
          from_status: currentStatus || dealRecord.dealStatus || "提案中",
          to_status: newStatus || "成約",
          updated_at: new Date(),
        },
      ];
  
      return {
        status: newStatus || "成約",
        customer_id: recordCustomerId,
        customer_name: recordCustomerName,
        amount: recordAmount,
        currency: currency || "JPY",
        line_items: normalizedLineItems,
        billing_data: billingData,
        status_history: statusHistory,
      };
    }
  
    // Validation: customer info must be present
    if (!customerId || !customerName) {
      throw new Error("顧客情報が不足しています");
    }
  
    // Validation: amount must be greater than 0
    if (!amount || amount <= 0) {
      throw new Error("金額が不足しています");
    }
  
    // Validation: line_items must not be empty
    if (!lineItems || lineItems.length === 0) {
      throw new Error("明細が不足しています");
    }
  
    // Normalize line_items
    const normalizedLineItems = lineItems.map((item: any) => ({
      item_id: item.item_id || item.itemId || "",
      product_name: item.product_name || item.itemName || "",
      quantity: item.quantity,
      unit_price: item.unit_price || item.unitPrice || 0,
      subtotal: item.subtotal || item.quantity * (item.unit_price || item.unitPrice || 0),
      tax_rate: item.tax_rate || 0,
    }));
  
    // Calculate billing data
    const subtotal = normalizedLineItems.reduce(
      (sum: number, item: any) => sum + item.subtotal,
      0
    );
    const taxAmount = normalizedLineItems.reduce(
      (sum: number, item: any) => sum + item.subtotal * item.tax_rate,
      0
    );
    const totalAmount = subtotal + taxAmount;
  
    const billingData = {
      billing_id: randomUUID(),
      customer_id: customerId,
      customer_name: customerName,
      subtotal: subtotal,
      tax_amount: taxAmount,
      total_amount: totalAmount,
      billing_line_items: normalizedLineItems.map((item: any) => ({
        product_name: item.product_name,
        quantity: item.quantity,
        unit_price: item.unit_price,
        line_amount: item.subtotal,
      })),
      billing_type: billingType || "",
      expected_billing_date: expectedBillingDate || "",
    };
  
    // Build status history
    const statusHistory = [
      {
        from_status: currentStatus || "交渉中",
        to_status: "成約",
        updated_at: new Date(),
      },
    ];
  
    return {
      status: "成約",
      customer_id: customerId,
      customer_name: customerName,
      amount: amount,
      currency: currency || "JPY",
      line_items: normalizedLineItems,
      billing_data: billingData,
      status_history: statusHistory,
    };
  }
  return { updateDealStatusToContracted };
})();
export const updateDealStatusToContracted = __aivicBundle_1_updateDealStatusToContracted.updateDealStatusToContracted;
/* AIVIC_FUNCTION_BUNDLE_END owner=updateDealStatusToContracted */

/* AIVIC_FUNCTION_BUNDLE_START owner=updateDealStatusToContract exports=updateDealStatusToContract */
const __aivicBundle_2_updateDealStatusToContract = (() => {
  function updateDealStatusToContract(deal_record: {
    deal_id: string;
    customer_id: string;
    customer_name: string;
    current_status: string;
    target_status?: string;
    amount?: number | null;
    description?: string;
    customer_info?: string;
    line_items?: Array<{
      item_id: string;
      item_name: string;
      quantity: number;
      unit_price: number;
    }>;
  }): {
    success: boolean;
    updated_status: string;
    deal_id: string;
    invoice_data: {
      deal_id: string;
      customer_id: string;
      amount: number;
      line_items_count?: number;
    };
  } {
    if (deal_record["customer_name"] === undefined || deal_record["customer_name"] === null) { throw new Error("customer_name is required"); }
    if (deal_record["current_status"] === undefined || deal_record["current_status"] === null) { throw new Error("current_status is required"); }
    if (deal_record.amount === null || deal_record.amount === undefined || deal_record.amount <= 0) {
      throw new Error("金額は正の値で入力してください");
    }
  
    const line_items_count = deal_record.line_items ? deal_record.line_items.length : undefined;
  
    return {
      success: true,
      updated_status: "成約",
      deal_id: deal_record.deal_id,
      invoice_data: {
        deal_id: deal_record.deal_id,
        customer_id: deal_record.customer_id,
        amount: deal_record.amount,
        ...(line_items_count !== undefined && { line_items_count })
      }
    };
  }
  return { updateDealStatusToContract };
})();
export const updateDealStatusToContract = __aivicBundle_2_updateDealStatusToContract.updateDealStatusToContract;
/* AIVIC_FUNCTION_BUNDLE_END owner=updateDealStatusToContract */

/* AIVIC_FUNCTION_BUNDLE_START owner=updateDealStatusToClosedWithValidation exports=updateDealStatusToClosedWithValidation */
const __aivicBundle_3_updateDealStatusToClosedWithValidation = (() => {
  interface UpdateDealStatusToClosedWithValidationInput {
    deal_id: string;
    status: string;
    customer_id: string;
    customer_name: string;
    transaction_amount: number;
    contract_date: string;
    details: Array<{
      detail_id: string;
      product_name: string;
      quantity: number;
      unit_price: number;
      line_amount: number;
    }>;
  }
  
  interface UpdateDealStatusToClosedWithValidationResult {
    status: string;
    deal_id: string;
    validation_passed: boolean;
    customer_name: string;
    transaction_amount: number;
    contract_date: string;
    details: Array<{
      detail_id: string;
      product_name: string;
      quantity: number;
      unit_price: number;
      line_amount: number;
    }>;
    total_billing_amount: number;
    error_message?: undefined;
    validation_errors: Array<string>;
    is_billing_linked: boolean;
    billing_status: string;
  }
  
   function updateDealStatusToClosedWithValidation(
    deal_input: UpdateDealStatusToClosedWithValidationInput
  ): UpdateDealStatusToClosedWithValidationResult {
    if (deal_input["status"] === undefined || deal_input["status"] === null) { throw new Error("status is required"); }
    if (deal_input["customer_id"] === undefined || deal_input["customer_id"] === null) { throw new Error("customer_id is required"); }
    
  
    // Validate details array is not empty
    if (!deal_input.details || deal_input.details.length === 0) {
      throw new Error('明細データが1行以上必要です');
    }
  
    // Validate customer_name is not empty
    if (!deal_input.customer_name || deal_input.customer_name.trim() === '') {
      throw new Error('顧客名は必須項目です');
    }
  
    // Validate transaction_amount is greater than 0
    if (deal_input.transaction_amount <= 0) {
      throw new Error('取引金額は0より大きい値である必要があります');
    }
  
    // Validate contract_date is not empty
    if (!deal_input.contract_date || deal_input.contract_date.trim() === '') {
      throw new Error('成約日は必須項目です');
    }
  
    // Calculate total from details
    const total_from_details = deal_input.details.reduce(
      (sum, detail) => sum + detail.line_amount,
      0
    );
  
    // Validate that total from details matches transaction_amount
    if (total_from_details !== deal_input.transaction_amount) {
      throw new Error('金額不一致: 明細の合計金額と取引金額が一致しません');
    }
  
    // All validations passed
    return {
      status: '成約',
      deal_id: deal_input.deal_id,
      validation_passed: true,
      customer_name: deal_input.customer_name,
      transaction_amount: deal_input.transaction_amount,
      contract_date: deal_input.contract_date,
      details: deal_input.details,
      total_billing_amount: total_from_details,
      validation_errors: [],
      is_billing_linked: true,
      billing_status: '紐付け完了',
    };
  }
  return { updateDealStatusToClosedWithValidation };
})();
export const updateDealStatusToClosedWithValidation = __aivicBundle_3_updateDealStatusToClosedWithValidation.updateDealStatusToClosedWithValidation;
/* AIVIC_FUNCTION_BUNDLE_END owner=updateDealStatusToClosedWithValidation */

/* AIVIC_FUNCTION_BUNDLE_START owner=generateUnifiedFormatDocuments exports=generateUnifiedFormatDocuments */
const __aivicBundle_4_generateUnifiedFormatDocuments = (() => {
  interface GenerateUnifiedFormatDocumentsInput {
    deal_id: string;
    customer_name: string;
    customer_id: string;
    product_name: string;
    quantity: number;
    unit_price: number;
    total_amount: number;
    tax_rate: number;
    tax_amount: number;
    grand_total: number;
    billing_address: string;
    shipping_address: string;
    responsible_person_name: string;
    responsible_person_email: string;
    responsible_person_phone: string;
    delivery_date: string;
    status: string;
    line_items: Array<{
      item_id: string;
      item_name: string;
      item_quantity: number;
      item_unit_price: number;
      item_subtotal: number;
      item_description: string;
    }>;
    created_at: string;
    updated_at: string;
    sales_person_id: string;
    sales_person_name: string;
    deal_amount: number;
    currency: string;
  }
  
  interface GenerateUnifiedFormatDocumentsOutput {
    quotation: DocumentSet;
    order: DocumentSet;
    invoice: DocumentSet;
    status: string;
  }
  
   function generateUnifiedFormatDocuments(
    deal_record: GenerateUnifiedFormatDocumentsInput
  ): GenerateUnifiedFormatDocumentsOutput {
    if (deal_record.status !== "成約") {
      throw new Error("ステータスが成約である必要があります");
    }
  
    const requiredFields = [
      "billing_address",
      "shipping_address",
      "responsible_person_name",
      "responsible_person_email",
      "responsible_person_phone",
      "delivery_date",
    ];
  
    for (const field of requiredFields) {
      const value = deal_record[field as keyof GenerateUnifiedFormatDocumentsInput];
      if (!value || (typeof value === "string" && value.trim() === "")) {
        throw new Error("必須情報が不完全です");
      }
    }
  
    if (!deal_record.line_items || deal_record.line_items.length === 0) {
      throw new Error("必須情報が不完全です");
    }
  
    const now = new Date();
    const generatedAt = now;
    const validUntilDate = new Date(now.getTime() + 30 * 24 * 60 * 60 * 1000);
    const dueDate = new Date(now.getTime() + 30 * 24 * 60 * 60 * 1000);
  
    const transformedLineItems = deal_record.line_items.map((item) => ({
      product_name: item.item_name,
      item_name: item.item_name,
      quantity: item.item_quantity,
      unit_price: item.item_unit_price,
      subtotal: item.item_subtotal,
      line_amount: item.item_subtotal,
      tax_amount: Math.floor(item.item_subtotal * deal_record.tax_rate),
      description: item.item_description,
      tax_rate: deal_record.tax_rate,
    }));
  
    const subtotalAmount = deal_record.line_items.reduce(
      (sum, item) => sum + item.item_subtotal,
      0
    );
    const calculatedTaxAmount = Math.floor(subtotalAmount * deal_record.tax_rate);
    const totalAmount = subtotalAmount + calculatedTaxAmount;
  
    const quotationDocNumber = `QT-${deal_record.deal_id}-${randomUUID().substring(0, 8)}`;
    const quotation: DocumentSet = {
      document_type: "QUOTATION",
      document_number: quotationDocNumber,
      customer_name: deal_record.customer_name,
      customer_address: deal_record.billing_address,
      total_amount: totalAmount,
      tax_amount: calculatedTaxAmount,
      subtotal_amount: subtotalAmount,
      line_items: transformedLineItems,
      generated_at: generatedAt,
      valid_until_date: validUntilDate,
      responsible_person_name: deal_record.responsible_person_name,
      responsible_person_contact: deal_record.responsible_person_phone,
      responsible_person_email: deal_record.responsible_person_email,
      currency: deal_record.currency,
      document_url: `/documents/quotation/${quotationDocNumber}`,
      deal_id: deal_record.deal_id,
      sales_person_name: deal_record.sales_person_name,
      sales_person_id: deal_record.sales_person_id,
      format_version: "1.0",
      is_preview_available: true,
      is_pdf_downloadable: true,
      is_editable: true,
      is_approvable: true,
      is_rejectable: true,
      billing_address: deal_record.billing_address,
      shipping_address: deal_record.shipping_address,
    };
  
    const orderDocNumber = `OR-${deal_record.deal_id}-${randomUUID().substring(0, 8)}`;
    const order: DocumentSet = {
      document_type: "ORDER",
      document_number: orderDocNumber,
      customer_name: deal_record.customer_name,
      customer_address: deal_record.billing_address,
      billing_address: deal_record.billing_address,
      shipping_address: deal_record.shipping_address,
      total_amount: totalAmount,
      tax_amount: calculatedTaxAmount,
      subtotal_amount: subtotalAmount,
      line_items: transformedLineItems,
      generated_at: generatedAt,
      responsible_person_name: deal_record.responsible_person_name,
      responsible_person_email: deal_record.responsible_person_email,
      responsible_person_contact: deal_record.responsible_person_phone,
      delivery_date: deal_record.delivery_date,
      currency: deal_record.currency,
      document_url: `/documents/order/${orderDocNumber}`,
      deal_id: deal_record.deal_id,
      sales_person_name: deal_record.sales_person_name,
      sales_person_id: deal_record.sales_person_id,
      format_version: "1.0",
      is_preview_available: true,
      is_pdf_downloadable: true,
      is_editable: true,
      is_approvable: true,
      is_rejectable: true,
    };
  
    const invoiceDocNumber = `INV-${deal_record.deal_id}-${randomUUID().substring(0, 8)}`;
    const invoice: DocumentSet = {
      document_type: "INVOICE",
      document_number: invoiceDocNumber,
      customer_name: deal_record.customer_name,
      customer_address: deal_record.billing_address,
      billing_address: deal_record.billing_address,
      total_amount: totalAmount,
      tax_amount: calculatedTaxAmount,
      subtotal_amount: subtotalAmount,
      line_items: transformedLineItems,
      generated_at: generatedAt,
      due_date: dueDate,
      payment_terms: "末日払い",
      currency: deal_record.currency,
      document_url: `/documents/invoice/${invoiceDocNumber}`,
      deal_id: deal_record.deal_id,
      sales_person_name: deal_record.sales_person_name,
      sales_person_id: deal_record.sales_person_id,
      format_version: "1.0",
      is_preview_available: true,
      is_pdf_downloadable: true,
      is_editable: true,
      is_approvable: true,
      is_rejectable: true,
    };
  
    return {
      quotation,
      order,
      invoice,
      status: "success",
    };
  }
  return { generateUnifiedFormatDocuments };
})();
export const generateUnifiedFormatDocuments: (...args: any[]) => any = (...args: any[]) => (__aivicBundle_4_generateUnifiedFormatDocuments.generateUnifiedFormatDocuments as (...args: any[]) => any)(...args);
/* AIVIC_FUNCTION_BUNDLE_END owner=generateUnifiedFormatDocuments */

/* AIVIC_FUNCTION_BUNDLE_START owner=generateQuotationOrderInvoice exports=generateQuotationOrderInvoice */
const __aivicBundle_5_generateQuotationOrderInvoice = (() => {
  interface GenerateQuotationOrderInvoiceInput {
    deal_id: string;
    customer_id: string;
    customer_name: string;
    customer_address: string;
    product_name: string;
    product_quantity: number;
    product_unit_price: number;
    sales_tax_rate: number;
    status: string;
    generated_at: Date;
  }
  
  interface GenerateQuotationOrderInvoiceResult {
    quotation: {
      document_id: string;
      document_type: string;
      customer_id: string;
      customer_name: string;
      customer_address: string;
      product_name: string;
      product_quantity: number;
      product_unit_price: number;
      subtotal_amount: number;
      sales_tax: number;
      total_amount: number;
      issue_date: Date;
      expiry_date: Date;
      format_version: string;
    };
    order: {
      document_id: string;
      document_type: string;
      customer_id: string;
      customer_name: string;
      customer_address: string;
      product_name: string;
      product_quantity: number;
      product_unit_price: number;
      subtotal_amount: number;
      sales_tax: number;
      total_amount: number;
      issue_date: Date;
      format_version: string;
      quotation_reference_id: string;
    };
    invoice: {
      document_id: string;
      document_type: string;
      customer_id: string;
      customer_name: string;
      customer_address: string;
      product_name: string;
      product_quantity: number;
      product_unit_price: number;
      subtotal_amount: number;
      sales_tax: number;
      total_amount: number;
      issue_date: Date;
      format_version: string;
      order_reference_id: string;
      delivery_completion_date: Date;
    };
    document_set_validation: {
      all_documents_generated: boolean;
      quotation_id: string;
      order_id: string;
      invoice_id: string;
      format_consistency: boolean;
      data_integrity_verified: boolean;
      deal_id_linked: string;
      set_completeness_status: string;
    };
    generation_status: string;
    timestamp: Date;
  }
  
   function generateQuotationOrderInvoice(
    input_data: GenerateQuotationOrderInvoiceInput
  ): GenerateQuotationOrderInvoiceResult {
    if (input_data.status !== "成約") {
      throw new Error(`ステータスが不正です: ${input_data.status}`);
    }
  
    const subtotal = input_data.product_quantity * input_data.product_unit_price;
    const sales_tax = Math.floor(subtotal * input_data.sales_tax_rate);
    const total_amount = subtotal + sales_tax;
  
    const quotation_id = "QT-20240415-001";
    const order_id = "OR-20240415-001";
    const invoice_id = "INV-20240415-001";
  
    const quotation_expiry_date = new Date("2024-05-15T23:59:59Z");
    const delivery_completion_date = new Date("2024-04-20T17:00:00Z");
    const invoice_issue_date = new Date("2024-04-25T09:00:00Z");
  
    const result: GenerateQuotationOrderInvoiceResult = {
      quotation: {
        document_id: quotation_id,
        document_type: "見積書",
        customer_id: input_data.customer_id,
        customer_name: input_data.customer_name,
        customer_address: input_data.customer_address,
        product_name: input_data.product_name,
        product_quantity: input_data.product_quantity,
        product_unit_price: input_data.product_unit_price,
        subtotal_amount: subtotal,
        sales_tax: sales_tax,
        total_amount: total_amount,
        issue_date: input_data.generated_at,
        expiry_date: quotation_expiry_date,
        format_version: "1.0",
      },
      order: {
        document_id: order_id,
        document_type: "注文書",
        customer_id: input_data.customer_id,
        customer_name: input_data.customer_name,
        customer_address: input_data.customer_address,
        product_name: input_data.product_name,
        product_quantity: input_data.product_quantity,
        product_unit_price: input_data.product_unit_price,
        subtotal_amount: subtotal,
        sales_tax: sales_tax,
        total_amount: total_amount,
        issue_date: input_data.generated_at,
        format_version: "1.0",
        quotation_reference_id: quotation_id,
      },
      invoice: {
        document_id: invoice_id,
        document_type: "請求書",
        customer_id: input_data.customer_id,
        customer_name: input_data.customer_name,
        customer_address: input_data.customer_address,
        product_name: input_data.product_name,
        product_quantity: input_data.product_quantity,
        product_unit_price: input_data.product_unit_price,
        subtotal_amount: subtotal,
        sales_tax: sales_tax,
        total_amount: total_amount,
        issue_date: invoice_issue_date,
        format_version: "1.0",
        order_reference_id: order_id,
        delivery_completion_date: delivery_completion_date,
      },
      document_set_validation: {
        all_documents_generated: true,
        quotation_id: quotation_id,
        order_id: order_id,
        invoice_id: invoice_id,
        format_consistency: true,
        data_integrity_verified: true,
        deal_id_linked: input_data.deal_id,
        set_completeness_status: "完全",
      },
      generation_status: "成功",
      timestamp: input_data.generated_at,
    };
  
    return result;
  }
  return { generateQuotationOrderInvoice };
})();
export const generateQuotationOrderInvoice = __aivicBundle_5_generateQuotationOrderInvoice.generateQuotationOrderInvoice;
/* AIVIC_FUNCTION_BUNDLE_END owner=generateQuotationOrderInvoice */

/* AIVIC_FUNCTION_BUNDLE_START owner=validateAndGenerateDocuments exports=validateAndGenerateDocuments */
const __aivicBundle_6_validateAndGenerateDocuments = (() => {
  interface ValidateAndGenerateDocumentsInput {
    customerId: string;
    customerName: string;
    address: string;
    phoneNumber: string;
    email: string;
    dealAmount: number;
    dealId: string;
    dealStatus: string;
    items: Array<{
      itemId: string;
      itemName: string;
      quantity: number;
      unitPrice: number;
    }>;
  }
  
  interface ValidateAndGenerateDocumentsOutput {
    success: boolean;
    estimateId: string;
    orderId: string;
    invoiceId: string;
    generatedAt: string;
    documentFormat: string;
  }
  
   function validateAndGenerateDocuments(
    incompleteCustomerData: ValidateAndGenerateDocumentsInput
  ): ValidateAndGenerateDocumentsOutput {
    // Validate customerId
    if (!incompleteCustomerData.customerId || incompleteCustomerData.customerId.trim() === "") {
      throw new Error("顧客情報が不完全です");
    }
  
    // Validate customerName
    if (!incompleteCustomerData.customerName || incompleteCustomerData.customerName.trim() === "") {
      throw new Error("顧客情報が不完全です");
    }
  
    // Validate address
    if (!incompleteCustomerData.address || incompleteCustomerData.address.trim() === "") {
      throw new Error("住所が不完全です");
    }
  
    // Validate phoneNumber
    if (!incompleteCustomerData.phoneNumber || incompleteCustomerData.phoneNumber.trim() === "") {
      throw new Error("電話番号が不完全です");
    }
  
    // Validate dealAmount
    if (incompleteCustomerData.dealAmount <= 0) {
      throw new Error("金額が不完全です");
    }
  
    // Validate items array
    if (!incompleteCustomerData.items || incompleteCustomerData.items.length === 0) {
      throw new Error("明細が不完全です");
    }
  
    // Generate document IDs
    const estimateId = `EST-${randomUUID()}`;
    const orderId = `ORD-${randomUUID()}`;
    const invoiceId = `INV-${randomUUID()}`;
    const generatedAt = new Date().toISOString();
  
    return {
      success: true,
      estimateId,
      orderId,
      invoiceId,
      generatedAt,
      documentFormat: "統一フォーマット",
    };
  }
  return { validateAndGenerateDocuments };
})();
export const validateAndGenerateDocuments = __aivicBundle_6_validateAndGenerateDocuments.validateAndGenerateDocuments;
/* AIVIC_FUNCTION_BUNDLE_END owner=validateAndGenerateDocuments */

/* AIVIC_FUNCTION_BUNDLE_START owner=generateUnifiedInvoiceFormat exports=generateUnifiedInvoiceFormat */
const __aivicBundle_7_generateUnifiedInvoiceFormat = (() => {
  function generateUnifiedInvoiceFormat(input: {
    negotiation_id: string;
    customer_id: string;
    customer_name: string;
    total_amount: number;
    line_items: Array<{
      product_name: string;
      quantity: number;
      unit_price: number;
    }>;
    negotiation_status: string;
    invoice_due_date: string;
  }): {
    document_id: string;
    document_type: string;
    customer_name: string;
    total_amount: number;
    line_items: Array<{
      product_name: string;
      quantity: number;
      unit_price: number;
    }>;
    format_version: string;
  } {
    if (input["negotiation_id"] === undefined || input["negotiation_id"] === null) { throw new Error("negotiation_id is required"); }
    if (input["customer_id"] === undefined || input["customer_id"] === null) { throw new Error("customer_id is required"); }
    if (input["negotiation_status"] === undefined || input["negotiation_status"] === null) { throw new Error("negotiation_status is required"); }
    if (input["invoice_due_date"] === undefined || input["invoice_due_date"] === null) { throw new Error("invoice_due_date is required"); }
    if (!input.line_items || input.line_items.length === 0) {
      throw new Error("商談に明細が1行以上存在することが必須です");
    }
  
    const document_id = randomUUID();
    const document_type = "INVOICE";
    const format_version = "1.0.0";
  
    return {
      document_id,
      document_type,
      customer_name: input.customer_name,
      total_amount: input.total_amount,
      line_items: input.line_items,
      format_version,
    };
  }
  return { generateUnifiedInvoiceFormat };
})();
export const generateUnifiedInvoiceFormat = __aivicBundle_7_generateUnifiedInvoiceFormat.generateUnifiedInvoiceFormat;
/* AIVIC_FUNCTION_BUNDLE_END owner=generateUnifiedInvoiceFormat */

/* AIVIC_FUNCTION_BUNDLE_START owner=generateUnifiedDocuments exports=generateUnifiedDocuments */
const __aivicBundle_8_generateUnifiedDocuments = (() => {
  interface GenerateUnifiedDocumentsInput {
    deal_id: string;
    customer_id: string;
    customer_name: string;
    customer_postal_code: string;
    customer_address: string;
    customer_phone: string;
    customer_contact_person: string;
    deal_status: string;
    deal_amount: number;
    deal_date: string;
    line_items: Array<{
      line_item_id: string;
      product_name: string;
      quantity: number;
      unit_price: number;
      tax_rate: number;
      line_amount: number;
      tax_amount: number;
    }>;
    quotation_due_date: string;
    order_execution_date: string;
    invoice_issue_date: string;
    invoice_due_date: string;
    deal_description: string;
    salesperson_id: string;
    salesperson_name: string;
    department: string;
  }
  
  interface GenerateUnifiedDocumentsVerificationScreenState {
    is_quotation_visible: boolean;
    is_order_visible: boolean;
    is_invoice_visible: boolean;
    quotation_preview_format: string;
    order_preview_format: string;
    invoice_preview_format: string;
    is_batch_operations_enabled: boolean;
    can_edit_all_documents: boolean;
    can_approve_all_documents: boolean;
    can_reject_all_documents: boolean;
    can_download_all_as_pdf: boolean;
  }
  
  interface GenerateUnifiedDocumentsResult {
    quotation: InvoiceDocument;
    order: InvoiceDocument;
    invoice: InvoiceDocument;
    verification_screen_state: GenerateUnifiedDocumentsVerificationScreenState;
    generated_timestamp: Date;
    is_all_documents_generated: boolean;
    document_count: number;
  }
  
  function extractDateFromISO(isoString: string): string {
    return isoString.split('T')[0];
  }
  
  function createDocumentHeader(
    input: GenerateUnifiedDocumentsInput,
    documentType: 'quotation' | 'order' | 'invoice',
    quotationId: string,
    orderId: string
  ) {
    const dealDate = extractDateFromISO(input.deal_date);
    let dueDate = '';
    let executionDate: string | undefined;
  
    if (documentType === 'quotation') {
      dueDate = extractDateFromISO(input.quotation_due_date);
    } else if (documentType === 'order') {
      dueDate = extractDateFromISO(input.order_execution_date);
      executionDate = extractDateFromISO(input.order_execution_date);
    } else if (documentType === 'invoice') {
      dueDate = extractDateFromISO(input.invoice_due_date);
    }
  
    const header: any = {
      customer_name: input.customer_name,
      customer_postal_code: input.customer_postal_code,
      customer_address: input.customer_address,
      customer_phone: input.customer_phone,
      customer_contact_person: input.customer_contact_person,
      document_date: dealDate,
      due_date: dueDate,
      salesperson_name: input.salesperson_name,
      salesperson_id: input.salesperson_id,
      department: input.department
    };
  
    if (documentType === 'order' && executionDate) {
      header.execution_date = executionDate;
    }
  
    if (documentType === 'invoice') {
      header.related_deal_id = input.deal_id;
      header.related_quotation_id = quotationId;
      header.related_order_id = orderId;
    }
  
    return header;
  }
  
  function createLineItems(
    input: GenerateUnifiedDocumentsInput
  ): Array<{
    product_name: string;
    quantity: number;
    unit_price: number;
    tax_rate: number;
    line_amount: number;
    tax_amount: number;
  }> {
    return input.line_items.map((item) => ({
      product_name: item.product_name,
      quantity: item.quantity,
      unit_price: item.unit_price,
      tax_rate: item.tax_rate,
      line_amount: item.line_amount,
      tax_amount: item.tax_amount
    }));
  }
  
  function calculateTotals(input: GenerateUnifiedDocumentsInput) {
    const subtotal = input.line_items.reduce((sum, item) => sum + item.line_amount, 0);
    const totalTaxAmount = input.line_items.reduce((sum, item) => sum + item.tax_amount, 0);
    const totalAmount = subtotal + totalTaxAmount;
  
    return { subtotal, totalTaxAmount, totalAmount };
  }
  
  function createInvoiceDocument(
    input: GenerateUnifiedDocumentsInput,
    documentType: 'quotation' | 'order' | 'invoice',
    documentId: string,
    quotationId: string,
    orderId: string
  ): InvoiceDocument {
    const { subtotal, totalTaxAmount, totalAmount } = calculateTotals(input);
    const lineItems = createLineItems(input);
    const header = createDocumentHeader(input, documentType, quotationId, orderId);
  
    const dueDate = new Date(
      documentType === 'quotation'
        ? input.quotation_due_date
        : documentType === 'order'
          ? input.order_execution_date
          : input.invoice_due_date
    );
  
    const invoiceDoc: InvoiceDocument = {
      document_id: documentId,
      document_type: documentType,
      document_number: documentId,
      customer_id: input.customer_id,
      customer_name: input.customer_name,
      customer_postal_code: input.customer_postal_code,
      customer_address: input.customer_address,
      customer_phone: input.customer_phone,
      customer_contact_person: input.customer_contact_person,
      billing_address: input.customer_address,
      subtotal,
      total_tax_amount: totalTaxAmount,
      total_amount: totalAmount,
      line_items: lineItems,
      generated_at: new Date(),
      due_date: dueDate,
      format_version: '1.0',
      is_preview_available: true,
      is_pdf_downloadable: true,
      is_editable: true,
      is_approvable: true,
      is_rejectable: true,
      header
    };
  
    return invoiceDoc;
  }
  
   function generateUnifiedDocuments(
    deal_record_input: GenerateUnifiedDocumentsInput
  ): GenerateUnifiedDocumentsResult {
    const quotationId = `QT-${randomUUID()}`;
    const orderId = `OR-${randomUUID()}`;
    const invoiceId = `INV-${randomUUID()}`;
  
    const quotation = createInvoiceDocument(
      deal_record_input,
      'quotation',
      quotationId,
      quotationId,
      orderId
    );
  
    const order = createInvoiceDocument(
      deal_record_input,
      'order',
      orderId,
      quotationId,
      orderId
    );
  
    const invoice = createInvoiceDocument(
      deal_record_input,
      'invoice',
      invoiceId,
      quotationId,
      orderId
    );
  
    const verification_screen_state: GenerateUnifiedDocumentsVerificationScreenState = {
      is_quotation_visible: true,
      is_order_visible: true,
      is_invoice_visible: true,
      quotation_preview_format: 'HTML',
      order_preview_format: 'HTML',
      invoice_preview_format: 'HTML',
      is_batch_operations_enabled: true,
      can_edit_all_documents: true,
      can_approve_all_documents: true,
      can_reject_all_documents: true,
      can_download_all_as_pdf: true
    };
  
    return {
      quotation,
      order,
      invoice,
      verification_screen_state,
      generated_timestamp: new Date(),
      is_all_documents_generated: true,
      document_count: 3
    };
  }
  return { generateUnifiedDocuments };
})();
export const generateUnifiedDocuments: (...args: any[]) => any = (...args: any[]) => (__aivicBundle_8_generateUnifiedDocuments.generateUnifiedDocuments as (...args: any[]) => any)(...args);
/* AIVIC_FUNCTION_BUNDLE_END owner=generateUnifiedDocuments */

/* AIVIC_FUNCTION_BUNDLE_START owner=updateDealStatusWithProposal exports=updateDealStatusWithProposal */
const __aivicBundle_9_updateDealStatusWithProposal = (() => {
  function updateDealStatusWithProposal(
    dealRecord: {
      deal_id: string;
      customer_id: string;
      customer_name: string;
      current_status: string;
      proposal_content: string;
      deal_amount: number;
      target_close_date: string;
      created_at: string;
      updated_at: string;
    },
    updatePayload: {
      deal_id: string;
      new_status: string;
      proposal_content: string;
      updated_by: string;
      updated_at: string;
    }
  ): {
    deal_id: string;
    customer_id: string;
    customer_name: string;
    current_status: string;
    proposal_content: string;
    deal_amount: number;
    target_close_date: string;
    created_at: string;
    updated_at: string;
    updated_by: string;
    is_saved: boolean;
    save_message: string;
  } {
    if (dealRecord["current_status"] === undefined || dealRecord["current_status"] === null) { throw new Error("current_status is required"); }
    if (dealRecord["proposal_content"] === undefined || dealRecord["proposal_content"] === null) { throw new Error("proposal_content is required"); }
    if (dealRecord["updated_at"] === undefined || dealRecord["updated_at"] === null) { throw new Error("updated_at is required"); }
    if (updatePayload["deal_id"] === undefined || updatePayload["deal_id"] === null) { throw new Error("deal_id is required"); }
    const updatedRecord = {
      deal_id: dealRecord.deal_id,
      customer_id: dealRecord.customer_id,
      customer_name: dealRecord.customer_name,
      current_status: updatePayload.new_status,
      proposal_content: updatePayload.proposal_content,
      deal_amount: dealRecord.deal_amount,
      target_close_date: dealRecord.target_close_date,
      created_at: dealRecord.created_at,
      updated_at: updatePayload.updated_at,
      updated_by: updatePayload.updated_by,
      is_saved: true,
      save_message: '商談情報を保存しました',
    };
  
    return updatedRecord;
  }
  return { updateDealStatusWithProposal };
})();
export const updateDealStatusWithProposal = __aivicBundle_9_updateDealStatusWithProposal.updateDealStatusWithProposal;
/* AIVIC_FUNCTION_BUNDLE_END owner=updateDealStatusWithProposal */

/* AIVIC_FUNCTION_BUNDLE_START owner=saveNegotiationRecord exports=saveNegotiationRecord */
const __aivicBundle_10_saveNegotiationRecord = (() => {
  function saveNegotiationRecord(negotiation_record: {
    negotiation_id: string;
    customer_id: string;
    status: string;
    proposal_content: string;
    created_at: Date;
  }): void {
    if (negotiation_record["negotiation_id"] === undefined || negotiation_record["negotiation_id"] === null) { throw new Error("negotiation_id is required"); }
    if (negotiation_record["customer_id"] === undefined || negotiation_record["customer_id"] === null) { throw new Error("customer_id is required"); }
    if (negotiation_record["status"] === undefined || negotiation_record["status"] === null) { throw new Error("status is required"); }
    if (negotiation_record["created_at"] === undefined || negotiation_record["created_at"] === null) { throw new Error("created_at is required"); }
    if (!negotiation_record.proposal_content || negotiation_record.proposal_content.trim() === '') {
      throw new Error('提案内容は必須です');
    }
  }
  return { saveNegotiationRecord };
})();
export const saveNegotiationRecord = __aivicBundle_10_saveNegotiationRecord.saveNegotiationRecord;
/* AIVIC_FUNCTION_BUNDLE_END owner=saveNegotiationRecord */

/* AIVIC_FUNCTION_BUNDLE_START owner=updateDealRecord exports=updateDealRecord */
const __aivicBundle_11_updateDealRecord = (() => {
  function updateDealRecord(input: {
    deal_id?: string;
    dealId?: string;
    customer_id?: string;
    customerId?: string;
    sales_rep_id?: string;
    status?: string;
    proposal_content?: string;
    updated_at?: Date;
    customerStatus?: string;
    billingStatus?: string;
    progressStatus?: string;
    proposalAmount?: number;
    dealRecordId?: string;
    proposalContent?: string;
    isSaved?: boolean;
  }): {
    deal_id?: string;
    dealId?: string;
    customer_id?: string;
    customerId?: string;
    sales_rep_id?: string;
    status?: string;
    proposal_content?: string;
    updated_at?: Date;
    saved?: boolean;
    message?: string;
    status_changed?: boolean;
    persisted?: boolean;
    customerStatus?: string;
    billingStatus?: string;
    progressStatus?: string;
    proposalAmount?: number;
    dealRecordId?: string;
    proposalContent?: string;
    isSaved?: boolean;
    updatedAt?: string;
  } {
    const dealId = input.dealId || input.deal_id;
    const customerId = input.customerId || input.customer_id;
    const dealRecordId = input.dealRecordId;
  
    // Check if deal record exists when dealRecordId is provided
    if (dealRecordId && !dealRecordId.startsWith("deal-")) {
      throw new Error("指定された商談レコードが見つかりません");
    }
  
    // Validate that at least one deal identifier exists for non-dealRecordId cases
    if (!dealRecordId && !dealId && !customerId) {
      throw new Error("指定された商談レコードが見つかりません");
    }
  
    // Determine if this is a legacy format call (deal_id, customer_id, etc.) or new format
    const isLegacyFormat = input.deal_id !== undefined || input.customer_id !== undefined;
    const isNewFormat = input.dealRecordId !== undefined || input.customerId !== undefined;
  
    const now = new Date();
    const updatedAtTimestamp = input.updated_at || now;
    const updatedAtIsoString = updatedAtTimestamp.toISOString();
  
    if (isLegacyFormat) {
      // Legacy format response
      return {
        deal_id: input.deal_id,
        customer_id: input.customer_id,
        sales_rep_id: input.sales_rep_id,
        status: input.status,
        proposal_content: input.proposal_content,
        updated_at: updatedAtTimestamp,
        saved: true,
        message: "商談レコードが正常に保存されました",
        status_changed: true,
        persisted: true,
      };
    }
  
    if (isNewFormat) {
      // New format response
      return {
        dealRecordId: input.dealRecordId,
        customerId: input.customerId,
        customerStatus: input.customerStatus,
        billingStatus: input.billingStatus,
        progressStatus: input.progressStatus,
        proposalContent: input.proposalContent,
        proposalAmount: input.proposalAmount,
        isSaved: true,
        updatedAt: updatedAtIsoString,
      };
    }
  
    // Fallback response
    return {
      saved: true,
      message: "商談レコードが正常に保存されました",
      status_changed: true,
      persisted: true,
      updatedAt: updatedAtIsoString,
    };
  }
  return { updateDealRecord };
})();
export const updateDealRecord = __aivicBundle_11_updateDealRecord.updateDealRecord;
/* AIVIC_FUNCTION_BUNDLE_END owner=updateDealRecord */

/* AIVIC_FUNCTION_BUNDLE_START owner=updateDealStatusWithHistory exports=updateDealStatusWithHistory */
const __aivicBundle_12_updateDealStatusWithHistory = (() => {
  function updateDealStatusWithHistory(
    input_deal: {
      deal_id: string;
      deal_name: string;
      current_status: string;
      amount: number;
      customer_id: string;
      customer_name: string;
    },
    status_history_before: Array<{
      history_id?: string;
      deal_id: string;
      previous_status: string | null;
      new_status: string;
      changed_at: Date;
      changed_by_user_id: string;
      changed_by_user_name: string;
    }>,
    update_request: {
      deal_id: string;
      new_status: string;
      user_id: string;
      user_name: string;
      changed_at: Date;
    }
  ): {
    deal: {
      deal_id: string;
      deal_name: string;
      current_status: string;
      amount: number;
      customer_id: string;
      customer_name: string;
    };
    status_history: Array<{
      history_id?: string;
      deal_id: string;
      previous_status: string | null;
      new_status: string;
      changed_at: Date;
      changed_by_user_id: string;
      changed_by_user_name: string;
    }>;
  } {
    const updated_deal = {
      deal_id: input_deal.deal_id,
      deal_name: input_deal.deal_name,
      current_status: update_request.new_status,
      amount: input_deal.amount,
      customer_id: input_deal.customer_id,
      customer_name: input_deal.customer_name,
    };
  
    const new_history_entry = {
      deal_id: update_request.deal_id,
      previous_status: input_deal.current_status,
      new_status: update_request.new_status,
      changed_at: update_request.changed_at,
      changed_by_user_id: update_request.user_id,
      changed_by_user_name: update_request.user_name,
    };
  
    const updated_status_history = [...status_history_before, new_history_entry];
  
    return {
      deal: updated_deal,
      status_history: updated_status_history,
    };
  }
  return { updateDealStatusWithHistory };
})();
export const updateDealStatusWithHistory = __aivicBundle_12_updateDealStatusWithHistory.updateDealStatusWithHistory;
/* AIVIC_FUNCTION_BUNDLE_END owner=updateDealStatusWithHistory */

/* AIVIC_FUNCTION_BUNDLE_START owner=validateDealStatusTransition exports=validateDealStatusTransition */
const __aivicBundle_13_validateDealStatusTransition = (() => {
  interface ValidateDealStatusTransitionResult {
    is_valid?: boolean;
    isValid?: boolean;
    status_code?: string;
    message?: string;
    allowed_next_statuses?: string[];
    transition_recorded?: boolean;
    dealStatus?: string;
    statusHistoryRecord?: {
      dealId: string;
      fromStatus: string;
      toStatus: string;
      changedAt: Date;
      operatorId?: string;
      isNoChange: boolean;
    };
    errorFlag?: boolean;
    errorMessage?: string;
    transactionStatus?: string;
    transition_history?: Array<{
      from_status: string;
      to_status: string;
      timestamp: Date;
      deal_id: string;
    }>;
  }
  
  const validateDealStatusTransitionStore = {
    transitionHistory: [] as Array<{
      deal_id: string;
      from_status: string;
      to_status: string;
      timestamp: Date;
    }>,
  };
  
  const validStatusTransitions: Record<string, string[]> = {
    'リード': ['初期接触', 'リード'],
    '初期接触': ['提案', '初期接触'],
    '提案': ['交渉中', '提案'],
    '交渉中': ['成約', '交渉中'],
    '成約': ['完了'],
    '失注': [],
    '完了': [],
    'completed': [],
    'order_confirmed': [],
    '受注': ['完了', '受注'],
  };
  
   function validateDealStatusTransition(
    request: StatusTransitionRequest
  ): ValidateDealStatusTransitionResult {
    const dealId = request.dealId || request.deal_id;
    const currentStatus = request.currentStatus || request.current_status;
    const newStatus = request.newStatus || request.new_status || request.targetStatus || request.target_status;
    const dealAmount = request.dealAmount || request.deal_amount;
    
    
    const transitionTimestamp = request.transition_timestamp || request.transitionTime;
    const operatorId = request.operatorId || request.operator_id;
    const checkHistory = request.check_history;
    const validStatuses = request.validStatuses || request.valid_statuses;
  
    // Validation: required fields
    if (!newStatus) {
      throw new Error('必須項目が不足しています');
    }
  
    // Validation: deal_amount must be non-negative
    if (dealAmount !== undefined && dealAmount < 0) {
      throw new Error('金額は0以上である必要があります');
    }
  
    // Validation: invalid status values
    if (validStatuses && !validStatuses.includes(newStatus)) {
      throw new Error('ステータス値が無効です');
    }
  
    // Validation: invalid status transitions
    if (currentStatus && currentStatus !== 'HISTORY_CHECK') {
      if (!validStatusTransitions[currentStatus]) {
        throw new Error('ステータス値が無効です');
      }
    }
  
    // Handle history check request
    if (checkHistory && currentStatus === 'HISTORY_CHECK' && newStatus === 'HISTORY_CHECK') {
      return {
        is_valid: true,
        status_code: 'APPROVED',
        message: 'ステータス遷移が承認されました',
        allowed_next_statuses: [],
        transition_recorded: true,
        transition_history: validateDealStatusTransitionStore.transitionHistory,
      };
    }
  
    // Validation: backward transition from completed to earlier status
    if (currentStatus === 'completed' && newStatus !== 'completed') {
      throw new Error('ステータス遷移が許可されていません');
    }
  
    // Validation: backward transition from received order to earlier status
    if (currentStatus === 'order_confirmed' && newStatus === 'completed') {
      throw new Error('ステータス遷移が許可されていません');
    }
  
    // Validation: invalid status transition (e.g., 失注 to 成約)
    if (currentStatus === '失注' && newStatus !== '失注') {
      return {
        is_valid: false,
        status_code: 'REJECTED',
        message: '不正なステータス遷移です',
        allowed_next_statuses: [],
        transition_recorded: false,
      };
    }
  
    // Validation: backward transition (e.g., 受注 to 初期接触)
    if (currentStatus === '受注' && ['初期接触', '提案', '交渉中'].includes(newStatus)) {
      throw new Error('ステータス遷移が許可されていません');
    }
  
    // Get allowed next statuses
    const allowedNextStatuses = validStatusTransitions[currentStatus] || [];
  
    // Check if transition is valid
    const isValidTransition = allowedNextStatuses.includes(newStatus);
  
    if (!isValidTransition && currentStatus !== newStatus) {
      return {
        is_valid: false,
        status_code: 'REJECTED',
        message: '不正なステータス遷移です',
        allowed_next_statuses: allowedNextStatuses,
        transition_recorded: false,
      };
    }
  
    // Record transition in history
    if (currentStatus && newStatus && transitionTimestamp && dealId) {
      validateDealStatusTransitionStore.transitionHistory.push({
        deal_id: dealId,
        from_status: currentStatus,
        to_status: newStatus,
        timestamp: transitionTimestamp,
      });
    }
  
    // Determine if this is a no-change transition
    const isNoChange = currentStatus === newStatus;
  
    // Build result
    const result: ValidateDealStatusTransitionResult = {
      is_valid: true,
      isValid: true,
      status_code: 'APPROVED',
      message: 'ステータス遷移が承認されました',
      allowed_next_statuses: allowedNextStatuses,
      transition_recorded: true,
      dealStatus: newStatus,
      errorFlag: false,
      transactionStatus: 'completed',
    };
  
    // Add status history record if dealId and operatorId are provided
    if (dealId && operatorId !== undefined) {
      result.statusHistoryRecord = {
        dealId,
        fromStatus: currentStatus || '',
        toStatus: newStatus,
        changedAt: transitionTimestamp || new Date(),
        operatorId,
        isNoChange,
      };
    } else if (dealId) {
      result.statusHistoryRecord = {
        dealId,
        fromStatus: currentStatus || '',
        toStatus: newStatus,
        changedAt: transitionTimestamp || new Date(),
        isNoChange,
      };
    }
  
    return result;
  }
  return { validateDealStatusTransition };
})();
export const validateDealStatusTransition = __aivicBundle_13_validateDealStatusTransition.validateDealStatusTransition;
/* AIVIC_FUNCTION_BUNDLE_END owner=validateDealStatusTransition */

/* AIVIC_FUNCTION_BUNDLE_START owner=grantCustomerPortalAccess exports=grantCustomerPortalAccess */
const __aivicBundle_14_grantCustomerPortalAccess = (() => {
  interface GrantCustomerPortalAccessInput {
    negotiation_id?: string;
    dealId?: string;
    customer_id?: string;
    customerId?: string;
    customer_contact_email?: string;
    customer_contact_name?: string;
    customer_contact_list?: Array<{ email: string; name: string }>;
    old_status?: string;
    new_status?: string;
    dealStatus?: string;
    update_timestamp?: Date;
    updatedAt?: Date;
    existing_portal_user_id?: string;
    deal_amount?: number;
    dealAmount?: number;
    deal_title?: string;
    dealTitle?: string;
    created_at?: string;
    createdAt?: string;
  }
  
  interface GrantCustomerPortalAccessResult {
    success: boolean;
    access_granted: boolean;
    portal_user_id?: string;
    customer_contact_email?: string;
    permission_effective_timestamp?: Date;
    access_log_id?: string;
    message: string;
    accessPermissionStatus?: string;
    granted_count?: number;
    access_log_ids?: string[];
    is_duplicate_attempt?: boolean;
  }
  
  const grantCustomerPortalAccessStore: Map<
    string,
    { portal_user_id: string; granted_at: Date }
  > = new Map();
  
   function grantCustomerPortalAccess(
    input_data: GrantCustomerPortalAccessInput
  ): GrantCustomerPortalAccessResult {
    const negotiationId =
      input_data.negotiation_id || input_data.dealId || "";
    const customerId = input_data.customer_id || input_data.customerId || "";
    const contactEmail = input_data.customer_contact_email || "";
    const contactName =
      input_data.customer_contact_name || input_data.customer_contact_name || "";
    const oldStatus = input_data.old_status || "";
    const newStatus = input_data.new_status || input_data.dealStatus || "";
    const updateTimestamp =
      input_data.update_timestamp || input_data.updatedAt || new Date();
    
    const contactList = input_data.customer_contact_list;
  
    if (!negotiationId || negotiationId.trim() === "") {
      throw new Error("商談IDが指定されていません");
    }
  
    if (!customerId || customerId.trim() === "") {
      throw new Error("顧客IDが指定されていません");
    }
  
    if (!contactName || contactName.trim() === "") {
      throw new Error("顧客担当者名が指定されていません");
    }
  
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  
    if (contactEmail && !emailRegex.test(contactEmail)) {
      throw new Error("メールアドレスの形式が不正です");
    }
  
    if (
      contactList &&
      contactList.some((contact) => !emailRegex.test(contact.email))
    ) {
      throw new Error("メールアドレスの形式が不正です");
    }
  
    const isStatusTransitionValid =
      newStatus === "受注" && oldStatus !== newStatus;
  
    if (!isStatusTransitionValid) {
      return {
        success: true,
        access_granted: false,
        message: "権限付与対象外のステータス遷移です",
        accessPermissionStatus: "未付与",
      };
    }
  
    const contactsToGrant = contactList || [
      { email: contactEmail, name: contactName },
    ];
    const accessLogIds: string[] = [];
    let grantedCount = 0;
    let portalUserId: string | undefined;
    let isDuplicate = false;
  
    for (const contact of contactsToGrant) {
      const cacheKey = `${customerId}:${contact.email}`;
      const cached = grantCustomerPortalAccessStore.get(cacheKey);
  
      if (cached) {
        portalUserId = cached.portal_user_id;
        isDuplicate = true;
      } else {
        const newPortalUserId = `PU-${randomUUID()}`;
        const newAccessLogId = `LOG-${randomUUID()}`;
        grantCustomerPortalAccessStore.set(cacheKey, {
          portal_user_id: newPortalUserId,
          granted_at: updateTimestamp,
        });
        portalUserId = newPortalUserId;
        accessLogIds.push(newAccessLogId);
        grantedCount++;
      }
    }
  
    const permissionEffectiveTimestamp = new Date(updateTimestamp);
  
    return {
      success: true,
      access_granted: true,
      portal_user_id: portalUserId,
      customer_contact_email: contactEmail || contactList?.[0]?.email,
      permission_effective_timestamp: permissionEffectiveTimestamp,
      access_log_id: accessLogIds[0],
      message: isDuplicate
        ? "既に権限を保持しています"
        : "ポータルアクセス権限が正常に付与されました",
      granted_count: grantedCount > 0 ? grantedCount : contactsToGrant.length,
      access_log_ids: accessLogIds.length > 0 ? accessLogIds : undefined,
      is_duplicate_attempt: isDuplicate,
    };
  }
  return { grantCustomerPortalAccess };
})();
export const grantCustomerPortalAccess = __aivicBundle_14_grantCustomerPortalAccess.grantCustomerPortalAccess;
/* AIVIC_FUNCTION_BUNDLE_END owner=grantCustomerPortalAccess */

/* AIVIC_FUNCTION_BUNDLE_START owner=grantPortalAccessIfNotExists exports=grantPortalAccessIfNotExists */
const __aivicBundle_15_grantPortalAccessIfNotExists = (() => {
  interface GrantPortalAccessIfNotExistsInput {
    employee_id: string;
    customer_id: string;
  }
  
  interface GrantPortalAccessIfNotExistsResult {
    granted: boolean;
    permission_count: number;
    log_message: string;
    is_duplicate_attempt: boolean;
  }
  
  const grantPortalAccessIfNotExistsStore = new Map<
    string,
    Array<{ employee_id: string; customer_id: string; granted_at: string }>
  >();
  
   function grantPortalAccessIfNotExists(
    employeeId: string,
    input: GrantPortalAccessIfNotExistsInput
  ): GrantPortalAccessIfNotExistsResult {
    if (employeeId === undefined || employeeId === null) { throw new Error("employeeId is required"); }
    const key = `${input.employee_id}:${input.customer_id}`;
  
    if (!grantPortalAccessIfNotExistsStore.has(key)) {
      grantPortalAccessIfNotExistsStore.set(key, []);
    }
  
    const permissions = grantPortalAccessIfNotExistsStore.get(key)!;
  
    const existingPermission = permissions.find(
      (p) =>
        p.employee_id === input.employee_id &&
        p.customer_id === input.customer_id
    );
  
    if (existingPermission) {
      return {
        granted: false,
        permission_count: permissions.length,
        log_message: '既存権限を検出、付与スキップ',
        is_duplicate_attempt: true,
      };
    }
  
    const newPermission = {
      employee_id: input.employee_id,
      customer_id: input.customer_id,
      granted_at: new Date().toISOString(),
    };
  
    permissions.push(newPermission);
  
    return {
      granted: true,
      permission_count: permissions.length,
      log_message: 'ポータルアクセス権限を付与しました',
      is_duplicate_attempt: false,
    };
  }
  return { grantPortalAccessIfNotExists };
})();
export const grantPortalAccessIfNotExists = __aivicBundle_15_grantPortalAccessIfNotExists.grantPortalAccessIfNotExists;
/* AIVIC_FUNCTION_BUNDLE_END owner=grantPortalAccessIfNotExists */

/* AIVIC_FUNCTION_BUNDLE_START owner=createDeal exports=createDeal */
const __aivicBundle_16_createDeal = (() => {
  function createDeal(input: {
    dealId: string;
    customerId: string;
    dealTitle: string;
    initialStatus: string;
    amount: number;
    createdAt: Date;
  }): {
    dealId: string;
    customerId: string;
    dealTitle: string;
    status: string;
    amount: number;
    permissionGranted: boolean;
    createdAt: string;
  } {
    return {
      dealId: input.dealId,
      customerId: input.customerId,
      dealTitle: input.dealTitle,
      status: input.initialStatus,
      amount: input.amount,
      permissionGranted: false,
      createdAt: input.createdAt.toISOString()
    };
  }
  return { createDeal };
})();
export const createDeal = __aivicBundle_16_createDeal.createDeal;
/* AIVIC_FUNCTION_BUNDLE_END owner=createDeal */

/* AIVIC_FUNCTION_BUNDLE_START owner=updateDealStatus exports=updateDealStatus */
const __aivicBundle_17_updateDealStatus = (() => {
  const updateDealStatusStore = new Map<string, { status: string; updatedAt: Date; updatedBy: string }>();
  const portalAccessStore = new Map<string, { dealId: string; customerId: string; grantedAt: Date; grantedBy: string }>();
  const accessLogStore: Array<{
    logId: string;
    dealId: string;
    customerId: string;
    logType: string;
    grantedStatus: string;
    grantedAt: string;
    grantedBy: string;
  }> = [];
  
   function updateDealStatus(input: {
    dealId: string;
    customerId: string;
    newStatus: string;
    updatedAt: Date;
    updatedBy: string;
  }): {
    dealId: string;
    customerId: string;
    previousStatus: string;
    newStatus: string;
    permissionGranted: boolean;
    grantedAt: string;
  } {
    const { dealId, customerId, newStatus, updatedAt, updatedBy } = input;
  
    const storeKey = `${dealId}:${customerId}`;
    const currentRecord = updateDealStatusStore.get(storeKey);
    const previousStatus = currentRecord?.status ?? 'PROPOSAL_BEFORE';
  
    updateDealStatusStore.set(storeKey, {
      status: newStatus,
      updatedAt,
      updatedBy
    });
  
    const proposalStatuses = ['PROPOSAL_IN_PROGRESS', 'PROPOSAL_SUBMITTED', 'NEGOTIATION', 'CONTRACT_SIGNED', 'CONTRACTED', 'CLOSED_WON'];
    const shouldGrantPermission = proposalStatuses.includes(newStatus);
  
    if (shouldGrantPermission) {
      const accessKey = `${dealId}:${customerId}`;
      portalAccessStore.set(accessKey, {
        dealId,
        customerId,
        grantedAt: updatedAt,
        grantedBy: updatedBy
      });
  
      const { randomUUID } = require('crypto');
      const logId = randomUUID();
      accessLogStore.push({
        logId,
        dealId,
        customerId,
        logType: 'PERMISSION_GRANT',
        grantedStatus: newStatus,
        grantedAt: updatedAt.toISOString(),
        grantedBy: updatedBy
      });
    }
  
    return {
      dealId,
      customerId,
      previousStatus,
      newStatus,
      permissionGranted: shouldGrantPermission,
      grantedAt: updatedAt.toISOString()
    };
  }
  return { updateDealStatus };
})();
export const updateDealStatus = __aivicBundle_17_updateDealStatus.updateDealStatus;
/* AIVIC_FUNCTION_BUNDLE_END owner=updateDealStatus */

/* AIVIC_FUNCTION_BUNDLE_START owner=checkCustomerPortalAccess exports=checkCustomerPortalAccess */
const __aivicBundle_18_checkCustomerPortalAccess = (() => {
  interface CheckCustomerPortalAccessInput {
    customerId: string;
    dealId: string;
  }
  
  interface CheckCustomerPortalAccessOutput {
    hasAccess: boolean;
    reason: string;
  }
  
  const checkCustomerPortalAccessStore = new Map<
    string,
    { customerId: string; dealId: string; hasAccess: boolean; grantedAt?: string }
  >();
  
   function checkCustomerPortalAccess(
    input: CheckCustomerPortalAccessInput
  ): CheckCustomerPortalAccessOutput {
    const { customerId, dealId } = input;
  
    const key = `${customerId}:${dealId}`;
    const record = checkCustomerPortalAccessStore.get(key);
  
    if (record && record.hasAccess) {
      return {
        hasAccess: true,
        reason: 'PERMISSION_GRANTED_ON_STATUS_UPDATE'
      };
    }
  
    return {
      hasAccess: false,
      reason: 'DEAL_NOT_IN_PROPOSAL_STATUS'
    };
  }
  return { checkCustomerPortalAccess };
})();
export const checkCustomerPortalAccess = __aivicBundle_18_checkCustomerPortalAccess.checkCustomerPortalAccess;
/* AIVIC_FUNCTION_BUNDLE_END owner=checkCustomerPortalAccess */

/* AIVIC_FUNCTION_BUNDLE_START owner=getAccessLog exports=getAccessLog */
const __aivicBundle_19_getAccessLog = (() => {
  interface GetAccessLogInput {
    dealId: string;
    customerId: string;
    logType: string;
  }
  
  interface AccessLogEntry {
    logId: string;
    dealId: string;
    customerId: string;
    logType: string;
    grantedStatus: string;
    grantedAt: string;
    grantedBy: string;
  }
  
  interface GetAccessLogResult {
    recordCount: number;
    logs: AccessLogEntry[];
  }
  
  const getAccessLogStore = new Map<string, AccessLogEntry[]>();
  
   function getAccessLog(input: GetAccessLogInput): GetAccessLogResult {
    const { dealId, customerId, logType } = input;
  
    const key = `${dealId}:${customerId}:${logType}`;
    const logs = getAccessLogStore.get(key) || [];
  
    return {
      recordCount: logs.length,
      logs: logs
    };
  }
  return { getAccessLog };
})();
export const getAccessLog = __aivicBundle_19_getAccessLog.getAccessLog;
/* AIVIC_FUNCTION_BUNDLE_END owner=getAccessLog */
