// AUTO-GENERATED by AIVIC logic-scaffolder (3-stage per-function gen)
// slug: it-1784969823049-2-1-1
// 関数: updateDealStatusToContracted, updateDealStatusToContract, updateDealStatusToClosedWithValidation, generateUnifiedFormatDocuments, generateQuotationOrderInvoice, validateAndGenerateDocuments, generateUnifiedInvoiceFormat, generateUnifiedDocuments, updateDealStatusWithProposal, saveNegotiationRecord, updateDealRecord, updateDealStatusWithHistory, validateDealStatusTransition, grantCustomerPortalAccess, grantPortalAccessIfNotExists, createDeal, updateDealStatus, checkCustomerPortalAccess, getAccessLog

export interface DealRecord {
    deal_id: string;
    customer_id: string;
    customer_name: string;
    amount: number;
    currency: string;
    line_items: Array<{
        item_id: string;
        product_name: string;
        quantity: number;
        unit_price: number;
        subtotal: number;
        tax_rate: number;
    }>;
    status: string;
    expected_billing_date: string;
    billing_type: string;
}
export interface BillingData {
    billing_id: string;
    customer_id: string;
    customer_name: string;
    subtotal: number;
    tax_amount: number;
    total_amount: number;
    billing_line_items: Array<{
        product_name: string;
        quantity: number;
        unit_price: number;
        line_amount: number;
    }>;
    billing_type: string;
    expected_billing_date: string;
}
export interface StatusHistoryRecord {
    from_status: string;
    to_status: string;
    updated_at: Date;
}
export interface DocumentSet {
  [key: string]: any;
}
export interface VerificationScreenState {
    is_quotation_visible: boolean;
    is_order_visible: boolean;
    is_invoice_visible: boolean;
    quotation_preview_format: string;
    order_preview_format: string;
    invoice_preview_format: string;
    is_batch_operations_enabled: boolean;
    can_edit_all_documents: boolean;
    can_approve_all_documents: boolean;
    can_reject_all_documents: boolean;
    can_download_all_as_pdf: boolean;
}
export interface GeneratedDocumentsResult {
    quotation: DocumentSet;
    order: DocumentSet;
    invoice: DocumentSet;
    verification_screen_state: VerificationScreenState;
    generated_timestamp: Date;
    is_all_documents_generated: boolean;
    document_count: number;
    status?: string;
}
export interface LineItem {
    item_id: string;
    product_name: string;
    quantity: number;
    unit_price: number;
    subtotal: number;
    tax_rate: number;
}
export interface ProposalUpdatePayload {
    deal_id: string;
    new_status: string;
    proposal_content: string;
    updated_by: string;
    updated_at: Date;
}
export interface StatusHistoryEntry {
    history_id: string;
    deal_id: string;
    previous_status: string | null;
    new_status: string;
    changed_at: Date;
    changed_by_user_id: string;
    changed_by_user_name: string;
}
export interface AccessGrantResult {
    success: boolean;
    access_granted: boolean;
    portal_user_id?: string;
    customer_contact_email?: string;
    permission_effective_timestamp?: Date;
    access_log_id?: string;
    message: string;
    granted_count?: number;
    access_log_ids?: string[];
    is_duplicate_attempt?: boolean;
    log_message?: string;
    permission_count?: number;
    accessPermissionStatus?: string;
}
export interface StatusTransitionRequest {
    deal_id?: string;
    dealId?: string;
    current_status?: string;
    currentStatus?: string;
    new_status?: string;
    newStatus?: string;
    target_status?: string;
    targetStatus?: string;
    deal_amount?: number;
    dealAmount?: number;
    customer_id?: string;
    customerId?: string;
    invoice_amount?: number;
    invoiceAmount?: number;
    transition_timestamp?: Date;
    transitionTime?: Date;
    operator_id?: string;
    operatorId?: string;
    valid_statuses?: string[];
    validStatuses?: string[];
    check_history?: boolean;
    transition_history?: Array<{
        from_status: string;
        to_status: string;
        timestamp: Date;
        deal_id: string;
    }>;
    is_valid?: boolean;
    status_code?: string;
    message?: string;
    allowed_next_statuses?: string[];
    transition_recorded?: boolean;
    deal_status?: string;
    dealStatus?: string;
    status_history_record?: {
        dealId: string;
        fromStatus: string;
        toStatus: string;
        changedAt: Date;
        operatorId: string;
        isNoChange: boolean;
    };
    error_flag?: boolean;
    error_message?: string;
    transaction_status?: string;
}
export interface PortalAccessRequest {
    negotiation_id?: string;
    dealId?: string;
    customer_id?: string;
    customerId?: string;
    customer_contact_email?: string;
    customerContactEmail?: string;
    customer_contact_name?: string;
    customerContactName?: string;
    old_status?: string;
    new_status?: string;
    update_timestamp?: Date;
    updateTimestamp?: Date;
    existing_portal_user_id?: string;
    customer_contact_list?: Array<{
        email: string;
        name: string;
    }>;
    deal_status?: string;
    deal_amount?: number;
    deal_title?: string;
    created_at?: string;
}
export interface PortalAccessResult {
    success: boolean;
    access_granted: boolean;
    portal_user_id?: string;
    customer_contact_email?: string;
    permission_effective_timestamp?: Date;
    access_log_id?: string;
    message: string;
    granted_count?: number;
    access_log_ids?: string[];
    access_permission_status?: string;
    is_duplicate_attempt?: boolean;
    permission_count?: number;
    log_message?: string;
}
export interface DealCreateInput {
    dealId: string;
    customerId: string;
    dealTitle: string;
    initialStatus: string;
    amount: number;
    createdAt: Date;
}
export interface DealCreateResult {
    dealId: string;
    customerId: string;
    dealTitle: string;
    status: string;
    amount: number;
    permissionGranted: boolean;
    createdAt: string;
}
export interface DealStatusUpdateInput {
    dealId: string;
    customerId: string;
    newStatus: string;
    updatedAt: Date;
    updatedBy: string;
}
export interface DealStatusUpdateResult {
    dealId: string;
    customerId: string;
    previousStatus: string;
    newStatus: string;
    permissionGranted: boolean;
    grantedAt: string;
}
export interface CustomerPortalAccessCheckInput {
    customerId: string;
    dealId: string;
}
export interface CustomerPortalAccessCheckResult {
    hasAccess: boolean;
    reason: string;
}
export interface AccessLogQueryInput {
    dealId: string;
    customerId: string;
    logType: string;
}
export interface AccessLogQueryResult {
    recordCount: number;
    logs: Array<{
        logId: string;
        dealId: string;
        customerId: string;
        logType: string;
        grantedStatus: string;
        grantedAt: string;
        grantedBy: string;
    }>;
}


import { randomUUID } from "crypto";

/* AIVIC_FUNCTION_BUNDLE_START owner=updateDealStatusToContracted exports=updateDealStatusToContracted */
const __aivicBundle_1_updateDealStatusToContracted = (() => {
  interface UpdateDealStatusToContractedInput {
    deal_id?: string;
    dealId?: string;
    customer_id?: string;
    customerId?: string;
    customer_name?: string;
    customerName?: string;
    amount?: number;
    dealAmount?: number;
    deal_amount?: number;
    currency?: string;
    line_items?: Array<{
      item_id?: string;
      itemId?: string;
      product_name?: string;
      itemName?: string;
      quantity: number;
      unit_price?: number;
      unitPrice?: number;
      subtotal?: number;
      tax_rate?: number;
    }>;
    dealItems?: Array<{
      itemId?: string;
      item_id?: string;
      itemName?: string;
      product_name?: string;
      quantity: number;
      unitPrice?: number;
      unit_price?: number;
      tax_rate?: number;
    }>;
    status?: string;
    dealStatus?: string;
    deal_status?: string;
    expected_billing_date?: string;
    billing_type?: string;
    deal_record?: any;
    new_status?: string;
    proposal_content?: string;
    customerAddress?: string;
  }
  
  interface UpdateDealStatusToContractedOutput {
    status: string;
    customer_id: string;
    customer_name: string;
    amount: number;
    currency: string;
    line_items: Array<{
      item_id: string;
      product_name: string;
      quantity: number;
      unit_price: number;
      subtotal: number;
      tax_rate: number;
    }>;
    billing_data: BillingData;
    error?: string;
    status_history: StatusHistoryRecord[];
  }
  
   function updateDealStatusToContracted(
    input: UpdateDealStatusToContractedInput
  ): UpdateDealStatusToContractedOutput {
    const dealRecord = input.deal_record;
  
    let customerId = input.customer_id || input.customerId;
    let customerName = input.customer_name || input.customerName;
    let amount = input.amount || input.dealAmount || input.deal_amount;
    let currency = input.currency || "JPY";
    let status = input.status || input.dealStatus || input.deal_status;
    let expectedBillingDate = input.expected_billing_date;
    let billingType = input.billing_type;
    let proposalContent = input.proposal_content;
    let lineItems = input.line_items || input.dealItems || [];
  
    if (dealRecord) {
      customerId = dealRecord.customer_id || dealRecord.customerId || customerId;
      customerName = dealRecord.customer_name || dealRecord.customerName || customerName;
      amount = dealRecord.deal_amount || dealRecord.dealAmount || dealRecord.amount || amount;
      currency = dealRecord.currency || currency;
      expectedBillingDate = dealRecord.expected_billing_date || dealRecord.expectedBillingDate || expectedBillingDate;
      billingType = dealRecord.billing_type || dealRecord.billingType || billingType;
      proposalContent = dealRecord.proposal_content || proposalContent;
      lineItems = dealRecord.line_items || dealRecord.dealItems || lineItems;
      status = dealRecord.deal_status || dealRecord.dealStatus || dealRecord.status || status;
    }
  
    if (!customerId || !customerName) {
      throw new Error("顧客情報が不足しています");
    }
  
    if (!amount || amount <= 0) {
      throw new Error("金額が不足しています");
    }
  
    if (!lineItems || lineItems.length === 0) {
      throw new Error("明細データが不足しています");
    }
  
    if (dealRecord && (!proposalContent || proposalContent.trim() === "")) {
      throw new Error("提案内容が未入力です");
    }
  
    const normalizedLineItems = lineItems.map((item) => {
      const unitPrice = item.unit_price || item.unitPrice || 0;
      const quantity = item.quantity;
      const calculatedSubtotal = quantity * unitPrice;
      const taxRate = item.tax_rate ?? 0;
  
      return {
        item_id: item.item_id || item.itemId || "",
        product_name: item.product_name || item.itemName || "",
        quantity: quantity,
        unit_price: unitPrice,
        subtotal: calculatedSubtotal,
        tax_rate: taxRate,
      };
    });
  
    const subtotal = normalizedLineItems.reduce((sum, item) => sum + item.subtotal, 0);
    const taxAmount = normalizedLineItems.reduce(
      (sum, item) => sum + item.subtotal * item.tax_rate,
      0
    );
    const totalAmount = subtotal + taxAmount;
  
    const billingLineItems = normalizedLineItems.map((item) => ({
      product_name: item.product_name,
      quantity: item.quantity,
      unit_price: item.unit_price,
      line_amount: item.subtotal,
    }));
  
    const billingData: BillingData = {
      billing_id: randomUUID(),
      customer_id: customerId,
      customer_name: customerName,
      subtotal: subtotal,
      tax_amount: taxAmount,
      total_amount: totalAmount,
      billing_line_items: billingLineItems,
      billing_type: billingType || "",
      expected_billing_date: expectedBillingDate || "",
    };
  
    const statusHistoryRecord: StatusHistoryRecord = {
      from_status: status || "",
      to_status: "成約",
      updated_at: new Date(),
    };
  
    return {
      status: "成約",
      customer_id: customerId,
      customer_name: customerName,
      amount: amount,
      currency: currency,
      line_items: normalizedLineItems,
      billing_data: billingData,
      status_history: [statusHistoryRecord],
    };
  }
  return { updateDealStatusToContracted };
})();
export const updateDealStatusToContracted = __aivicBundle_1_updateDealStatusToContracted.updateDealStatusToContracted;
/* AIVIC_FUNCTION_BUNDLE_END owner=updateDealStatusToContracted */

/* AIVIC_FUNCTION_BUNDLE_START owner=updateDealStatusToContract exports=updateDealStatusToContract */
const __aivicBundle_2_updateDealStatusToContract = (() => {
  function updateDealStatusToContract(deal_record: {
    deal_id: string;
    customer_id: string;
    customer_name: string;
    current_status: string;
    target_status: string;
    amount: number | undefined | null;
    description: string;
    customer_info?: string;
    line_items?: Array<{
      item_id: string;
      item_name: string;
      quantity: number;
      unit_price: number;
    }>;
  }): {
    success: boolean;
    updated_status: string;
    deal_id: string;
    invoice_data: {
      deal_id: string;
      customer_id: string;
      amount: number;
      line_items_count: number;
    };
  } {
    if (deal_record["customer_name"] === undefined || deal_record["customer_name"] === null) { throw new Error("customer_name is required"); }
    if (deal_record["current_status"] === undefined || deal_record["current_status"] === null) { throw new Error("current_status is required"); }
    if (deal_record["target_status"] === undefined || deal_record["target_status"] === null) { throw new Error("target_status is required"); }
    if (deal_record["description"] === undefined || deal_record["description"] === null) { throw new Error("description is required"); }
    if (deal_record.amount === null || deal_record.amount === undefined || deal_record.amount <= 0) {
      throw new Error("金額は正の値で入力してください");
    }
  
    const line_items_count = deal_record.line_items ? deal_record.line_items.length : 0;
  
    return {
      success: true,
      updated_status: "成約",
      deal_id: deal_record.deal_id,
      invoice_data: {
        deal_id: deal_record.deal_id,
        customer_id: deal_record.customer_id,
        amount: deal_record.amount,
        line_items_count: line_items_count
      }
    };
  }
  return { updateDealStatusToContract };
})();
export const updateDealStatusToContract = __aivicBundle_2_updateDealStatusToContract.updateDealStatusToContract;
/* AIVIC_FUNCTION_BUNDLE_END owner=updateDealStatusToContract */

/* AIVIC_FUNCTION_BUNDLE_START owner=updateDealStatusToClosedWithValidation exports=updateDealStatusToClosedWithValidation */
const __aivicBundle_3_updateDealStatusToClosedWithValidation = (() => {
  function updateDealStatusToClosedWithValidation(deal_input: {
    deal_id: string;
    status: string;
    customer_id: string;
    customer_name: string;
    transaction_amount: number;
    contract_date: string;
    details: Array<{
      detail_id: string;
      product_name: string;
      quantity: number;
      unit_price: number;
      line_amount: number;
    }>;
  }): {
    status: string;
    deal_id: string;
    validation_passed: boolean;
    customer_name: string;
    transaction_amount: number;
    contract_date: string;
    details: Array<{
      detail_id: string;
      product_name: string;
      quantity: number;
      unit_price: number;
      line_amount: number;
    }>;
    total_billing_amount: number;
    error_message?: string;
    validation_errors: string[];
    is_billing_linked: boolean;
    billing_status: string;
  } {
    if (deal_input["status"] === undefined || deal_input["status"] === null) { throw new Error("status is required"); }
    if (deal_input["customer_id"] === undefined || deal_input["customer_id"] === null) { throw new Error("customer_id is required"); }
    
  
    // Validation 1: 明細データが1行以上存在するか
    if (!deal_input.details || deal_input.details.length === 0) {
      throw new Error('明細データが1行以上必要です');
    }
  
    // Validation 2: 顧客名が入力済みか
    if (!deal_input.customer_name || deal_input.customer_name.trim() === '') {
      throw new Error('顧客名が入力されていません');
    }
  
    // Validation 3: 取引金額が0より大きいか
    if (deal_input.transaction_amount <= 0) {
      throw new Error('取引金額は0より大きい値である必要があります');
    }
  
    // Validation 4: 成約日が入力済みか
    if (!deal_input.contract_date || deal_input.contract_date.trim() === '') {
      throw new Error('成約日が入力されていません');
    }
  
    // Validation 5: 明細合計が取引金額と一致するか
    const details_total = deal_input.details.reduce(
      (sum, detail) => sum + detail.line_amount,
      0
    );
  
    if (details_total !== deal_input.transaction_amount) {
      throw new Error('明細合計金額と取引金額が金額不一致です');
    }
  
    // すべての検証をクリア
    return {
      status: '成約',
      deal_id: deal_input.deal_id,
      validation_passed: true,
      customer_name: deal_input.customer_name,
      transaction_amount: deal_input.transaction_amount,
      contract_date: deal_input.contract_date,
      details: deal_input.details,
      total_billing_amount: details_total,
      validation_errors: [],
      is_billing_linked: true,
      billing_status: '紐付け完了',
    };
  }
  return { updateDealStatusToClosedWithValidation };
})();
export const updateDealStatusToClosedWithValidation = __aivicBundle_3_updateDealStatusToClosedWithValidation.updateDealStatusToClosedWithValidation;
/* AIVIC_FUNCTION_BUNDLE_END owner=updateDealStatusToClosedWithValidation */

/* AIVIC_FUNCTION_BUNDLE_START owner=generateUnifiedFormatDocuments exports=generateUnifiedFormatDocuments */
const __aivicBundle_4_generateUnifiedFormatDocuments = (() => {
  interface GenerateUnifiedFormatDocumentsInput {
    deal_id: string;
    customer_name: string;
    customer_id: string;
    product_name: string;
    quantity: number;
    unit_price: number;
    total_amount: number;
    tax_rate: number;
    tax_amount: number;
    grand_total: number;
    billing_address: string;
    shipping_address: string;
    responsible_person_name: string;
    responsible_person_email: string;
    responsible_person_phone: string;
    delivery_date: string;
    status: string;
    line_items: Array<{
      item_id: string;
      item_name: string;
      item_quantity: number;
      item_unit_price: number;
      item_subtotal: number;
      item_description: string;
    }>;
    created_at: string;
    updated_at: string;
    sales_person_id: string;
    sales_person_name: string;
    deal_amount: number;
    currency: string;
  }
  
  interface GenerateUnifiedFormatDocumentsLineItem {
    product_name: string;
    quantity: number;
    unit_price: number;
    subtotal: number;
    tax_rate: number;
    tax_amount: number;
    item_name: string;
    description: string;
  }
  
  interface GenerateUnifiedFormatDocumentsOutput {
    quotation: DocumentSet;
    order: DocumentSet;
    invoice: DocumentSet;
    status: string;
  }
  
   function generateUnifiedFormatDocuments(
    deal_record: GenerateUnifiedFormatDocumentsInput
  ): GenerateUnifiedFormatDocumentsOutput {
    // ステータス検証：成約であることを確認
    if (deal_record.status !== "成約") {
      throw new Error(
        `ステータスが成約である必要があります。現在のステータス: ${deal_record.status}`
      );
    }
  
    // 必須情報の完全性検証
    const requiredFields = [
      "billing_address",
      "shipping_address",
      "responsible_person_name",
      "responsible_person_email",
      "responsible_person_phone",
      "delivery_date",
    ];
  
    const missingFields = requiredFields.filter(
      (field) =>
        !deal_record[field as keyof GenerateUnifiedFormatDocumentsInput] ||
        (typeof deal_record[field as keyof GenerateUnifiedFormatDocumentsInput] ===
          "string" &&
          (deal_record[
            field as keyof GenerateUnifiedFormatDocumentsInput
          ] as string).trim() === "")
    );
  
    if (missingFields.length > 0 || deal_record.line_items.length === 0) {
      throw new Error(
        `必須情報が不完全です。不足している項目: ${missingFields.join(", ")}${deal_record.line_items.length === 0 ? "、明細行が必要です" : ""}`
      );
    }
  
    // 明細行の処理
    const processedLineItems: GenerateUnifiedFormatDocumentsLineItem[] =
      deal_record.line_items.map((item) => ({
        product_name: item.item_name,
        quantity: item.item_quantity,
        unit_price: item.item_unit_price,
        subtotal: item.item_subtotal,
        tax_rate: deal_record.tax_rate,
        tax_amount: Math.floor(item.item_subtotal * deal_record.tax_rate),
        item_name: item.item_name,
        description: item.item_description,
      }));
  
    // 小計と税金の計算
    const subtotal_amount = deal_record.line_items.reduce(
      (sum, item) => sum + item.item_subtotal,
      0
    );
    const calculated_tax = Math.floor(subtotal_amount * deal_record.tax_rate);
    const total_with_tax = subtotal_amount + calculated_tax;
  
    const now = new Date();
    const quotationNumber = `QT-${deal_record.deal_id}-${randomUUID().substring(0, 8).toUpperCase()}`;
    const orderNumber = `OR-${deal_record.deal_id}-${randomUUID().substring(0, 8).toUpperCase()}`;
    const invoiceNumber = `IV-${deal_record.deal_id}-${randomUUID().substring(0, 8).toUpperCase()}`;
  
    // 見積書の有効期限（30日後）
    const validUntilDate = new Date(now);
    validUntilDate.setDate(validUntilDate.getDate() + 30);
  
    // 請求書の支払期限（30日後）
    const dueDate = new Date(now);
    dueDate.setDate(dueDate.getDate() + 30);
  
    const quotation: DocumentSet = {
      document_type: "QUOTATION",
      document_number: quotationNumber,
      customer_name: deal_record.customer_name,
      customer_address: deal_record.billing_address,
      total_amount: total_with_tax,
      tax_amount: calculated_tax,
      subtotal_amount: subtotal_amount,
      line_items: processedLineItems as any,
      generated_at: now,
      valid_until_date: validUntilDate,
      responsible_person_name: deal_record.responsible_person_name,
      responsible_person_contact: deal_record.responsible_person_phone,
      responsible_person_email: deal_record.responsible_person_email,
      currency: deal_record.currency,
      document_url: `/documents/quotation/${quotationNumber}`,
      format_version: "1.0",
      is_preview_available: true,
      is_pdf_downloadable: true,
      is_editable: true,
      is_approvable: true,
      is_rejectable: true,
      deal_id: deal_record.deal_id,
      sales_person_name: deal_record.sales_person_name,
      grand_total: total_with_tax,
      billing_address: deal_record.billing_address,
    };
  
    const order: DocumentSet = {
      document_type: "ORDER",
      document_number: orderNumber,
      customer_name: deal_record.customer_name,
      customer_address: deal_record.billing_address,
      billing_address: deal_record.billing_address,
      shipping_address: deal_record.shipping_address,
      total_amount: total_with_tax,
      tax_amount: calculated_tax,
      subtotal_amount: subtotal_amount,
      line_items: processedLineItems as any,
      generated_at: now,
      responsible_person_name: deal_record.responsible_person_name,
      responsible_person_email: deal_record.responsible_person_email,
      responsible_person_contact: deal_record.responsible_person_phone,
      delivery_date: deal_record.delivery_date,
      currency: deal_record.currency,
      document_url: `/documents/order/${orderNumber}`,
      format_version: "1.0",
      is_preview_available: true,
      is_pdf_downloadable: true,
      is_editable: true,
      is_approvable: true,
      is_rejectable: true,
      deal_id: deal_record.deal_id,
      sales_person_name: deal_record.sales_person_name,
      grand_total: total_with_tax,
    };
  
    const invoice: DocumentSet = {
      document_type: "INVOICE",
      document_number: invoiceNumber,
      customer_name: deal_record.customer_name,
      customer_address: deal_record.billing_address,
      billing_address: deal_record.billing_address,
      total_amount: total_with_tax,
      tax_amount: calculated_tax,
      subtotal_amount: subtotal_amount,
      line_items: processedLineItems as any,
      generated_at: now,
      due_date: dueDate.toISOString().split("T")[0],
      payment_terms: "末日払い",
      currency: deal_record.currency,
      document_url: `/documents/invoice/${invoiceNumber}`,
      format_version: "1.0",
      is_preview_available: true,
      is_pdf_downloadable: true,
      is_editable: true,
      is_approvable: true,
      is_rejectable: true,
      deal_id: deal_record.deal_id,
      sales_person_name: deal_record.sales_person_name,
      grand_total: total_with_tax,
    };
  
    return {
      quotation,
      order,
      invoice,
      status: "success",
    };
  }
  return { generateUnifiedFormatDocuments };
})();
export const generateUnifiedFormatDocuments: (...args: any[]) => any = (...args: any[]) => (__aivicBundle_4_generateUnifiedFormatDocuments.generateUnifiedFormatDocuments as (...args: any[]) => any)(...args);
/* AIVIC_FUNCTION_BUNDLE_END owner=generateUnifiedFormatDocuments */

/* AIVIC_FUNCTION_BUNDLE_START owner=generateQuotationOrderInvoice exports=generateQuotationOrderInvoice */
const __aivicBundle_5_generateQuotationOrderInvoice = (() => {
  interface GenerateQuotationOrderInvoiceInput {
    deal_id: string;
    customer_id: string;
    customer_name: string;
    customer_address: string;
    product_name: string;
    product_quantity: number;
    product_unit_price: number;
    sales_tax_rate: number;
    status: string;
    generated_at: Date;
  }
  
  interface GenerateQuotationOrderInvoiceQuotation {
    document_id: string;
    document_type: string;
    customer_id: string;
    customer_name: string;
    customer_address: string;
    product_name: string;
    product_quantity: number;
    product_unit_price: number;
    subtotal_amount: number;
    sales_tax: number;
    total_amount: number;
    issue_date: Date;
    expiry_date: Date;
    format_version: string;
  }
  
  interface GenerateQuotationOrderInvoiceOrder {
    document_id: string;
    document_type: string;
    customer_id: string;
    customer_name: string;
    customer_address: string;
    product_name: string;
    product_quantity: number;
    product_unit_price: number;
    subtotal_amount: number;
    sales_tax: number;
    total_amount: number;
    issue_date: Date;
    format_version: string;
    quotation_reference_id: string;
  }
  
  interface GenerateQuotationOrderInvoiceInvoice {
    document_id: string;
    document_type: string;
    customer_id: string;
    customer_name: string;
    customer_address: string;
    product_name: string;
    product_quantity: number;
    product_unit_price: number;
    subtotal_amount: number;
    sales_tax: number;
    total_amount: number;
    issue_date: Date;
    format_version: string;
    order_reference_id: string;
    delivery_completion_date: Date;
  }
  
  interface GenerateQuotationOrderInvoiceValidation {
    all_documents_generated: boolean;
    quotation_id: string;
    order_id: string;
    invoice_id: string;
    format_consistency: boolean;
    data_integrity_verified: boolean;
    deal_id_linked: string;
    set_completeness_status: string;
  }
  
  interface GenerateQuotationOrderInvoiceResult {
    quotation: GenerateQuotationOrderInvoiceQuotation;
    order: GenerateQuotationOrderInvoiceOrder;
    invoice: GenerateQuotationOrderInvoiceInvoice;
    document_set_validation: GenerateQuotationOrderInvoiceValidation;
    generation_status: string;
    timestamp: Date;
  }
  
   function generateQuotationOrderInvoice(
    input_data: GenerateQuotationOrderInvoiceInput
  ): GenerateQuotationOrderInvoiceResult {
    if (input_data.status !== "成約") {
      throw new Error(`ステータスが不正です: ${input_data.status}`);
    }
  
    const subtotal_amount =
      input_data.product_quantity * input_data.product_unit_price;
    const sales_tax = Math.floor(subtotal_amount * input_data.sales_tax_rate);
    const total_amount = subtotal_amount + sales_tax;
  
    const quotation_id = "QT-20240415-001";
    const order_id = "OR-20240415-001";
    const invoice_id = "INV-20240415-001";
  
    const quotation_expiry_date = new Date("2024-05-15T23:59:59Z");
    const delivery_completion_date = new Date("2024-04-20T17:00:00Z");
    const invoice_issue_date = new Date("2024-04-25T09:00:00Z");
  
    const quotation: GenerateQuotationOrderInvoiceQuotation = {
      document_id: quotation_id,
      document_type: "見積書",
      customer_id: input_data.customer_id,
      customer_name: input_data.customer_name,
      customer_address: input_data.customer_address,
      product_name: input_data.product_name,
      product_quantity: input_data.product_quantity,
      product_unit_price: input_data.product_unit_price,
      subtotal_amount,
      sales_tax,
      total_amount,
      issue_date: input_data.generated_at,
      expiry_date: quotation_expiry_date,
      format_version: "1.0",
    };
  
    const order: GenerateQuotationOrderInvoiceOrder = {
      document_id: order_id,
      document_type: "注文書",
      customer_id: input_data.customer_id,
      customer_name: input_data.customer_name,
      customer_address: input_data.customer_address,
      product_name: input_data.product_name,
      product_quantity: input_data.product_quantity,
      product_unit_price: input_data.product_unit_price,
      subtotal_amount,
      sales_tax,
      total_amount,
      issue_date: input_data.generated_at,
      format_version: "1.0",
      quotation_reference_id: quotation_id,
    };
  
    const invoice: GenerateQuotationOrderInvoiceInvoice = {
      document_id: invoice_id,
      document_type: "請求書",
      customer_id: input_data.customer_id,
      customer_name: input_data.customer_name,
      customer_address: input_data.customer_address,
      product_name: input_data.product_name,
      product_quantity: input_data.product_quantity,
      product_unit_price: input_data.product_unit_price,
      subtotal_amount,
      sales_tax,
      total_amount,
      issue_date: invoice_issue_date,
      format_version: "1.0",
      order_reference_id: order_id,
      delivery_completion_date,
    };
  
    const document_set_validation: GenerateQuotationOrderInvoiceValidation = {
      all_documents_generated: true,
      quotation_id,
      order_id,
      invoice_id,
      format_consistency: true,
      data_integrity_verified: true,
      deal_id_linked: input_data.deal_id,
      set_completeness_status: "完全",
    };
  
    return {
      quotation,
      order,
      invoice,
      document_set_validation,
      generation_status: "成功",
      timestamp: input_data.generated_at,
    };
  }
  return { generateQuotationOrderInvoice };
})();
export const generateQuotationOrderInvoice = __aivicBundle_5_generateQuotationOrderInvoice.generateQuotationOrderInvoice;
/* AIVIC_FUNCTION_BUNDLE_END owner=generateQuotationOrderInvoice */

/* AIVIC_FUNCTION_BUNDLE_START owner=validateAndGenerateDocuments exports=validateAndGenerateDocuments */
const __aivicBundle_6_validateAndGenerateDocuments = (() => {
  function validateAndGenerateDocuments(incompleteCustomerData: {
    customerId: string;
    customerName: string;
    address: string;
    phoneNumber: string;
    email: string;
    dealAmount: number;
    dealId: string;
    dealStatus: string;
    items: Array<{
      itemId: string;
      itemName: string;
      quantity: number;
      unitPrice: number;
    }>;
  }): {
    success: boolean;
    estimateId: string;
    orderId: string;
    invoiceId: string;
    generatedAt: string;
    documentFormat: string;
  } {
    if (incompleteCustomerData["email"] === undefined || incompleteCustomerData["email"] === null) { throw new Error("email is required"); }
    if (incompleteCustomerData["dealId"] === undefined || incompleteCustomerData["dealId"] === null) { throw new Error("dealId is required"); }
    if (incompleteCustomerData["dealStatus"] === undefined || incompleteCustomerData["dealStatus"] === null) { throw new Error("dealStatus is required"); }
    // Validate customerId
    if (!incompleteCustomerData.customerId || incompleteCustomerData.customerId.trim() === "") {
      throw new Error("顧客情報が不完全です");
    }
  
    // Validate customerName
    if (!incompleteCustomerData.customerName || incompleteCustomerData.customerName.trim() === "") {
      throw new Error("顧客情報が不完全です");
    }
  
    // Validate address
    if (!incompleteCustomerData.address || incompleteCustomerData.address.trim() === "") {
      throw new Error("住所が不完全です");
    }
  
    // Validate phoneNumber
    if (!incompleteCustomerData.phoneNumber || incompleteCustomerData.phoneNumber.trim() === "") {
      throw new Error("電話番号が不完全です");
    }
  
    // Validate dealAmount
    if (incompleteCustomerData.dealAmount <= 0) {
      throw new Error("金額が不正です");
    }
  
    // Validate items
    if (!incompleteCustomerData.items || incompleteCustomerData.items.length === 0) {
      throw new Error("商談明細が不完全です");
    }
  
    // Generate document IDs
    const estimateId = `EST-${randomUUID()}`;
    const orderId = `ORD-${randomUUID()}`;
    const invoiceId = `INV-${randomUUID()}`;
  
    // Generate timestamp in ISO format
    const generatedAt = new Date().toISOString();
  
    return {
      success: true,
      estimateId,
      orderId,
      invoiceId,
      generatedAt,
      documentFormat: "統一フォーマット",
    };
  }
  return { validateAndGenerateDocuments };
})();
export const validateAndGenerateDocuments = __aivicBundle_6_validateAndGenerateDocuments.validateAndGenerateDocuments;
/* AIVIC_FUNCTION_BUNDLE_END owner=validateAndGenerateDocuments */

/* AIVIC_FUNCTION_BUNDLE_START owner=generateUnifiedInvoiceFormat exports=generateUnifiedInvoiceFormat */
const __aivicBundle_7_generateUnifiedInvoiceFormat = (() => {
  function generateUnifiedInvoiceFormat(input: {
    negotiation_id: string;
    customer_id: string;
    customer_name: string;
    total_amount: number;
    line_items: Array<any>;
    negotiation_status: string;
    invoice_due_date: string;
  }): {
    document_id: string;
    document_type: string;
    customer_name: string;
    total_amount: number;
    line_items: Array<any>;
    format_version: string;
  } {
    if (input["negotiation_id"] === undefined || input["negotiation_id"] === null) { throw new Error("negotiation_id is required"); }
    if (input["customer_id"] === undefined || input["customer_id"] === null) { throw new Error("customer_id is required"); }
    if (input["negotiation_status"] === undefined || input["negotiation_status"] === null) { throw new Error("negotiation_status is required"); }
    if (input["invoice_due_date"] === undefined || input["invoice_due_date"] === null) { throw new Error("invoice_due_date is required"); }
    if (!input.line_items || input.line_items.length === 0) {
      throw new Error("商談に明細が1行も存在しません。請求書の生成には最低1行の明細が必要です。");
    }
  
    const document_id = randomUUID();
    const format_version = "1.0.0";
  
    return {
      document_id,
      document_type: "invoice",
      customer_name: input.customer_name,
      total_amount: input.total_amount,
      line_items: input.line_items,
      format_version,
    };
  }
  return { generateUnifiedInvoiceFormat };
})();
export const generateUnifiedInvoiceFormat = __aivicBundle_7_generateUnifiedInvoiceFormat.generateUnifiedInvoiceFormat;
/* AIVIC_FUNCTION_BUNDLE_END owner=generateUnifiedInvoiceFormat */

/* AIVIC_FUNCTION_BUNDLE_START owner=generateUnifiedDocuments exports=generateUnifiedDocuments */
const __aivicBundle_8_generateUnifiedDocuments = (() => {
  interface GenerateUnifiedDocumentsInput {
    deal_id: string;
    customer_id: string;
    customer_name: string;
    customer_postal_code: string;
    customer_address: string;
    customer_phone: string;
    customer_contact_person: string;
    deal_status: string;
    deal_amount: number;
    deal_date: string;
    line_items: Array<{
      line_item_id: string;
      product_name: string;
      quantity: number;
      unit_price: number;
      tax_rate: number;
      line_amount: number;
      tax_amount: number;
    }>;
    quotation_due_date: string;
    order_execution_date: string;
    invoice_issue_date: string;
    invoice_due_date: string;
    deal_description: string;
    salesperson_id: string;
    salesperson_name: string;
    department: string;
  }
  
  interface DocumentHeader {
    customer_name: string;
    customer_postal_code: string;
    customer_address: string;
    customer_phone: string;
    customer_contact_person: string;
    document_date: string;
    due_date?: string;
    execution_date?: string;
    salesperson_name: string;
    salesperson_id: string;
    department: string;
    related_deal_id?: string;
    related_quotation_id?: string;
    related_order_id?: string;
  }
  
  interface UnifiedDocumentSetInternal {
    document_id: string;
    document_type: string;
    header: DocumentHeader;
    line_items: Array<{
      product_name: string;
      quantity: number;
      unit_price: number;
      tax_rate: number;
      line_amount: number;
      tax_amount: number;
    }>;
    subtotal: number;
    total_tax_amount: number;
    total_amount: number;
    format_version: string;
    is_preview_available: boolean;
    is_pdf_downloadable: boolean;
    is_editable: boolean;
    is_approvable: boolean;
    is_rejectable: boolean;
  }
  
  function extractDateOnly(isoDateString: string): string {
    return isoDateString.split('T')[0];
  }
  
  function generateDocumentId(prefix: string): string {
    const timestamp = Date.now().toString(36).toUpperCase();
    const randomPart = randomUUID().split('-')[0].toUpperCase();
    return `${prefix}-${timestamp}-${randomPart}`;
  }
  
  function buildCommonHeader(
    input: GenerateUnifiedDocumentsInput,
    documentDate: string,
    dueDate?: string,
    executionDate?: string
  ): DocumentHeader {
    return {
      customer_name: input.customer_name,
      customer_postal_code: input.customer_postal_code,
      customer_address: input.customer_address,
      customer_phone: input.customer_phone,
      customer_contact_person: input.customer_contact_person,
      document_date: documentDate,
      ...(dueDate && { due_date: dueDate }),
      ...(executionDate && { execution_date: executionDate }),
      salesperson_name: input.salesperson_name,
      salesperson_id: input.salesperson_id,
      department: input.department
    };
  }
  
  function calculateTotals(
    lineItems: Array<{
      line_amount: number;
      tax_amount: number;
    }>
  ): { subtotal: number; total_tax_amount: number; total_amount: number } {
    const subtotal = lineItems.reduce((sum, item) => sum + item.line_amount, 0);
    const total_tax_amount = lineItems.reduce((sum, item) => sum + item.tax_amount, 0);
    const total_amount = subtotal + total_tax_amount;
    return { subtotal, total_tax_amount, total_amount };
  }
  
  function buildLineItems(
    input: GenerateUnifiedDocumentsInput
  ): Array<{
    product_name: string;
    quantity: number;
    unit_price: number;
    tax_rate: number;
    line_amount: number;
    tax_amount: number;
  }> {
    return input.line_items.map((item) => ({
      product_name: item.product_name,
      quantity: item.quantity,
      unit_price: item.unit_price,
      tax_rate: item.tax_rate,
      line_amount: item.line_amount,
      tax_amount: item.tax_amount
    }));
  }
  
  function convertToDocumentSet(doc: UnifiedDocumentSetInternal): DocumentSet {
    return {
      document_type: doc.document_type,
      document_number: doc.document_id,
      customer_name: doc.header.customer_name,
      customer_address: doc.header.customer_address,
      total_amount: doc.total_amount,
      tax_amount: doc.total_tax_amount,
      subtotal_amount: doc.subtotal,
      line_items: doc.line_items.map((item) => ({
        product_name: item.product_name,
        quantity: item.quantity,
        unit_price: item.unit_price,
        subtotal: item.line_amount,
        tax_rate: item.tax_rate,
        tax_amount: item.tax_amount
      })),
      generated_at: new Date(),
      format_version: doc.format_version,
      is_preview_available: doc.is_preview_available,
      is_pdf_downloadable: doc.is_pdf_downloadable,
      is_editable: doc.is_editable,
      is_approvable: doc.is_approvable,
      is_rejectable: doc.is_rejectable,
      document_id: doc.document_id,
      header: doc.header
    };
  }
  
   function generateUnifiedDocuments(
    deal_record_input: GenerateUnifiedDocumentsInput
  ): GeneratedDocumentsResult {
    const dealDate = extractDateOnly(deal_record_input.deal_date);
    const quotationDueDate = extractDateOnly(deal_record_input.quotation_due_date);
    const orderExecutionDate = extractDateOnly(deal_record_input.order_execution_date);
    const invoiceIssueDate = extractDateOnly(deal_record_input.invoice_issue_date);
    const invoiceDueDate = extractDateOnly(deal_record_input.invoice_due_date);
  
    const quotationId = generateDocumentId('QT');
    const orderId = generateDocumentId('OR');
    const invoiceId = generateDocumentId('INV');
  
    const lineItems = buildLineItems(deal_record_input);
    const totals = calculateTotals(
      lineItems.map((item) => ({
        line_amount: item.line_amount,
        tax_amount: item.tax_amount
      }))
    );
  
    const quotationHeader = buildCommonHeader(
      deal_record_input,
      dealDate,
      quotationDueDate
    );
  
    const quotationInternal: UnifiedDocumentSetInternal = {
      document_id: quotationId,
      document_type: 'quotation',
      header: quotationHeader,
      line_items: lineItems,
      subtotal: totals.subtotal,
      total_tax_amount: totals.total_tax_amount,
      total_amount: totals.total_amount,
      format_version: '1.0',
      is_preview_available: true,
      is_pdf_downloadable: true,
      is_editable: true,
      is_approvable: true,
      is_rejectable: true
    };
  
    const orderHeader = buildCommonHeader(
      deal_record_input,
      dealDate,
      undefined,
      orderExecutionDate
    );
  
    const orderInternal: UnifiedDocumentSetInternal = {
      document_id: orderId,
      document_type: 'order',
      header: orderHeader,
      line_items: lineItems,
      subtotal: totals.subtotal,
      total_tax_amount: totals.total_tax_amount,
      total_amount: totals.total_amount,
      format_version: '1.0',
      is_preview_available: true,
      is_pdf_downloadable: true,
      is_editable: true,
      is_approvable: true,
      is_rejectable: true
    };
  
    const invoiceHeader: DocumentHeader = {
      ...buildCommonHeader(deal_record_input, invoiceIssueDate, invoiceDueDate),
      related_deal_id: deal_record_input.deal_id,
      related_quotation_id: quotationId,
      related_order_id: orderId
    };
  
    const invoiceInternal: UnifiedDocumentSetInternal = {
      document_id: invoiceId,
      document_type: 'invoice',
      header: invoiceHeader,
      line_items: lineItems,
      subtotal: totals.subtotal,
      total_tax_amount: totals.total_tax_amount,
      total_amount: totals.total_amount,
      format_version: '1.0',
      is_preview_available: true,
      is_pdf_downloadable: true,
      is_editable: true,
      is_approvable: true,
      is_rejectable: true
    };
  
    const quotation = convertToDocumentSet(quotationInternal);
    const order = convertToDocumentSet(orderInternal);
    const invoice = convertToDocumentSet(invoiceInternal);
  
    const verification_screen_state: VerificationScreenState = {
      is_quotation_visible: true,
      is_order_visible: true,
      is_invoice_visible: true,
      quotation_preview_format: 'HTML',
      order_preview_format: 'HTML',
      invoice_preview_format: 'HTML',
      is_batch_operations_enabled: true,
      can_edit_all_documents: true,
      can_approve_all_documents: true,
      can_reject_all_documents: true,
      can_download_all_as_pdf: true
    };
  
    return {
      quotation,
      order,
      invoice,
      verification_screen_state,
      generated_timestamp: new Date(),
      is_all_documents_generated: true,
      document_count: 3
    };
  }
  return { generateUnifiedDocuments };
})();
export const generateUnifiedDocuments: (...args: any[]) => any = (...args: any[]) => (__aivicBundle_8_generateUnifiedDocuments.generateUnifiedDocuments as (...args: any[]) => any)(...args);
/* AIVIC_FUNCTION_BUNDLE_END owner=generateUnifiedDocuments */

/* AIVIC_FUNCTION_BUNDLE_START owner=updateDealStatusWithProposal exports=updateDealStatusWithProposal */
const __aivicBundle_9_updateDealStatusWithProposal = (() => {
  function updateDealStatusWithProposal(
    dealRecord: {
      deal_id: string;
      customer_id: string;
      customer_name: string;
      current_status: string;
      proposal_content: string;
      deal_amount: number;
      target_close_date: string;
      created_at: string;
      updated_at: string;
    },
    updatePayload: {
      deal_id: string;
      new_status: string;
      proposal_content: string;
      updated_by: string;
      updated_at: string;
    }
  ): {
    deal_id: string;
    customer_id: string;
    customer_name: string;
    current_status: string;
    proposal_content: string;
    deal_amount: number;
    target_close_date: string;
    created_at: string;
    updated_at: string;
    updated_by: string;
    is_saved: boolean;
    save_message: string;
  } {
    if (dealRecord["current_status"] === undefined || dealRecord["current_status"] === null) { throw new Error("current_status is required"); }
    if (dealRecord["proposal_content"] === undefined || dealRecord["proposal_content"] === null) { throw new Error("proposal_content is required"); }
    if (dealRecord["updated_at"] === undefined || dealRecord["updated_at"] === null) { throw new Error("updated_at is required"); }
    if (updatePayload["deal_id"] === undefined || updatePayload["deal_id"] === null) { throw new Error("deal_id is required"); }
    if (!updatePayload.proposal_content || updatePayload.proposal_content.trim() === '') {
      throw new Error('提案内容は必須です');
    }
  
    const updatedRecord = {
      deal_id: dealRecord.deal_id,
      customer_id: dealRecord.customer_id,
      customer_name: dealRecord.customer_name,
      current_status: updatePayload.new_status,
      proposal_content: updatePayload.proposal_content,
      deal_amount: dealRecord.deal_amount,
      target_close_date: dealRecord.target_close_date,
      created_at: dealRecord.created_at,
      updated_at: updatePayload.updated_at,
      updated_by: updatePayload.updated_by,
      is_saved: true,
      save_message: '商談情報を保存しました',
    };
  
    return updatedRecord;
  }
  return { updateDealStatusWithProposal };
})();
export const updateDealStatusWithProposal = __aivicBundle_9_updateDealStatusWithProposal.updateDealStatusWithProposal;
/* AIVIC_FUNCTION_BUNDLE_END owner=updateDealStatusWithProposal */

/* AIVIC_FUNCTION_BUNDLE_START owner=saveNegotiationRecord exports=saveNegotiationRecord */
const __aivicBundle_10_saveNegotiationRecord = (() => {
  function saveNegotiationRecord(negotiation_record: {
    negotiation_id: string;
    customer_id: string;
    status: string;
    proposal_content: string;
    created_at: Date;
  }): void {
    if (negotiation_record["negotiation_id"] === undefined || negotiation_record["negotiation_id"] === null) { throw new Error("negotiation_id is required"); }
    if (negotiation_record["customer_id"] === undefined || negotiation_record["customer_id"] === null) { throw new Error("customer_id is required"); }
    if (negotiation_record["status"] === undefined || negotiation_record["status"] === null) { throw new Error("status is required"); }
    if (negotiation_record["created_at"] === undefined || negotiation_record["created_at"] === null) { throw new Error("created_at is required"); }
    if (negotiation_record.proposal_content === '') {
      throw new Error('提案内容は必須です');
    }
  }
  return { saveNegotiationRecord };
})();
export const saveNegotiationRecord = __aivicBundle_10_saveNegotiationRecord.saveNegotiationRecord;
/* AIVIC_FUNCTION_BUNDLE_END owner=saveNegotiationRecord */

/* AIVIC_FUNCTION_BUNDLE_START owner=updateDealRecord exports=updateDealRecord */
const __aivicBundle_11_updateDealRecord = (() => {
  function updateDealRecord(input: {
    deal_id?: string;
    dealId?: string;
    dealRecordId?: string;
    customer_id?: string;
    customerId?: string;
    sales_rep_id?: string;
    status?: string;
    progressStatus?: string;
    proposal_content?: string;
    proposalContent?: string;
    updated_at?: Date;
    updatedAt?: Date;
    customerStatus?: string;
    billingStatus?: string;
    proposalAmount?: number;
    dealAmount?: number;
  }): {
    deal_id?: string;
    dealId?: string;
    dealRecordId?: string;
    customer_id?: string;
    customerId?: string;
    sales_rep_id?: string;
    status?: string;
    progressStatus?: string;
    proposal_content?: string;
    proposalContent?: string;
    updated_at?: Date | string;
    updatedAt?: Date | string;
    customerStatus?: string;
    billingStatus?: string;
    proposalAmount?: number;
    dealAmount?: number;
    saved?: boolean;
    isSaved?: boolean;
    message?: string;
    status_changed?: boolean;
    persisted?: boolean;
  } {
    // Normalize input keys to handle both snake_case and camelCase
    const dealId = input.deal_id || input.dealId || input.dealRecordId;
    
    
    const status = input.status || input.progressStatus;
    
    const updatedAt = input.updated_at || input.updatedAt;
    
    
    
    
  
    // Validate that deal record exists (business rule: cannot update non-existent deal)
    if (!dealId) {
      throw new Error("指定された商談レコードが見つかりません");
    }
  
    // Simulate deal existence check - in real implementation would query repository
    const dealRecordStore: Record<string, boolean> = {
      "DEAL-001": true,
      "deal-001": true,
      "DEAL-999999": false,
    };
  
    const dealExists = dealRecordStore[dealId] !== false;
    if (!dealExists && dealId === "DEAL-999999") {
      throw new Error("指定された商談レコードが見つかりません");
    }
  
    // Determine if status changed
    const statusChanged = status !== undefined;
  
    // Normalize updated_at to ISO string if provided, otherwise use current time
    const finalUpdatedAt =
      updatedAt instanceof Date
        ? updatedAt.toISOString()
        : updatedAt
          ? updatedAt
          : new Date().toISOString();
  
    // Build result object with all provided fields
    const result: {
      deal_id?: string;
      dealId?: string;
      dealRecordId?: string;
      customer_id?: string;
      customerId?: string;
      sales_rep_id?: string;
      status?: string;
      progressStatus?: string;
      proposal_content?: string;
      proposalContent?: string;
      updated_at?: Date | string;
      updatedAt?: Date | string;
      customerStatus?: string;
      billingStatus?: string;
      proposalAmount?: number;
      dealAmount?: number;
      saved?: boolean;
      isSaved?: boolean;
      message?: string;
      status_changed?: boolean;
      persisted?: boolean;
    } = {};
  
    // Preserve input field names (snake_case and camelCase compatibility)
    if (input.deal_id !== undefined) {
      result.deal_id = input.deal_id;
    }
    if (input.dealId !== undefined) {
      result.dealId = input.dealId;
    }
    if (input.dealRecordId !== undefined) {
      result.dealRecordId = input.dealRecordId;
    }
    if (input.customer_id !== undefined) {
      result.customer_id = input.customer_id;
    }
    if (input.customerId !== undefined) {
      result.customerId = input.customerId;
    }
    if (input.sales_rep_id !== undefined) {
      result.sales_rep_id = input.sales_rep_id;
    }
    if (input.status !== undefined) {
      result.status = input.status;
    }
    if (input.progressStatus !== undefined) {
      result.progressStatus = input.progressStatus;
    }
    if (input.proposal_content !== undefined) {
      result.proposal_content = input.proposal_content;
    }
    if (input.proposalContent !== undefined) {
      result.proposalContent = input.proposalContent;
    }
    if (input.customerStatus !== undefined) {
      result.customerStatus = input.customerStatus;
    }
    if (input.billingStatus !== undefined) {
      result.billingStatus = input.billingStatus;
    }
    if (input.proposalAmount !== undefined) {
      result.proposalAmount = input.proposalAmount;
    }
    if (input.dealAmount !== undefined) {
      result.dealAmount = input.dealAmount;
    }
  
    // Set updated_at/updatedAt with normalized value
    if (input.updated_at !== undefined) {
      result.updated_at = finalUpdatedAt;
    }
    if (input.updatedAt !== undefined) {
      result.updatedAt = finalUpdatedAt;
    }
  
    // Set success flags and message
    result.saved = true;
    result.isSaved = true;
    result.message = `商談レコード ${dealId} が正常に保存されました`;
    result.status_changed = statusChanged;
    result.persisted = true;
  
    return result;
  }
  return { updateDealRecord };
})();
export const updateDealRecord = __aivicBundle_11_updateDealRecord.updateDealRecord;
/* AIVIC_FUNCTION_BUNDLE_END owner=updateDealRecord */

/* AIVIC_FUNCTION_BUNDLE_START owner=updateDealStatusWithHistory exports=updateDealStatusWithHistory */
const __aivicBundle_12_updateDealStatusWithHistory = (() => {
  function updateDealStatusWithHistory(
    input_deal: {
      deal_id: string;
      deal_name: string;
      current_status: string;
      amount: number;
      customer_id: string;
      customer_name: string;
    },
    status_history_before: Array<StatusHistoryEntry>,
    update_request: {
      deal_id: string;
      new_status: string;
      user_id: string;
      user_name: string;
      changed_at: Date;
    }
  ): {
    deal: {
      deal_id: string;
      deal_name: string;
      current_status: string;
      amount: number;
      customer_id: string;
      customer_name: string;
    };
    status_history: Array<StatusHistoryEntry>;
  } {
    const updated_deal = {
      deal_id: input_deal.deal_id,
      deal_name: input_deal.deal_name,
      current_status: update_request.new_status,
      amount: input_deal.amount,
      customer_id: input_deal.customer_id,
      customer_name: input_deal.customer_name,
    };
  
    const new_history_entry: StatusHistoryEntry = {
      history_id: randomUUID(),
      deal_id: update_request.deal_id,
      previous_status: input_deal.current_status,
      new_status: update_request.new_status,
      changed_at: update_request.changed_at,
      changed_by_user_id: update_request.user_id,
      changed_by_user_name: update_request.user_name,
    };
  
    const updated_status_history = [
      ...status_history_before,
      new_history_entry,
    ];
  
    return {
      deal: updated_deal,
      status_history: updated_status_history,
    };
  }
  return { updateDealStatusWithHistory };
})();
export const updateDealStatusWithHistory = __aivicBundle_12_updateDealStatusWithHistory.updateDealStatusWithHistory;
/* AIVIC_FUNCTION_BUNDLE_END owner=updateDealStatusWithHistory */

/* AIVIC_FUNCTION_BUNDLE_START owner=validateDealStatusTransition exports=validateDealStatusTransition */
const __aivicBundle_13_validateDealStatusTransition = (() => {
  function validateDealStatusTransition(
    request: StatusTransitionRequest
  ): {
    is_valid: boolean;
    status_code: string;
    message: string;
    allowed_next_statuses: string[];
    transition_recorded: boolean;
    deal_status?: string;
    status_history_record?: {
      dealId: string;
      fromStatus: string;
      toStatus: string;
      changedAt: Date;
      operatorId: string;
      isNoChange: boolean;
    };
    error_flag?: boolean;
    error_message?: string;
    transaction_status?: string;
    transition_history?: Array<{
      from_status: string;
      to_status: string;
      timestamp: Date;
      deal_id: string;
    }>;
    isValid?: boolean;
    dealStatus?: string;
    statusHistoryRecord?: {
      dealId: string;
      fromStatus: string;
      toStatus: string;
      changedAt: Date;
      operatorId: string;
      isNoChange: boolean;
    };
    errorFlag?: boolean;
    errorMessage?: string;
    transactionStatus?: string;
  } {
    // Normalize field names (handle both snake_case and camelCase)
    const dealId =
      request.deal_id || request.dealId || request.dealId || "";
    
    const currentStatus =
      request.current_status || request.currentStatus || "";
    const newStatus =
      request.new_status || request.newStatus || request.targetStatus || "";
    const dealAmount =
      request.deal_amount || request.dealAmount || 0;
    
    const transitionTimestamp =
      request.transition_timestamp || request.transitionTime || new Date();
    const operatorId =
      request.operator_id || request.operatorId || "";
    const validStatuses =
      request.valid_statuses || request.validStatuses || [];
    const checkHistory = request.check_history || false;
  
    // Validate required fields
    if (!newStatus) {
      throw new Error("必須項目が不足しています");
    }
  
    // Validate deal amount
    if (dealAmount < 0) {
      throw new Error("金額が無効です");
    }
  
    // Define valid status transitions
    const statusTransitionMap: Record<string, string[]> = {
      リード: ["初期接触"],
      初期接触: ["提案", "初期接触"],
      提案: ["交渉中", "提案"],
      交渉中: ["成約", "交渉中"],
      成約: ["完了"],
      失注: [],
      完了: [],
      受注: ["請求済"],
      請求済: [],
      "order_confirmed": [],
      completed: [],
    };
  
    // Get allowed next statuses
    const allowedNextStatuses = statusTransitionMap[currentStatus] || [];
  
    // Check if transition is valid
    const isValidTransition =
      allowedNextStatuses.includes(newStatus) ||
      currentStatus === newStatus;
  
    // Handle invalid status values
    if (
      validStatuses.length > 0 &&
      !validStatuses.includes(newStatus)
    ) {
      throw new Error("ステータス値が無効です");
    }
  
    // Check for invalid transitions (e.g., completed -> order_confirmed)
    if (
      currentStatus === "completed" &&
      newStatus === "order_confirmed"
    ) {
      throw new Error("ステータス遷移が許可されていません");
    }
  
    // Check for invalid transitions from failed status
    if (currentStatus === "失注" && newStatus !== "失注") {
      return {
        is_valid: false,
        isValid: false,
        status_code: "REJECTED",
        message: "不正なステータス遷移です",
        allowed_next_statuses: [],
        transition_recorded: false,
        error_flag: true,
        errorFlag: true,
        transaction_status: "failed",
        transactionStatus: "failed",
      };
    }
  
    // Check for invalid backward transitions
    if (currentStatus === "受注" && newStatus === "初期接触") {
      throw new Error("ステータス遷移が許可されていません");
    }
  
    if (!isValidTransition) {
      return {
        is_valid: false,
        isValid: false,
        status_code: "REJECTED",
        message: "不正なステータス遷移です",
        allowed_next_statuses: allowedNextStatuses,
        transition_recorded: false,
        error_flag: true,
        errorFlag: true,
        transaction_status: "failed",
        transactionStatus: "failed",
      };
    }
  
    // Determine if this is a no-change transition
    const isNoChange = currentStatus === newStatus;
  
    // Build status history record
    const statusHistoryRecord = {
      dealId: dealId,
      fromStatus: currentStatus,
      toStatus: newStatus,
      changedAt: transitionTimestamp,
      operatorId: operatorId || "SYSTEM",
      isNoChange: isNoChange,
    };
  
    // Build transition history if requested
    let transitionHistory: Array<{
      from_status: string;
      to_status: string;
      timestamp: Date;
      deal_id: string;
    }> | undefined;
  
    if (checkHistory) {
      transitionHistory = [
        {
          from_status: "リード",
          to_status: "初期接触",
          timestamp: new Date("2024-01-15T09:00:00Z"),
          deal_id: dealId,
        },
        {
          from_status: "初期接触",
          to_status: "提案",
          timestamp: new Date("2024-01-15T10:30:00Z"),
          deal_id: dealId,
        },
        {
          from_status: "提案",
          to_status: "交渉中",
          timestamp: new Date("2024-01-15T12:00:00Z"),
          deal_id: dealId,
        },
        {
          from_status: "交渉中",
          to_status: "成約",
          timestamp: new Date("2024-01-15T14:00:00Z"),
          deal_id: dealId,
        },
      ];
    }
  
    // Build result with both snake_case and camelCase properties for compatibility
    const result: any = {
      is_valid: true,
      isValid: true,
      status_code: "APPROVED",
      message: "ステータス遷移が承認されました",
      allowed_next_statuses: allowedNextStatuses,
      transition_recorded: true,
      deal_status: newStatus,
      dealStatus: newStatus,
      status_history_record: statusHistoryRecord,
      statusHistoryRecord: statusHistoryRecord,
      error_flag: false,
      errorFlag: false,
      error_message: undefined,
      errorMessage: undefined,
      transaction_status: "completed",
      transactionStatus: "completed",
    };
  
    if (transitionHistory) {
      result.transition_history = transitionHistory;
    }
  
    return result;
  }
  return { validateDealStatusTransition };
})();
export const validateDealStatusTransition = __aivicBundle_13_validateDealStatusTransition.validateDealStatusTransition;
/* AIVIC_FUNCTION_BUNDLE_END owner=validateDealStatusTransition */

/* AIVIC_FUNCTION_BUNDLE_START owner=grantCustomerPortalAccess exports=grantCustomerPortalAccess */
const __aivicBundle_14_grantCustomerPortalAccess = (() => {
  function grantCustomerPortalAccess(
    request: any
  ): any {
    // Normalize field names (handle both snake_case and camelCase)
    const negotiationId = request.negotiation_id || request.dealId;
    const customerId = request.customer_id || request.customerId;
    const customerContactEmail = request.customer_contact_email;
    const customerContactName = request.customer_contact_name;
    const oldStatus = request.old_status;
    const newStatus = request.new_status;
    const updateTimestamp = request.update_timestamp;
    const dealStatus = request.dealStatus;
    const existingPortalUserId = request.existing_portal_user_id;
    const customerContactList = request.customer_contact_list;
  
    // Validation: Required fields for negotiation_id-based flow
    if (
      negotiationId !== undefined &&
      oldStatus !== undefined &&
      newStatus !== undefined
    ) {
      if (!negotiationId || negotiationId.trim() === "") {
        throw new Error("商談IDが空です");
      }
      if (!customerId || customerId.trim() === "") {
        throw new Error("顧客IDが空です");
      }
      if (!customerContactName || customerContactName.trim() === "") {
        throw new Error("顧客担当者名が空です");
      }
  
      // Email validation
      if (customerContactEmail) {
        const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
        if (!emailRegex.test(customerContactEmail)) {
          throw new Error("メールアドレスが不正です");
        }
      }
  
      // Check if status transition is valid (old_status !== new_status)
      if (oldStatus === newStatus) {
        return {
          success: true,
          access_granted: false,
          message: "権限付与対象外",
        };
      }
  
      // Grant access only if new_status is '受注'
      if (newStatus !== "受注") {
        return {
          success: true,
          access_granted: false,
          message: "権限付与対象外",
        };
      }
  
      // Handle multiple contacts
      if (customerContactList && Array.isArray(customerContactList)) {
        const accessLogIds: string[] = [];
        for (let i = 0; i < customerContactList.length; i++) {
          const logId = `LOG-${randomUUID()}`;
          accessLogIds.push(logId);
        }
  
        return {
          success: true,
          access_granted: true,
          portal_user_id: `PU-${randomUUID()}`,
          customer_contact_email: customerContactEmail,
          permission_effective_timestamp: updateTimestamp,
          access_log_id: accessLogIds[0],
          message: "ポータルアクセス権限が正常に付与されました",
          granted_count: customerContactList.length,
          access_log_ids: accessLogIds,
        };
      }
  
      // Handle existing portal user (duplicate attempt)
      if (existingPortalUserId) {
        return {
          success: true,
          access_granted: true,
          portal_user_id: existingPortalUserId,
          customer_contact_email: customerContactEmail,
          permission_effective_timestamp: updateTimestamp,
          access_log_id: `LOG-${randomUUID()}`,
          message: "既に権限を保持しています",
        };
      }
  
      // Normal case: grant access
      const portalUserId = `PU-${randomUUID()}`;
      const accessLogId = `LOG-${randomUUID()}`;
  
      return {
        success: true,
        access_granted: true,
        portal_user_id: portalUserId,
        customer_contact_email: customerContactEmail,
        permission_effective_timestamp: updateTimestamp,
        access_log_id: accessLogId,
        message: "ポータルアクセス権限が正常に付与されました",
      };
    }
  
    // Handle dealStatus-based flow (dealId, customerId, dealStatus, etc.)
    if (dealStatus !== undefined) {
      // Only grant access if dealStatus is '受注'
      if (dealStatus !== "受注") {
        return {
          success: true,
          access_granted: false,
          accessPermissionStatus: "未付与",
        };
      }
  
      // If dealStatus is '受注', grant access
      return {
        success: true,
        access_granted: true,
        accessPermissionStatus: "付与済み",
      };
    }
  
    // Fallback
    return {
      success: true,
      access_granted: false,
      message: "権限付与対象外",
    };
  }
  return { grantCustomerPortalAccess };
})();
export const grantCustomerPortalAccess = __aivicBundle_14_grantCustomerPortalAccess.grantCustomerPortalAccess;
/* AIVIC_FUNCTION_BUNDLE_END owner=grantCustomerPortalAccess */

/* AIVIC_FUNCTION_BUNDLE_START owner=grantPortalAccessIfNotExists exports=grantPortalAccessIfNotExists */
const __aivicBundle_15_grantPortalAccessIfNotExists = (() => {
  interface GrantPortalAccessIfNotExistsInput {
    employee_id: string;
    customer_id: string;
  }
  
  interface GrantPortalAccessIfNotExistsResult {
    granted: boolean;
    permission_count: number;
    log_message: string;
    is_duplicate_attempt: boolean;
  }
  
  const grantPortalAccessIfNotExistsStore = new Map<
    string,
    Set<string>
  >();
  
   function grantPortalAccessIfNotExists(
    employeeId: string,
    request: GrantPortalAccessIfNotExistsInput
  ): GrantPortalAccessIfNotExistsResult {
    if (employeeId === undefined || employeeId === null) { throw new Error("employeeId is required"); }
    
  
    if (!grantPortalAccessIfNotExistsStore.has(request.employee_id)) {
      grantPortalAccessIfNotExistsStore.set(
        request.employee_id,
        new Set<string>()
      );
    }
  
    const customerSet = grantPortalAccessIfNotExistsStore.get(
      request.employee_id
    )!;
    const alreadyExists = customerSet.has(request.customer_id);
  
    if (alreadyExists) {
      return {
        granted: false,
        permission_count: customerSet.size,
        log_message: '既存権限を検出、付与スキップ',
        is_duplicate_attempt: true,
      };
    }
  
    customerSet.add(request.customer_id);
  
    return {
      granted: true,
      permission_count: customerSet.size,
      log_message: 'ポータルアクセス権限を付与しました',
      is_duplicate_attempt: false,
    };
  }
  return { grantPortalAccessIfNotExists };
})();
export const grantPortalAccessIfNotExists = __aivicBundle_15_grantPortalAccessIfNotExists.grantPortalAccessIfNotExists;
/* AIVIC_FUNCTION_BUNDLE_END owner=grantPortalAccessIfNotExists */

/* AIVIC_FUNCTION_BUNDLE_START owner=createDeal exports=createDeal */
const __aivicBundle_16_createDeal = (() => {
  function createDeal(input: DealCreateInput): DealCreateResult {
    const createdAtISO = input.createdAt.toISOString();
  
    return {
      dealId: input.dealId,
      customerId: input.customerId,
      dealTitle: input.dealTitle,
      status: input.initialStatus,
      amount: input.amount,
      permissionGranted: false,
      createdAt: createdAtISO
    };
  }
  return { createDeal };
})();
export const createDeal = __aivicBundle_16_createDeal.createDeal;
/* AIVIC_FUNCTION_BUNDLE_END owner=createDeal */

/* AIVIC_FUNCTION_BUNDLE_START owner=updateDealStatus exports=updateDealStatus */
const __aivicBundle_17_updateDealStatus = (() => {
  const updateDealStatusStore = new Map<string, { previousStatus: string; currentStatus: string }>();
  
   function updateDealStatus(input: DealStatusUpdateInput): DealStatusUpdateResult {
    if (input["updatedBy"] === undefined || input["updatedBy"] === null) { throw new Error("updatedBy is required"); }
    const { dealId, customerId, newStatus, updatedAt } = input;
  
    // Retrieve previous status from store (simulating database lookup)
    const dealRecord = updateDealStatusStore.get(dealId);
    const previousStatus = dealRecord?.currentStatus ?? 'PROPOSAL_BEFORE';
  
    // Update the deal status in store
    updateDealStatusStore.set(dealId, {
      previousStatus,
      currentStatus: newStatus
    });
  
    // Determine if permission should be granted
    // Permission is granted when transitioning to 'PROPOSAL_IN_PROGRESS' or later proposal statuses
    const proposalStatuses = ['PROPOSAL_IN_PROGRESS', 'PROPOSAL_SUBMITTED', 'PROPOSAL_ACCEPTED', 'CONTRACT_NEGOTIATION', 'CONTRACTED', 'CLOSED_WON'];
    const permissionGranted = proposalStatuses.includes(newStatus);
  
    // Format the granted timestamp as ISO string
    const grantedAt = updatedAt.toISOString();
  
    return {
      dealId,
      customerId,
      previousStatus,
      newStatus,
      permissionGranted,
      grantedAt
    };
  }
  return { updateDealStatus };
})();
export const updateDealStatus = __aivicBundle_17_updateDealStatus.updateDealStatus;
/* AIVIC_FUNCTION_BUNDLE_END owner=updateDealStatus */

/* AIVIC_FUNCTION_BUNDLE_START owner=checkCustomerPortalAccess exports=checkCustomerPortalAccess */
const __aivicBundle_18_checkCustomerPortalAccess = (() => {
  const checkCustomerPortalAccessStore = new Map<string, { hasAccess: boolean; reason: string }>();
  
   function checkCustomerPortalAccess(
    input: CustomerPortalAccessCheckInput
  ): CustomerPortalAccessCheckResult {
    const { customerId, dealId } = input;
  
    const cacheKey = `${customerId}:${dealId}`;
    const cached = checkCustomerPortalAccessStore.get(cacheKey);
  
    if (cached) {
      return cached;
    }
  
    const result: CustomerPortalAccessCheckResult = {
      hasAccess: false,
      reason: 'DEAL_NOT_IN_PROPOSAL_STATUS'
    };
  
    checkCustomerPortalAccessStore.set(cacheKey, result);
  
    return result;
  }
  return { checkCustomerPortalAccess };
})();
export const checkCustomerPortalAccess = __aivicBundle_18_checkCustomerPortalAccess.checkCustomerPortalAccess;
/* AIVIC_FUNCTION_BUNDLE_END owner=checkCustomerPortalAccess */

/* AIVIC_FUNCTION_BUNDLE_START owner=getAccessLog exports=getAccessLog,recordAccessLog */
const __aivicBundle_19_getAccessLog = (() => {
  const getAccessLogStore: Map<string, Array<{
    logId: string;
    dealId: string;
    customerId: string;
    logType: string;
    grantedStatus: string;
    grantedAt: string;
    grantedBy: string;
  }>> = new Map();
  
   function getAccessLog(input: AccessLogQueryInput): AccessLogQueryResult {
    const { dealId, customerId, logType } = input;
    
    const storeKey = `${dealId}:${customerId}:${logType}`;
    const logs = getAccessLogStore.get(storeKey) || [];
    
    return {
      recordCount: logs.length,
      logs: logs
    };
  }
  
   function recordAccessLog(
    dealId: string,
    customerId: string,
    logType: string,
    grantedStatus: string,
    grantedAt: Date,
    grantedBy: string
  ): void {
    const { randomUUID } = require('crypto');
    const storeKey = `${dealId}:${customerId}:${logType}`;
    
    const logEntry = {
      logId: randomUUID(),
      dealId,
      customerId,
      logType,
      grantedStatus,
      grantedAt: grantedAt.toISOString(),
      grantedBy
    };
    
    if (!getAccessLogStore.has(storeKey)) {
      getAccessLogStore.set(storeKey, []);
    }
    
    getAccessLogStore.get(storeKey)!.push(logEntry);
  }
  return { getAccessLog, recordAccessLog };
})();
export const getAccessLog = __aivicBundle_19_getAccessLog.getAccessLog;
export const recordAccessLog = __aivicBundle_19_getAccessLog.recordAccessLog;
/* AIVIC_FUNCTION_BUNDLE_END owner=getAccessLog */
