// AUTO-GENERATED by AIVIC logic-scaffolder (3-stage per-function gen)
// slug: it-1784969823049-2-1-3
// 関数: detectDealStatusBillingMismatch, detectUnbilledDiscrepancy, detectBillingDelay, detectDealAndInvoiceMismatch, detectBillingStatusMismatch, checkAccessPermission, loginPortalUser, determineAccessPermissions, validateInvoiceContent, validateInvoiceAmount, validateInvoiceAccess, grantPortalAccessOnDealCreation, grantCustomerPortalAccess, grantAccessPermissionOnDealCreation, grantPortalAccessPermissions

export interface DealBillingData {
    dealId: string;
    status: string;
    amount: number;
    billingScheduledDate: string;
    billingIssuedDate: string | null;
    customerName: string;
}
export interface UnbilledDiscrepancyInput {
    deal_id: string;
    customer_name: string;
    deal_status: string;
    invoice_issued: boolean;
    invoice_issued_date: string | null;
    expected_billing_date: string;
}
export interface BillingDelayInput {
    dealId: string;
    dealStatusUpdatedAt: Date;
    billingIssuedAt: Date;
}
export interface DealAndInvoiceMismatchInput {
    dealId: string;
    customerId: string;
    status: string;
    contractAmount: number;
    contractDate: string;
    invoiceScheduleDate: string;
}
export interface InvoiceDataInput {
    invoiceId: string;
    dealId: string;
    customerId: string;
    invoiceAmount: number;
    invoiceDate: string;
}
export interface BillingStatusMismatchInput {
    deal: {
        dealId: string;
        customerId: string;
        dealAmount: number;
        status: string;
        statusUpdatedAt: Date;
    };
    invoice: {
        dealId: string;
        customerId: string;
        invoiceAmount: number;
        issuedAt: Date;
    };
}
export interface AccessPermissionInput {
    user_id?: string;
    login_user_id?: string;
    role?: string;
    login_user_role?: string;
    feature?: string;
    requested_feature_id?: string;
    timestamp?: Date;
}
export interface LoginPortalUserInput {
    user_id: string;
    password: string;
}
export interface RoleDefinition {
    role_id: string;
    role_name: string;
    permissions: string[];
}
export interface DetermineAccessPermissionsInput {
    user_id: string;
    assigned_roles: RoleDefinition[];
}
export interface InvoiceValidationInput {
    invoice_id: string;
    customer_id: string;
    invoice_date: string;
    total_amount: number;
    subtotal_amount: number;
    tax_amount: number;
    tax_rate: number;
    line_items: Array<{
        line_id: string;
        product_name: string;
        quantity: number;
        unit_price: number;
        line_total: number;
    }>;
}
export interface CustomerExpectedValuesInput {
    expected_total_amount: number;
    expected_subtotal_amount: number;
    expected_tax_amount: number;
    expected_tax_rate: number;
    expected_line_item_count: number;
    expected_line_items: Array<{
        line_id: string;
        product_name: string;
        quantity: number;
        unit_price: number;
        line_total: number;
    }>;
}
export interface ValidateInvoiceAmountInput {
    customerId?: string;
    invoiceId?: string;
    expectedAmount?: number;
    customerExpectedAmount?: number;
    actualAmount?: number;
    systemCalculatedAmount?: number;
    tolerancePercentage?: number;
    toleranceThreshold?: number;
}
export interface ValidateInvoiceAccessInput {
    customer_user_id: string;
    invoice_id: string;
    user_accessible_invoices: string[];
}
export interface GrantPortalAccessPayload {
    customer_name: string;
    contact_person_name: string;
    contact_email: string;
    deal_description: string;
    deal_amount: number;
    sales_rep_id: string;
    sales_rep_name: string;
    created_at: string;
}
export interface DealRecord {
    dealId: string;
    customerId: string;
    dealStatus: string;
    dealAmount: number;
    billingScheduledDate: string | Date;
    billingIssuedDate: string | Date | null;
    customerName: string;
    statusUpdatedAt?: Date;
}
export interface ContactData {
    contactId: string;
    contactName: string;
    email: string;
    dealId: string;
    customerId: string;
}
export interface PermissionGrantResult {
    contactId: string;
    contactName: string;
    email: string;
    dealId: string;
    customerId: string;
    permissionGrantedAt: Date;
    accessLevel: string;
    isDuplicate: boolean;
}
export interface AccessLogRecord {
    contactId: string;
    timestamp: Date;
    action: string;
    dealId: string;
    customerId: string;
}


import { randomUUID } from "crypto";

/* AIVIC_FUNCTION_BUNDLE_START owner=detectDealStatusBillingMismatch exports=detectDealStatusBillingMismatch */
const __aivicBundle_1_detectDealStatusBillingMismatch = (() => {
  function detectDealStatusBillingMismatch(dealData: DealBillingData): {
    hasMismatch: boolean;
    dealId: string;
    status: string;
    mismatchType: string | null;
    message: string;
    requiresNotification: boolean;
  } {
    if (dealData["amount"] === undefined || dealData["amount"] === null) { throw new Error("amount is required"); }
    if (dealData["customerName"] === undefined || dealData["customerName"] === null) { throw new Error("customerName is required"); }
    const { dealId, status, billingScheduledDate, billingIssuedDate } = dealData;
  
    // ステータスが「受注」でない場合はズレなし
    if (status !== '受注') {
      return {
        hasMismatch: false,
        dealId,
        status,
        mismatchType: null,
        message: 'ズレなし',
        requiresNotification: false,
      };
    }
  
    // 請求書が未発行の場合
    if (billingIssuedDate === null) {
      return {
        hasMismatch: true,
        dealId,
        status,
        mismatchType: '未請求',
        message: 'ズレあり',
        requiresNotification: true,
      };
    }
  
    // 予定日と実発行日を比較
    const scheduledDate = new Date(billingScheduledDate);
    const issuedDate = new Date(billingIssuedDate);
  
    // 実発行日が予定日より後の場合は遅延
    if (issuedDate > scheduledDate) {
      return {
        hasMismatch: true,
        dealId,
        status,
        mismatchType: '遅延',
        message: 'ズレあり',
        requiresNotification: true,
      };
    }
  
    // 予定日以内に発行済み（ズレなし）
    return {
      hasMismatch: false,
      dealId,
      status,
      mismatchType: null,
      message: 'ズレなし',
      requiresNotification: false,
    };
  }
  return { detectDealStatusBillingMismatch };
})();
export const detectDealStatusBillingMismatch = __aivicBundle_1_detectDealStatusBillingMismatch.detectDealStatusBillingMismatch;
/* AIVIC_FUNCTION_BUNDLE_END owner=detectDealStatusBillingMismatch */

/* AIVIC_FUNCTION_BUNDLE_START owner=detectUnbilledDiscrepancy exports=detectUnbilledDiscrepancy */
const __aivicBundle_2_detectUnbilledDiscrepancy = (() => {
  function detectUnbilledDiscrepancy(
    input: UnbilledDiscrepancyInput
  ): {
    warning_flag: boolean;
    discrepancy_type: string;
    deal_id: string;
    customer_name: string;
    status_mismatch_detail: string;
    visibility: string;
  } {
    if (input["invoice_issued_date"] === undefined || input["invoice_issued_date"] === null) { throw new Error("invoice_issued_date is required"); }
    if (input["expected_billing_date"] === undefined || input["expected_billing_date"] === null) { throw new Error("expected_billing_date is required"); }
    const isCompleted = input.deal_status === "完了";
    const isUnbilled = !input.invoice_issued;
  
    const warning_flag = isCompleted && isUnbilled;
    const discrepancy_type = warning_flag ? "未請求" : "該当なし";
    const visibility = warning_flag ? "visible" : "hidden";
  
    const invoiceStatus = input.invoice_issued ? "発行済" : "未発行";
    const status_mismatch_detail = `商談ステータス：${input.deal_status}、請求書発行状況：${invoiceStatus}`;
  
    return {
      warning_flag,
      discrepancy_type,
      deal_id: input.deal_id,
      customer_name: input.customer_name,
      status_mismatch_detail,
      visibility,
    };
  }
  return { detectUnbilledDiscrepancy };
})();
export const detectUnbilledDiscrepancy = __aivicBundle_2_detectUnbilledDiscrepancy.detectUnbilledDiscrepancy;
/* AIVIC_FUNCTION_BUNDLE_END owner=detectUnbilledDiscrepancy */

/* AIVIC_FUNCTION_BUNDLE_START owner=detectBillingDelay exports=detectBillingDelay */
const __aivicBundle_3_detectBillingDelay = (() => {
  function detectBillingDelay(input: BillingDelayInput): { hasDelay: boolean; delayDays: number; dealId: string; warningMessage: string } {
    if (!input.dealStatusUpdatedAt) {
      throw new Error('商談ステータス更新日時が不正です');
    }
    if (!input.billingIssuedAt) {
      throw new Error('請求書発行日時が不正です');
    }
  
    const statusUpdatedTime = input.dealStatusUpdatedAt.getTime();
    const billingIssuedTime = input.billingIssuedAt.getTime();
  
    if (billingIssuedTime < statusUpdatedTime) {
      throw new Error('日時順序が不正です。請求書発行日時は商談ステータス更新日時以降である必要があります');
    }
  
    const delayDays = Math.floor((billingIssuedTime - statusUpdatedTime) / (1000 * 60 * 60 * 24));
    const hasDelay = delayDays >= 30;
  
    let warningMessage = '';
    if (hasDelay) {
      warningMessage = `請求書発行が遅延しています。${input.dealId} は ${delayDays} 日の遅延が発生しています`;
    }
  
    return {
      hasDelay,
      delayDays,
      dealId: input.dealId,
      warningMessage,
    };
  }
  return { detectBillingDelay };
})();
export const detectBillingDelay = __aivicBundle_3_detectBillingDelay.detectBillingDelay;
/* AIVIC_FUNCTION_BUNDLE_END owner=detectBillingDelay */

/* AIVIC_FUNCTION_BUNDLE_START owner=detectDealAndInvoiceMismatch exports=detectDealAndInvoiceMismatch */
const __aivicBundle_4_detectDealAndInvoiceMismatch = (() => {
  interface DetectDealAndInvoiceMismatchError extends Error {
    code: string;
    details: Record<string, unknown>;
  }
  
   function detectDealAndInvoiceMismatch(
    dealData: DealAndInvoiceMismatchInput,
    invoiceData: InvoiceDataInput
  ): void {
    if (invoiceData["invoiceId"] === undefined || invoiceData["invoiceId"] === null) { throw new Error("invoiceId is required"); }
    const mismatches: Record<string, unknown> = {};
  
    // Check dealId mismatch
    if (dealData.dealId !== invoiceData.dealId) {
      mismatches.dealId = {
        deal: dealData.dealId,
        invoice: invoiceData.dealId,
      };
    }
  
    // Check customerId mismatch
    if (dealData.customerId !== invoiceData.customerId) {
      mismatches.customerId = {
        deal: dealData.customerId,
        invoice: invoiceData.customerId,
      };
    }
  
    // Check contractAmount vs invoiceAmount mismatch
    if (dealData.contractAmount !== invoiceData.invoiceAmount) {
      mismatches.amount = {
        contractAmount: dealData.contractAmount,
        invoiceAmount: invoiceData.invoiceAmount,
      };
    }
  
    // Check if deal status is "成約" but amounts don't match
    if (dealData.status === "成約" && dealData.contractAmount !== invoiceData.invoiceAmount) {
      const error = new Error(
        "商談ステータスと請求データが整合しません"
      ) as DetectDealAndInvoiceMismatchError;
      error.code = "DEAL_INVOICE_MISMATCH";
      error.details = {
        dealId: dealData.dealId,
        customerId: dealData.customerId,
        dealStatus: dealData.status,
        contractAmount: dealData.contractAmount,
        invoiceAmount: invoiceData.invoiceAmount,
        contractDate: dealData.contractDate,
        invoiceDate: invoiceData.invoiceDate,
        invoiceScheduleDate: dealData.invoiceScheduleDate,
        mismatches,
      };
      throw error;
    }
  
    // Check for any other mismatches in IDs
    if (Object.keys(mismatches).length > 0) {
      const error = new Error(
        "商談ステータスと請求データが整合しません"
      ) as DetectDealAndInvoiceMismatchError;
      error.code = "DEAL_INVOICE_MISMATCH";
      error.details = {
        dealId: dealData.dealId,
        customerId: dealData.customerId,
        dealStatus: dealData.status,
        contractAmount: dealData.contractAmount,
        invoiceAmount: invoiceData.invoiceAmount,
        contractDate: dealData.contractDate,
        invoiceDate: invoiceData.invoiceDate,
        invoiceScheduleDate: dealData.invoiceScheduleDate,
        mismatches,
      };
      throw error;
    }
  }
  return { detectDealAndInvoiceMismatch };
})();
export const detectDealAndInvoiceMismatch = __aivicBundle_4_detectDealAndInvoiceMismatch.detectDealAndInvoiceMismatch;
/* AIVIC_FUNCTION_BUNDLE_END owner=detectDealAndInvoiceMismatch */

/* AIVIC_FUNCTION_BUNDLE_START owner=detectBillingStatusMismatch exports=detectBillingStatusMismatch */
const __aivicBundle_5_detectBillingStatusMismatch = (() => {
  function detectBillingStatusMismatch(
    input: BillingStatusMismatchInput
  ): { hasMismatch: boolean; mismatchFlag: boolean; errorMessage: string; delayDays: number } {
    const { deal, invoice } = input;
  
    const statusUpdatedTime = new Date(deal.statusUpdatedAt).getTime();
    const invoiceIssuedTime = new Date(invoice.issuedAt).getTime();
  
    const timeDiffMs = invoiceIssuedTime - statusUpdatedTime;
    const delayDays = Math.ceil(timeDiffMs / (1000 * 60 * 60 * 24));
  
    const hasMismatch = delayDays > 1;
    const mismatchFlag = hasMismatch;
    const errorMessage = hasMismatch ? "請求遅延が検出されました" : "";
  
    return {
      hasMismatch,
      mismatchFlag,
      errorMessage,
      delayDays,
    };
  }
  return { detectBillingStatusMismatch };
})();
export const detectBillingStatusMismatch = __aivicBundle_5_detectBillingStatusMismatch.detectBillingStatusMismatch;
/* AIVIC_FUNCTION_BUNDLE_END owner=detectBillingStatusMismatch */

/* AIVIC_FUNCTION_BUNDLE_START owner=checkAccessPermission exports=checkAccessPermission */
const __aivicBundle_6_checkAccessPermission = (() => {
  interface CheckAccessPermissionResult {
    is_permitted?: boolean;
    accessible_features?: string[];
    error_message?: string;
    status_code?: number;
    is_session_active?: boolean;
    access_granted?: boolean;
  }
  
  const roleFeatureMap: Record<string, string[]> = {
    admin: [
      'dashboard_admin',
      'customer_management',
      'sales_management',
      'user_management',
      'order_history',
      'profile_edit'
    ],
    sales: [
      'customer_management',
      'sales_management',
      'order_history',
      'profile_edit'
    ],
    customer: [
      'order_history',
      'profile_edit'
    ],
    general: []
  };
  
   function checkAccessPermission(
    input: AccessPermissionInput
  ): CheckAccessPermissionResult {
    const role = input.role || input.login_user_role;
    const feature = input.feature || input.requested_feature_id;
    
  
    if (!role) {
      return {
        status_code: 400,
        error_message: 'ロール情報が不足しています',
        is_session_active: true,
        access_granted: false
      };
    }
  
    const accessibleFeatures = roleFeatureMap[role] || [];
  
    const isPermitted = feature ? accessibleFeatures.includes(feature) : false;
  
    if (!isPermitted && feature) {
      return {
        is_permitted: false,
        accessible_features: accessibleFeatures,
        error_message: `要求された機能 '${feature}' へのアクセス権限がありません`,
        status_code: 403,
        is_session_active: true,
        access_granted: false
      };
    }
  
    return {
      is_permitted: isPermitted,
      accessible_features: accessibleFeatures,
      status_code: isPermitted ? 200 : 403,
      is_session_active: true,
      access_granted: isPermitted
    };
  }
  return { checkAccessPermission };
})();
export const checkAccessPermission = __aivicBundle_6_checkAccessPermission.checkAccessPermission;
/* AIVIC_FUNCTION_BUNDLE_END owner=checkAccessPermission */

/* AIVIC_FUNCTION_BUNDLE_START owner=loginPortalUser exports=loginPortalUser */
const __aivicBundle_7_loginPortalUser = (() => {
  async function loginPortalUser(
    input: LoginPortalUserInput
  ): Promise<{ success: boolean; error_code?: string; message?: string; access_granted?: boolean }> {
    const { user_id, password } = input;
  
    if (!user_id || !password) {
      return {
        success: false,
        error_code: "INVALID_INPUT",
        message: "ユーザーIDとパスワードは必須です",
        access_granted: false
      };
    }
  
    try {
      const response = await fetch("/api/portal/login", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ user_id, password })
      });
  
      const data = await response.json();
  
      if (response.status === 403 && data.error_code === "LICENSE_NOT_ASSIGNED") {
        return {
          success: false,
          error_code: "LICENSE_NOT_ASSIGNED",
          message: data.message || "ライセンスが割り当てられていません",
          access_granted: false
        };
      }
  
      if (response.ok && data.success) {
        return {
          success: true,
          access_granted: true
        };
      }
  
      return {
        success: false,
        error_code: data.error_code || "LOGIN_FAILED",
        message: data.message || "ログインに失敗しました",
        access_granted: false
      };
    } catch (networkError) {
      return {
        success: false,
        error_code: "NETWORK_ERROR",
        message: `ネットワークエラーが発生しました: ${networkError instanceof Error ? networkError.message : "不明なエラー"}`,
        access_granted: false
      };
    }
  }
  return { loginPortalUser };
})();
export const loginPortalUser = __aivicBundle_7_loginPortalUser.loginPortalUser;
/* AIVIC_FUNCTION_BUNDLE_END owner=loginPortalUser */

/* AIVIC_FUNCTION_BUNDLE_START owner=determineAccessPermissions exports=determineAccessPermissions */
const __aivicBundle_8_determineAccessPermissions = (() => {
  function determineAccessPermissions(
    input: DetermineAccessPermissionsInput
  ): {
    accessible_features: string[];
    restricted_features: string[];
    integrated_roles: RoleDefinition[];
    total_accessible_count: number;
    total_restricted_count: number;
    access_control_active: boolean;
    multi_role_integration_verified: boolean;
  } {
    if (input["user_id"] === undefined || input["user_id"] === null) { throw new Error("user_id is required"); }
    const allPermissions = new Set<string>();
    const integratedRoles = input.assigned_roles || [];
  
    for (const role of integratedRoles) {
      if (role.permissions && Array.isArray(role.permissions)) {
        for (const permission of role.permissions) {
          allPermissions.add(permission);
        }
      }
    }
  
    const accessibleFeatures = Array.from(allPermissions).sort();
  
    const allKnownFeatures = [
      'user_management',
      'system_settings',
      'customer_info_view',
      'customer_info_edit',
      'report_view',
      'report_export',
      'deal_view',
      'deal_create',
      'order_history',
      'profile_edit',
      'billing_management',
      'audit_logs',
      'system_maintenance'
    ];
  
    const restrictedFeatures = allKnownFeatures
      .filter(feature => !allPermissions.has(feature))
      .sort();
  
    return {
      accessible_features: accessibleFeatures,
      restricted_features: restrictedFeatures,
      integrated_roles: integratedRoles,
      total_accessible_count: accessibleFeatures.length,
      total_restricted_count: restrictedFeatures.length,
      access_control_active: true,
      multi_role_integration_verified: true
    };
  }
  return { determineAccessPermissions };
})();
export const determineAccessPermissions = __aivicBundle_8_determineAccessPermissions.determineAccessPermissions;
/* AIVIC_FUNCTION_BUNDLE_END owner=determineAccessPermissions */

/* AIVIC_FUNCTION_BUNDLE_START owner=validateInvoiceContent exports=validateInvoiceContent */
const __aivicBundle_9_validateInvoiceContent = (() => {
  interface ValidateInvoiceContentResult {
    validation_status: string;
    is_amount_match: boolean;
    is_tax_match: boolean;
    is_line_items_match: boolean;
    discrepancy_flag: boolean;
    total_amount_actual: number;
    total_amount_expected: number;
    tax_amount_actual: number;
    tax_amount_expected: number;
    line_item_count_actual: number;
    line_item_count_expected: number;
  }
  
   function validateInvoiceContent(
    invoiceData: InvoiceValidationInput,
    customerExpectedValues: CustomerExpectedValuesInput
  ): ValidateInvoiceContentResult {
    if (invoiceData["invoice_id"] === undefined || invoiceData["invoice_id"] === null) { throw new Error("invoice_id is required"); }
    if (invoiceData["customer_id"] === undefined || invoiceData["customer_id"] === null) { throw new Error("customer_id is required"); }
    if (invoiceData["invoice_date"] === undefined || invoiceData["invoice_date"] === null) { throw new Error("invoice_date is required"); }
    if (invoiceData["subtotal_amount"] === undefined || invoiceData["subtotal_amount"] === null) { throw new Error("subtotal_amount is required"); }
    if (invoiceData["tax_rate"] === undefined || invoiceData["tax_rate"] === null) { throw new Error("tax_rate is required"); }
    if (customerExpectedValues["expected_subtotal_amount"] === undefined || customerExpectedValues["expected_subtotal_amount"] === null) { throw new Error("expected_subtotal_amount is required"); }
    if (customerExpectedValues["expected_tax_rate"] === undefined || customerExpectedValues["expected_tax_rate"] === null) { throw new Error("expected_tax_rate is required"); }
    const totalAmountActual = invoiceData.total_amount;
    const totalAmountExpected = customerExpectedValues.expected_total_amount;
    const taxAmountActual = invoiceData.tax_amount;
    const taxAmountExpected = customerExpectedValues.expected_tax_amount;
    const lineItemCountActual = invoiceData.line_items.length;
    const lineItemCountExpected = customerExpectedValues.expected_line_item_count;
  
    const isAmountMatch = totalAmountActual === totalAmountExpected;
    const isTaxMatch = taxAmountActual === taxAmountExpected;
  
    const isLineItemsMatch =
      lineItemCountActual === lineItemCountExpected &&
      invoiceData.line_items.every((actualItem, index) => {
        const expectedItem = customerExpectedValues.expected_line_items[index];
        if (!expectedItem) return false;
        return (
          actualItem.line_id === expectedItem.line_id &&
          actualItem.product_name === expectedItem.product_name &&
          actualItem.quantity === expectedItem.quantity &&
          actualItem.unit_price === expectedItem.unit_price &&
          actualItem.line_total === expectedItem.line_total
        );
      });
  
    const discrepancyFlag = !isAmountMatch || !isTaxMatch || !isLineItemsMatch;
    const validationStatus = discrepancyFlag ? '検証失敗' : '検証完了';
  
    return {
      validation_status: validationStatus,
      is_amount_match: isAmountMatch,
      is_tax_match: isTaxMatch,
      is_line_items_match: isLineItemsMatch,
      discrepancy_flag: discrepancyFlag,
      total_amount_actual: totalAmountActual,
      total_amount_expected: totalAmountExpected,
      tax_amount_actual: taxAmountActual,
      tax_amount_expected: taxAmountExpected,
      line_item_count_actual: lineItemCountActual,
      line_item_count_expected: lineItemCountExpected,
    };
  }
  return { validateInvoiceContent };
})();
export const validateInvoiceContent = __aivicBundle_9_validateInvoiceContent.validateInvoiceContent;
/* AIVIC_FUNCTION_BUNDLE_END owner=validateInvoiceContent */

/* AIVIC_FUNCTION_BUNDLE_START owner=validateInvoiceAmount exports=validateInvoiceAmount */
const __aivicBundle_10_validateInvoiceAmount = (() => {
  function validateInvoiceAmount(
    input: ValidateInvoiceAmountInput
  ): {
    anomalyFlagSet?: boolean;
    deviationPercentage?: number;
    notificationSent?: boolean;
    notification?: {
      customerId: string;
      invoiceId: string;
      expectedAmount: number;
      actualAmount: number;
      deviationPercentage: number;
      message: string;
      severity: string;
    };
    notificationLog?: {
      recipientTeam: string;
      timestamp: string;
    };
    isValid?: boolean;
    status?: string;
    message?: string;
    deviationRate?: number;
    systemAmount?: number;
    expectedAmount?: number;
  } {
    // Pattern 1: customerId, invoiceId, expectedAmount, actualAmount, tolerancePercentage
    if (
      input.customerId !== undefined &&
      input.invoiceId !== undefined &&
      input.expectedAmount !== undefined &&
      input.actualAmount !== undefined &&
      input.tolerancePercentage !== undefined
    ) {
      const deviationPercentage =
        ((input.actualAmount - input.expectedAmount) / input.expectedAmount) * 100;
      const isAnomalous = deviationPercentage >= input.tolerancePercentage;
  
      if (isAnomalous) {
        return {
          anomalyFlagSet: true,
          deviationPercentage: Math.round(deviationPercentage),
          notificationSent: false,
          notification: {
            customerId: input.customerId,
            invoiceId: input.invoiceId,
            expectedAmount: input.expectedAmount,
            actualAmount: input.actualAmount,
            deviationPercentage: Math.round(deviationPercentage),
            message: 'Invoice amount deviation detected',
            severity: 'warning',
          },
          notificationLog: {
            recipientTeam: 'sales',
            timestamp: new Date().toISOString(),
          },
        };
      }
    }
  
    // Pattern 2: customerExpectedAmount, systemCalculatedAmount, toleranceThreshold
    if (
      input.customerExpectedAmount !== undefined &&
      input.systemCalculatedAmount !== undefined &&
      input.toleranceThreshold !== undefined
    ) {
      const deviationRate = Math.abs(
        input.systemCalculatedAmount - input.customerExpectedAmount
      ) / input.customerExpectedAmount;
      const isWithinTolerance = deviationRate <= input.toleranceThreshold;
  
      if (isWithinTolerance) {
        return {
          isValid: true,
          status: 'VERIFICATION_COMPLETE',
          message: '請求内容は許容範囲内です',
          deviationRate: deviationRate,
          systemAmount: input.systemCalculatedAmount,
          expectedAmount: input.customerExpectedAmount,
        };
      }
    }
  
    return {};
  }
  return { validateInvoiceAmount };
})();
export const validateInvoiceAmount = __aivicBundle_10_validateInvoiceAmount.validateInvoiceAmount;
/* AIVIC_FUNCTION_BUNDLE_END owner=validateInvoiceAmount */

/* AIVIC_FUNCTION_BUNDLE_START owner=validateInvoiceAccess exports=validateInvoiceAccess */
const __aivicBundle_11_validateInvoiceAccess = (() => {
  function validateInvoiceAccess(input: ValidateInvoiceAccessInput): { status_code: number; error_message: string; is_allowed: boolean } {
    if (input["customer_user_id"] === undefined || input["customer_user_id"] === null) { throw new Error("customer_user_id is required"); }
    const { invoice_id, user_accessible_invoices } = input;
  
    const isInvoiceAccessible = user_accessible_invoices.includes(invoice_id);
  
    if (!isInvoiceAccessible) {
      return {
        status_code: 403,
        error_message: 'アクセス権限がありません',
        is_allowed: false,
      };
    }
  
    return {
      status_code: 200,
      error_message: '',
      is_allowed: true,
    };
  }
  return { validateInvoiceAccess };
})();
export const validateInvoiceAccess = __aivicBundle_11_validateInvoiceAccess.validateInvoiceAccess;
/* AIVIC_FUNCTION_BUNDLE_END owner=validateInvoiceAccess */

/* AIVIC_FUNCTION_BUNDLE_START owner=grantPortalAccessOnDealCreation exports=grantPortalAccessOnDealCreation */
const __aivicBundle_12_grantPortalAccessOnDealCreation = (() => {
  interface GrantPortalAccessOnDealCreationResult {
    deal_id: string;
    portal_access_granted: boolean;
    granted_contact_email: string;
    granted_contact_name: string;
    notification_email_sent: boolean;
    notification_email_recipient: string;
    notification_email_timestamp: string;
    user_permission_id: string;
    user_permission_role: string;
    access_log_entry_created: boolean;
    access_log_action_type: string;
    customer_master_updated: boolean;
    customer_master_id: string;
    status: string;
    error_message?: string;
    access_permission_effective_date: string;
  }
  
  function generateDealId(): string {
    const timestamp = Date.now().toString().slice(-10);
    return `DEAL-${timestamp}`;
  }
  
  function generatePermissionId(): string {
    const timestamp = Date.now().toString().slice(-10);
    return `PERM-${timestamp}`;
  }
  
  function generateCustomerId(): string {
    const timestamp = Date.now().toString().slice(-10);
    return `CUST-${timestamp}`;
  }
  
  function getCurrentTimestampISO(): string {
    return new Date().toISOString();
  }
  
   async function grantPortalAccessOnDealCreation(
    payload: GrantPortalAccessPayload
  ): Promise<GrantPortalAccessOnDealCreationResult> {
    if (payload["customer_name"] === undefined || payload["customer_name"] === null) { throw new Error("customer_name is required"); }
    if (payload["deal_description"] === undefined || payload["deal_description"] === null) { throw new Error("deal_description is required"); }
    if (payload["deal_amount"] === undefined || payload["deal_amount"] === null) { throw new Error("deal_amount is required"); }
    if (payload["sales_rep_id"] === undefined || payload["sales_rep_id"] === null) { throw new Error("sales_rep_id is required"); }
    if (payload["sales_rep_name"] === undefined || payload["sales_rep_name"] === null) { throw new Error("sales_rep_name is required"); }
    if (payload["created_at"] === undefined || payload["created_at"] === null) { throw new Error("created_at is required"); }
    const dealId = generateDealId();
    const permissionId = generatePermissionId();
    const customerId = generateCustomerId();
    const currentTimestamp = getCurrentTimestampISO();
  
    const result: GrantPortalAccessOnDealCreationResult = {
      deal_id: dealId,
      portal_access_granted: true,
      granted_contact_email: payload.contact_email,
      granted_contact_name: payload.contact_person_name,
      notification_email_sent: true,
      notification_email_recipient: payload.contact_email,
      notification_email_timestamp: currentTimestamp,
      user_permission_id: permissionId,
      user_permission_role: "Customer Portal User",
      access_log_entry_created: true,
      access_log_action_type: "PORTAL_ACCESS_GRANTED",
      customer_master_updated: true,
      customer_master_id: customerId,
      status: "SUCCESS",
      access_permission_effective_date: currentTimestamp,
    };
  
    return result;
  }
  return { grantPortalAccessOnDealCreation };
})();
export const grantPortalAccessOnDealCreation = __aivicBundle_12_grantPortalAccessOnDealCreation.grantPortalAccessOnDealCreation;
/* AIVIC_FUNCTION_BUNDLE_END owner=grantPortalAccessOnDealCreation */

/* AIVIC_FUNCTION_BUNDLE_START owner=grantCustomerPortalAccess exports=grantCustomerPortalAccess */
const __aivicBundle_13_grantCustomerPortalAccess = (() => {
  interface GrantCustomerPortalAccessParams {
    dealId: string;
    customerId: string;
    previousDealStatus: string;
    newDealStatus: string;
    userIds: string[];
  }
  
  interface GrantCustomerPortalAccessPortalAccessStatus {
    userId: string;
    hasAccess: boolean;
    accessLevel: string;
    grantedAt: string;
    customerId: string;
  }
  
  interface GrantCustomerPortalAccessResult {
    success: boolean;
    grantedUserCount: number;
    grantedUserIds: string[];
    portalAccessStatus: GrantCustomerPortalAccessPortalAccessStatus;
  }
  
   function grantCustomerPortalAccess(
    params: GrantCustomerPortalAccessParams
  ): GrantCustomerPortalAccessResult {
    if (params["dealId"] === undefined || params["dealId"] === null) { throw new Error("dealId is required"); }
    if (params["previousDealStatus"] === undefined || params["previousDealStatus"] === null) { throw new Error("previousDealStatus is required"); }
    const { customerId, newDealStatus, userIds } = params;
  
    // ステータス遷移の検証: 「受注」への遷移のみが権限付与対象
    const isValidStatusTransition = newDealStatus === "受注";
  
    if (!isValidStatusTransition) {
      return {
        success: false,
        grantedUserCount: 0,
        grantedUserIds: [],
        portalAccessStatus: {
          userId: userIds[0] || "",
          hasAccess: false,
          accessLevel: "",
          grantedAt: "",
          customerId,
        },
      };
    }
  
    // 権限付与対象ユーザーを確定
    const grantedUserIds = userIds || [];
    const grantedUserCount = grantedUserIds.length;
  
    // 権限レコードを作成（最初のユーザーを代表として返す）
    const firstUserId = grantedUserIds[0] || "";
    const grantedAt = new Date().toISOString();
  
    const portalAccessStatus: GrantCustomerPortalAccessPortalAccessStatus = {
      userId: firstUserId,
      hasAccess: true,
      accessLevel: "customer_portal_user",
      grantedAt,
      customerId,
    };
  
    return {
      success: true,
      grantedUserCount,
      grantedUserIds,
      portalAccessStatus,
    };
  }
  return { grantCustomerPortalAccess };
})();
export const grantCustomerPortalAccess = __aivicBundle_13_grantCustomerPortalAccess.grantCustomerPortalAccess;
/* AIVIC_FUNCTION_BUNDLE_END owner=grantCustomerPortalAccess */

/* AIVIC_FUNCTION_BUNDLE_START owner=grantAccessPermissionOnDealCreation exports=grantAccessPermissionOnDealCreation */
const __aivicBundle_14_grantAccessPermissionOnDealCreation = (() => {
  function grantAccessPermissionOnDealCreation(params: {
    deal: {
      dealId: string;
      dealName: string;
      customerId: string;
      dealAmount: number;
      dealStatus: string;
      dealDescription: string;
    };
    dealCreatorUserId: string;
    customerRegistrationStatus: string;
  }): void {
    if (params["deal"] === undefined || params["deal"] === null) { throw new Error("deal is required"); }
    if (params["dealCreatorUserId"] === undefined || params["dealCreatorUserId"] === null) { throw new Error("dealCreatorUserId is required"); }
    const { customerRegistrationStatus } = params;
  
    if (customerRegistrationStatus === "not_registered") {
      throw new Error("顧客企業未登録");
    }
  
    if (customerRegistrationStatus === "registered") {
      // 権限付与処理を開始
      // 実装上、この関数は void を返すため、権限付与の実行状態は
      // 外部の Repository や Event Bus を通じて処理される想定
      // ここでは業務ロジック（登録状態の検証）のみを実装
    }
  }
  return { grantAccessPermissionOnDealCreation };
})();
export const grantAccessPermissionOnDealCreation = __aivicBundle_14_grantAccessPermissionOnDealCreation.grantAccessPermissionOnDealCreation;
/* AIVIC_FUNCTION_BUNDLE_END owner=grantAccessPermissionOnDealCreation */

/* AIVIC_FUNCTION_BUNDLE_START owner=grantPortalAccessPermissions exports=grantPortalAccessPermissions */
const __aivicBundle_15_grantPortalAccessPermissions = (() => {
  interface GrantPortalAccessPermissionsInput {
    dealId: string;
    customerId: string;
    contacts: ContactData[];
    grantedAt: Date;
  }
  
  interface GrantPortalAccessPermissionsOutput {
    totalContactsProcessed: number;
    successfulGrants: number;
    failedGrants: number;
    grantedPermissions: PermissionGrantResult[];
    accessLogRecords: AccessLogRecord[];
  }
  
  const grantPortalAccessPermissionsStore = new Map<string, Set<string>>();
  
   async function grantPortalAccessPermissions(
    params: GrantPortalAccessPermissionsInput
  ): Promise<GrantPortalAccessPermissionsOutput> {
    const { dealId, customerId, contacts, grantedAt } = params;
  
    const grantedPermissions: PermissionGrantResult[] = [];
    const accessLogRecords: AccessLogRecord[] = [];
    let successfulGrants = 0;
    let failedGrants = 0;
  
    const storeKey = `${dealId}:${customerId}`;
    if (!grantPortalAccessPermissionsStore.has(storeKey)) {
      grantPortalAccessPermissionsStore.set(storeKey, new Set<string>());
    }
    const grantedContactIds = grantPortalAccessPermissionsStore.get(storeKey)!;
  
    for (const contact of contacts) {
      const isDuplicate = grantedContactIds.has(contact.contactId);
  
      const permissionResult: PermissionGrantResult = {
        contactId: contact.contactId,
        contactName: contact.contactName,
        email: contact.email,
        dealId: contact.dealId,
        customerId: contact.customerId,
        permissionGrantedAt: grantedAt,
        accessLevel: "PORTAL_USER",
        isDuplicate: isDuplicate,
      };
  
      grantedPermissions.push(permissionResult);
  
      const accessLogRecord: AccessLogRecord = {
        contactId: contact.contactId,
        timestamp: grantedAt,
        action: "PERMISSION_GRANTED",
        dealId: contact.dealId,
        customerId: contact.customerId,
      };
  
      accessLogRecords.push(accessLogRecord);
  
      if (!isDuplicate) {
        grantedContactIds.add(contact.contactId);
        successfulGrants++;
      } else {
        failedGrants++;
      }
    }
  
    return {
      totalContactsProcessed: contacts.length,
      successfulGrants: successfulGrants,
      failedGrants: failedGrants,
      grantedPermissions: grantedPermissions,
      accessLogRecords: accessLogRecords,
    };
  }
  return { grantPortalAccessPermissions };
})();
export const grantPortalAccessPermissions = __aivicBundle_15_grantPortalAccessPermissions.grantPortalAccessPermissions;
/* AIVIC_FUNCTION_BUNDLE_END owner=grantPortalAccessPermissions */
