// AUTO-GENERATED by AIVIC logic-scaffolder (3-stage per-function gen)
// slug: it-1-1
// 関数: validateDocumentGeneration, validateCustomerInfoAndGenerateDocuments, validateDealAmount, generateEstimateOrderInvoice, verifyGeneratedDocuments, validateAndGenerateDocuments, validateDocumentAmountAndLineItems, validateDocumentAmount, validateDocumentDetails, validateDocumentLines, generateQuotationOrderInvoice, generateEstimate, generateOrder, generateInvoice, generateInvoiceFromUnbilledDeal, validateInvoiceFormat, generateInvoiceFromDeal, determineInvoicingTiming, determineBillingExecutionTiming, extractDealData, extractBillingTargetData, validateQuotationData, validateBillingTargetData, validateBillingDataReasonableness, calculateTotalCost, generateLicenseCostComparisonTable, calculateInitialConstructionCost, calculateLicenseCostComparison

export interface DealRecord {
  [key: string]: any;
}
export interface ValidationResult {
    isValid: boolean;
    validationStatus: string;
    errors: string[];
    warnings: string[];
    canGenerateDocuments?: boolean;
}
export interface DocumentSet {
    quotation: any;
    order: any;
    invoice: any;
}
export interface LineItem {
  [key: string]: any;
}
export interface GeneratedDocuments {
    quotation: {
        documentType: string;
        customerName: string;
        customerAddress?: string;
        customerPhone?: string;
        customerEmail?: string;
        subtotal: number;
        tax: number;
        total: number;
        items: Array<{
            itemName: string;
            quantity: number;
            unitPrice: number;
            subtotal: number;
        }>;
        dealId: string;
    };
    order: {
        documentType: string;
        customerName: string;
        customerAddress?: string;
        customerPhone?: string;
        customerEmail?: string;
        subtotal: number;
        tax: number;
        total: number;
        items: Array<{
            itemName: string;
            quantity: number;
            unitPrice: number;
            subtotal: number;
        }>;
        dealId: string;
    };
    invoice: {
        documentType: string;
        customerName: string;
        customerAddress?: string;
        customerPhone?: string;
        customerEmail?: string;
        subtotal: number;
        tax: number;
        total: number;
        items: Array<{
            itemName: string;
            quantity: number;
            unitPrice: number;
            subtotal: number;
        }>;
        dealId: string;
    };
}
export interface InvoiceLineItem {
    lineId: string | number;
    productName: string;
    quantity: number;
    unitPrice: number;
    subtotal?: number;
    taxAmount?: number;
    total?: number;
    taxRate?: number;
    lineOrder?: number;
}
export interface BillingExecutionResult {
  [key: string]: any;
}
export interface ExtractionResult {
  [key: string]: any;
}
export interface ValidationCheckResult {
  [key: string]: any;
}
export interface CostComparisonInput {
    salesforceMonthlyFee: number;
    userCount: number;
    initialConstructionCost: number;
    annualMaintenanceCost: number;
}
export interface FiscalYearCost {
    year: number;
    annualLicenseCost: number;
    annualOperationCost: number;
}
export interface ComparisonTableRow {
    year: number;
    annualLicenseCost: number;
    annualOperationCost: number;
    yearlyTotalCost: number;
    cumulativeLicenseCost: number;
    cumulativeOperationCost: number;
    cumulativeTotalCost: number;
}
export interface LicenseCostComparisonResult {
    comparisonTable: ComparisonTableRow[];
    grandTotalLicenseCost: number;
    grandTotalOperationCost: number;
    grandTotalCost: number;
    averageAnnualCost: number;
}
export interface InitialConstructionCostInput {
    developmentScale: string;
    developmentDays: number;
    teamSize: number;
    initialConstructionCost: number;
}
export interface LicenseCostComparisonInput {
    salesforceLicenseCost: number;
    initialConstructionCost: number;
    annualMaintenanceCost: number | null;
}
export interface LicenseCostComparisonOutput {
    comparisonSkipped: boolean;
    warningMessage: string | null;
    comparisonResult: {
        totalSalesforceThreeYearCost: number;
        totalDevelopmentThreeYearCost: number;
        costSavings: number;
    } | null;
    hasError: boolean;
}


import { randomUUID } from "crypto";

/* AIVIC_FUNCTION_BUNDLE_START owner=validateDocumentGeneration exports=validateDocumentGeneration */
const __aivicBundle_1_validateDocumentGeneration = (() => {
  function validateDocumentGeneration(dealData: any): ValidationResult {
    const errors: string[] = [];
    const warnings: string[] = [];
  
    // Validate dealId
    if (!dealData.dealId || typeof dealData.dealId !== "string" || dealData.dealId.trim() === "") {
      errors.push("商談IDが未入力です");
    }
  
    // Validate customer info
    const customerInfo = dealData.customerInfo;
    if (!customerInfo) {
      errors.push("顧客情報が未入力です");
    } else {
      if (!customerInfo.customerId || typeof customerInfo.customerId !== "string" || customerInfo.customerId.trim() === "") {
        errors.push("顧客IDが未入力です");
      }
      if (!customerInfo.customerName || typeof customerInfo.customerName !== "string" || customerInfo.customerName.trim() === "") {
        errors.push("顧客名が未入力です");
      }
      if (!customerInfo.address || typeof customerInfo.address !== "string" || customerInfo.address.trim() === "") {
        errors.push("住所が未入力です");
      }
      if (!customerInfo.phoneNumber || typeof customerInfo.phoneNumber !== "string" || customerInfo.phoneNumber.trim() === "") {
        errors.push("電話番号が未入力です");
      }
      if (!customerInfo.emailAddress || typeof customerInfo.emailAddress !== "string" || customerInfo.emailAddress.trim() === "") {
        errors.push("メールアドレスが未入力です");
      }
    }
  
    // Validate dealAmount
    if (dealData.dealAmount === undefined || dealData.dealAmount === null) {
      errors.push("商談金額が未入力です");
    } else if (typeof dealData.dealAmount !== "number" || dealData.dealAmount < 0) {
      errors.push("商談金額が不正です");
    }
  
    // Validate lineItems
    if (!dealData.lineItems || !Array.isArray(dealData.lineItems)) {
      errors.push("明細行が1行以上必要です");
    } else if (dealData.lineItems.length === 0) {
      errors.push("明細行が1行以上必要です");
    } else {
      for (let i = 0; i < dealData.lineItems.length; i++) {
        const item = dealData.lineItems[i];
        if (!item.productName || typeof item.productName !== "string" || item.productName.trim() === "") {
          errors.push(`明細行${i + 1}の商品名が未入力です`);
        }
        if (item.quantity === undefined || item.quantity === null || typeof item.quantity !== "number" || item.quantity <= 0) {
          errors.push(`明細行${i + 1}の数量が不正です`);
        }
        if (item.unitPrice === undefined || item.unitPrice === null || typeof item.unitPrice !== "number" || item.unitPrice < 0) {
          errors.push(`明細行${i + 1}の単価が不正です`);
        }
      }
    }
  
    const isValid = errors.length === 0;
    const validationStatus = isValid ? "OK" : "NG";
    const canGenerateDocuments = isValid;
  
    return {
      isValid,
      validationStatus,
      errors,
      warnings,
      canGenerateDocuments,
    };
  }
  return { validateDocumentGeneration };
})();
export const validateDocumentGeneration = __aivicBundle_1_validateDocumentGeneration.validateDocumentGeneration;
/* AIVIC_FUNCTION_BUNDLE_END owner=validateDocumentGeneration */

/* AIVIC_FUNCTION_BUNDLE_START owner=validateCustomerInfoAndGenerateDocuments exports=validateCustomerInfoAndGenerateDocuments */
const __aivicBundle_2_validateCustomerInfoAndGenerateDocuments = (() => {
  function validateCustomerInfoAndGenerateDocuments(
    dealId: string,
    customerInfo: {
      customer_name: string;
      address: string;
      phone_number: string;
      email_address: string;
    }
  ): {
    success: boolean;
    deal_id: string;
    generated_documents?: {
      quotation: any;
      order: any;
      invoice: any;
    };
  } {
    if (!customerInfo.customer_name || customerInfo.customer_name.trim() === '') {
      throw new Error('顧客名が入力されていません');
    }
  
    if (!customerInfo.address || customerInfo.address.trim() === '') {
      throw new Error('住所が入力されていません');
    }
  
    if (!customerInfo.phone_number || customerInfo.phone_number.trim() === '') {
      throw new Error('電話番号が入力されていません');
    }
  
    if (!customerInfo.email_address || customerInfo.email_address.trim() === '') {
      throw new Error('メールアドレスが入力されていません');
    }
  
    const baseDocument = {
      customerName: customerInfo.customer_name,
      customerAddress: customerInfo.address,
      customerPhone: customerInfo.phone_number,
      customerEmail: customerInfo.email_address,
      dealId: dealId,
    };
  
    const quotation = {
      documentType: 'quotation',
      ...baseDocument,
    };
  
    const order = {
      documentType: 'order',
      ...baseDocument,
    };
  
    const invoice = {
      documentType: 'invoice',
      ...baseDocument,
    };
  
    return {
      success: true,
      deal_id: dealId,
      generated_documents: {
        quotation,
        order,
        invoice,
      },
    };
  }
  return { validateCustomerInfoAndGenerateDocuments };
})();
export const validateCustomerInfoAndGenerateDocuments = __aivicBundle_2_validateCustomerInfoAndGenerateDocuments.validateCustomerInfoAndGenerateDocuments;
/* AIVIC_FUNCTION_BUNDLE_END owner=validateCustomerInfoAndGenerateDocuments */

/* AIVIC_FUNCTION_BUNDLE_START owner=validateDealAmount exports=validateDealAmount */
const __aivicBundle_3_validateDealAmount = (() => {
  function validateDealAmount(dealData: DealRecord): { is_valid: boolean; warning_message?: string } {
    if (dealData["dealId"] === undefined || dealData["dealId"] === null) { throw new Error("dealId is required"); }
    if (dealData["customerId"] === undefined || dealData["customerId"] === null) { throw new Error("customerId is required"); }
    if (dealData["customerName"] === undefined || dealData["customerName"] === null) { throw new Error("customerName is required"); }
    if (dealData["dealStatus"] === undefined || dealData["dealStatus"] === null) { throw new Error("dealStatus is required"); }
    if (dealData.dealAmount === 0) {
      return {
        is_valid: false,
        warning_message: '金額が0円です'
      };
    }
  
    return {
      is_valid: true
    };
  }
  return { validateDealAmount };
})();
export const validateDealAmount: (...args: any[]) => any = (...args: any[]) => (__aivicBundle_3_validateDealAmount.validateDealAmount as (...args: any[]) => any)(...args);
/* AIVIC_FUNCTION_BUNDLE_END owner=validateDealAmount */

/* AIVIC_FUNCTION_BUNDLE_START owner=generateEstimateOrderInvoice exports=generateEstimateOrderInvoice */
const __aivicBundle_4_generateEstimateOrderInvoice = (() => {
  function generateEstimateOrderInvoice(dealData: any): any {
    // Input validation
    if (!dealData) {
      throw new Error('商談データが見つかりません');
    }
  
    const dealId = dealData.deal_id || dealData.dealId;
    const customerId = dealData.customer_id || dealData.customerId;
    const customerName = dealData.customer_name || dealData.customerName;
    const dealAmount = dealData.deal_amount ?? dealData.dealAmount ?? 0;
    
    
    const address = dealData.address || dealData.customerAddress || '';
    const phone = dealData.phone_number || dealData.phoneNumber || dealData.customerPhone || '';
    const email = dealData.email_address || dealData.emailAddress || dealData.customerEmail || '';
  
    if (!customerId || !customerName) {
      throw new Error('顧客情報が見つかりません');
    }
  
    // Extract line items
    const lineItems = dealData.lineItems || dealData.line_items || [];
    
    // Calculate subtotal from line items or use deal amount
    let subtotal = 0;
    const formattedItems: any[] = [];
  
    if (lineItems && lineItems.length > 0) {
      lineItems.forEach((item: any) => {
        const quantity = item.quantity || 0;
        const unitPrice = item.unit_price || item.unitPrice || 0;
        const itemTotal = quantity * unitPrice;
        subtotal += itemTotal;
        
        formattedItems.push({
          lineItemId: item.line_item_id || item.lineItemId,
          itemName: item.product_name || item.productName || item.itemName || '',
          productName: item.product_name || item.productName || item.itemName || '',
          quantity: quantity,
          unitPrice: unitPrice,
          subtotal: itemTotal,
          totalPrice: itemTotal,
          taxRate: item.tax_rate || item.taxRate,
        });
      });
    } else {
      // If no line items, use deal amount as subtotal
      subtotal = dealAmount;
    }
  
    // Calculate tax (assuming 10% if not specified)
    const taxRate = dealData.tax_rate || dealData.taxRate || 0.1;
    const tax = Math.round(subtotal * taxRate);
    const total = subtotal + tax;
  
    // Create document template
    const createDocument = (documentType: string) => ({
      documentType: documentType,
      customerName: customerName,
      customerAddress: address,
      customerPhone: phone,
      customerEmail: email,
      subtotal: subtotal,
      tax: tax,
      total: total,
      total_amount: total,
      items: formattedItems,
      dealId: dealId,
    });
  
    return {
      quotation: createDocument('見積書'),
      estimate: createDocument('見積書'),
      order: createDocument('注文書'),
      invoice: createDocument('請求書'),
    };
  }
  return { generateEstimateOrderInvoice };
})();
export const generateEstimateOrderInvoice = __aivicBundle_4_generateEstimateOrderInvoice.generateEstimateOrderInvoice;
/* AIVIC_FUNCTION_BUNDLE_END owner=generateEstimateOrderInvoice */

/* AIVIC_FUNCTION_BUNDLE_START owner=verifyGeneratedDocuments exports=verifyGeneratedDocuments */
const __aivicBundle_5_verifyGeneratedDocuments = (() => {
  function verifyGeneratedDocuments(generatedDocs: any): {status: string; messages: string[]; is_processable: boolean} {
    const messages: string[] = [];
    let status = 'ok';
    let is_processable = true;
  
    // Null/undefined check
    if (!generatedDocs) {
      messages.push('生成された帳票がありません');
      status = 'error';
      is_processable = false;
      return { status, messages, is_processable };
    }
  
    const estimate = generatedDocs.estimate || generatedDocs.quotation;
    const order = generatedDocs.order;
    const invoice = generatedDocs.invoice;
  
    // Check if all three documents exist
    if (!estimate || !order || !invoice) {
      messages.push('見積書、注文書、請求書のいずれかが生成されていません');
      status = 'error';
      is_processable = false;
      return { status, messages, is_processable };
    }
  
    // Extract amounts - handle both camelCase and snake_case
    const estimateAmount = estimate.total_amount ?? estimate.total ?? 0;
    const orderAmount = order.total_amount ?? order.total ?? 0;
    const invoiceAmount = invoice.total_amount ?? invoice.total ?? 0;
  
    // Check for zero amounts
    if (estimateAmount === 0 || orderAmount === 0 || invoiceAmount === 0) {
      messages.push('金額が0円です');
      status = 'warning';
    }
  
    // Check amount consistency across documents
    if (estimateAmount !== orderAmount || orderAmount !== invoiceAmount) {
      messages.push('見積書、注文書、請求書の金額が一致していません');
      status = 'warning';
    }
  
    // Check for line items existence and consistency
    const estimateItems = estimate.items || [];
    const orderItems = order.items || [];
    const invoiceItems = invoice.items || [];
  
    if (estimateItems.length === 0 && orderItems.length === 0 && invoiceItems.length === 0) {
      messages.push('明細行がありません');
      status = 'warning';
    }
  
    // Validate line items structure
    const validateLineItems = (items: any[], docName: string): boolean => {
      if (!Array.isArray(items)) return false;
      return items.every(item => 
        item && 
        typeof item.itemName === 'string' && 
        typeof item.quantity === 'number' && 
        typeof item.unitPrice === 'number'
      );
    };
  
    if (estimateItems.length > 0 && !validateLineItems(estimateItems, '見積書')) {
      messages.push('見積書の明細行が不正です');
      status = 'warning';
    }
  
    if (orderItems.length > 0 && !validateLineItems(orderItems, '注文書')) {
      messages.push('注文書の明細行が不正です');
      status = 'warning';
    }
  
    if (invoiceItems.length > 0 && !validateLineItems(invoiceItems, '請求書')) {
      messages.push('請求書の明細行が不正です');
      status = 'warning';
    }
  
    // Check required customer information
    const requiredFields = ['customerName'];
    for (const field of requiredFields) {
      if (!estimate[field] && !order[field] && !invoice[field]) {
        messages.push(`顧客情報が不足しています: ${field}`);
        status = 'warning';
      }
    }
  
    // Determine if processable
    is_processable = status !== 'error';
  
    return { status, messages, is_processable };
  }
  return { verifyGeneratedDocuments };
})();
export const verifyGeneratedDocuments = __aivicBundle_5_verifyGeneratedDocuments.verifyGeneratedDocuments;
/* AIVIC_FUNCTION_BUNDLE_END owner=verifyGeneratedDocuments */

/* AIVIC_FUNCTION_BUNDLE_START owner=validateAndGenerateDocuments exports=validateAndGenerateDocuments */
const __aivicBundle_6_validateAndGenerateDocuments = (() => {
  interface ValidateAndGenerateDocumentsInput {
    deal_id: string;
    customer_id: string;
    customer_name: string;
    customer_address: string;
    deal_amount: number;
    deal_status: string;
    deal_date: Date;
    invoice_expected_date: Date;
    line_items: Array<{
      line_item_id?: string;
      product_name: string;
      quantity: number;
      unit_price: number;
      line_total?: number;
    }>;
  }
  
  interface ValidateAndGenerateDocumentsOutput {
    success: boolean;
    error_type?: string;
    warning_message?: string;
    documents_generated: boolean;
    estimate: any;
    order: any;
    invoice: any;
  }
  
   function validateAndGenerateDocuments(
    dealData: ValidateAndGenerateDocumentsInput
  ): ValidateAndGenerateDocumentsOutput {
    // Validate required fields
    if (
      !dealData.deal_id ||
      !dealData.customer_id ||
      !dealData.customer_name ||
      !dealData.customer_address ||
      dealData.deal_amount === undefined ||
      !dealData.deal_status ||
      !dealData.deal_date ||
      !dealData.invoice_expected_date
    ) {
      return {
        success: false,
        error_type: "MISSING_REQUIRED_FIELDS",
        warning_message: "必須項目が不足しています。すべての必須項目を入力してください。",
        documents_generated: false,
        estimate: null,
        order: null,
        invoice: null
      };
    }
  
    // Validate line items - must have at least 2 items
    if (!dealData.line_items || dealData.line_items.length < 2) {
      return {
        success: false,
        error_type: "INSUFFICIENT_LINE_ITEMS",
        warning_message:
          "明細行が不足しています。すべての必須項目の明細行を入力してください。",
        documents_generated: false,
        estimate: null,
        order: null,
        invoice: null
      };
    }
  
    // Validate line items have required fields
    const allLineItemsValid = dealData.line_items.every(
      (item) =>
        item.product_name &&
        item.quantity !== undefined &&
        item.quantity > 0 &&
        item.unit_price !== undefined &&
        item.unit_price > 0
    );
  
    if (!allLineItemsValid) {
      return {
        success: false,
        error_type: "INVALID_LINE_ITEMS",
        warning_message: "明細行に無効な値が含まれています。すべての明細行を確認してください。",
        documents_generated: false,
        estimate: null,
        order: null,
        invoice: null
      };
    }
  
    // Calculate totals from line items
    const subtotal = dealData.line_items.reduce((sum, item) => {
      return sum + item.quantity * item.unit_price;
    }, 0);
  
    // Validate deal amount matches line items total
    if (Math.abs(subtotal - dealData.deal_amount) > 0.01) {
      return {
        success: false,
        error_type: "AMOUNT_MISMATCH",
        warning_message:
          "商談金額と明細行の合計が一致しません。金額を確認してください。",
        documents_generated: false,
        estimate: null,
        order: null,
        invoice: null
      };
    }
  
    // Generate documents
    const taxRate = 0.1; // 10% tax
    const tax = Math.round(subtotal * taxRate);
    const total = subtotal + tax;
  
    const documentItems = dealData.line_items.map((item) => ({
      itemName: item.product_name,
      quantity: item.quantity,
      unitPrice: item.unit_price,
      subtotal: item.quantity * item.unit_price
    }));
  
    const baseDocument = {
      customerName: dealData.customer_name,
      customerAddress: dealData.customer_address,
      subtotal,
      tax,
      total,
      items: documentItems,
      dealId: dealData.deal_id
    };
  
    const estimate = {
      documentType: "ESTIMATE",
      ...baseDocument
    };
  
    const order = {
      documentType: "ORDER",
      ...baseDocument
    };
  
    const invoice = {
      documentType: "INVOICE",
      ...baseDocument
    };
  
    return {
      success: true,
      documents_generated: true,
      estimate,
      order,
      invoice
    };
  }
  return { validateAndGenerateDocuments };
})();
export const validateAndGenerateDocuments = __aivicBundle_6_validateAndGenerateDocuments.validateAndGenerateDocuments;
/* AIVIC_FUNCTION_BUNDLE_END owner=validateAndGenerateDocuments */

/* AIVIC_FUNCTION_BUNDLE_START owner=validateDocumentAmountAndLineItems exports=validateDocumentAmountAndLineItems */
const __aivicBundle_7_validateDocumentAmountAndLineItems = (() => {
  function validateDocumentAmountAndLineItems(documentData: {
    totalAmount: number;
    lineItems: Array<{ amount: number; description: string }>;
    lineCount: number;
  }): {
    status: string;
    isValid: boolean;
    totalAmount: number;
    lineCount: number;
    calculatedTotal: number;
    message: string;
  } {
    const { totalAmount, lineItems, lineCount } = documentData;
  
    // 明細行の合計を計算
    const calculatedTotal = lineItems.reduce((sum, item) => sum + item.amount, 0);
  
    // 明細行数の検証
    const lineCountMatches = lineItems.length === lineCount;
  
    // 合計金額の検証
    const amountMatches = totalAmount === calculatedTotal;
  
    // 明細が存在するかの検証
    const hasLineItems = lineItems.length > 0 && lineCount > 0;
  
    // 検証結果の判定
    let status: string;
    let isValid: boolean;
    let message: string;
  
    if (!hasLineItems) {
      status = "warning";
      isValid = false;
      message = "明細が不足しています";
    } else if (lineCountMatches && amountMatches) {
      status = "OK";
      isValid = true;
      message = "帳票金額と明細が正確です";
    } else if (!lineCountMatches) {
      status = "error";
      isValid = false;
      message = "明細行数が一致しません";
    } else if (!amountMatches) {
      status = "error";
      isValid = false;
      message = `帳票金額と明細の合計が一致しません（帳票: ${totalAmount}, 計算値: ${calculatedTotal}）`;
    } else {
      status = "error";
      isValid = false;
      message = "帳票の検証に失敗しました";
    }
  
    return {
      status,
      isValid,
      totalAmount,
      lineCount,
      calculatedTotal,
      message
    };
  }
  return { validateDocumentAmountAndLineItems };
})();
export const validateDocumentAmountAndLineItems = __aivicBundle_7_validateDocumentAmountAndLineItems.validateDocumentAmountAndLineItems;
/* AIVIC_FUNCTION_BUNDLE_END owner=validateDocumentAmountAndLineItems */

/* AIVIC_FUNCTION_BUNDLE_START owner=validateDocumentAmount exports=validateDocumentAmount */
const __aivicBundle_8_validateDocumentAmount = (() => {
  function validateDocumentAmount(documentData: {
    totalAmount: number;
    lineItems: Array<{ unitPrice: number; quantity: number }>;
  }): {
    status: string;
    actualLineItemTotal: number;
    reportedTotal: number;
    discrepancy: number;
    message?: string;
  } {
    const { totalAmount, lineItems } = documentData;
  
    // Validate totalAmount is non-negative
    if (totalAmount < 0) {
      throw new Error('金額は負の値にできません');
    }
  
    // Validate each line item
    for (const item of lineItems) {
      if (item.unitPrice < 0) {
        throw new Error('単価は負の値にできません');
      }
      if (item.quantity < 0) {
        throw new Error('数量は負の値にできません');
      }
    }
  
    // Check if line items are empty
    if (lineItems.length === 0) {
      return {
        status: 'warning',
        actualLineItemTotal: 0,
        reportedTotal: totalAmount,
        discrepancy: totalAmount,
        message: '明細行がありません',
      };
    }
  
    // Check if line item count exceeds threshold
    if (lineItems.length > 1000) {
      const actualTotal = lineItems.reduce(
        (sum, item) => sum + item.unitPrice * item.quantity,
        0
      );
      return {
        status: 'warning',
        actualLineItemTotal: actualTotal,
        reportedTotal: totalAmount,
        discrepancy: Math.abs(totalAmount - actualTotal),
        message: '明細行数が異常に多い可能性があります',
      };
    }
  
    // Calculate actual line item total
    const actualLineItemTotal = lineItems.reduce(
      (sum, item) => sum + item.unitPrice * item.quantity,
      0
    );
  
    // Calculate discrepancy
    const discrepancy = Math.abs(totalAmount - actualLineItemTotal);
  
    // Determine status based on discrepancy
    if (discrepancy === 0) {
      return {
        status: 'ok',
        actualLineItemTotal,
        reportedTotal: totalAmount,
        discrepancy: 0,
      };
    } else {
      return {
        status: 'error',
        actualLineItemTotal,
        reportedTotal: totalAmount,
        discrepancy,
        message: '金額合計が一致していません',
      };
    }
  }
  return { validateDocumentAmount };
})();
export const validateDocumentAmount = __aivicBundle_8_validateDocumentAmount.validateDocumentAmount;
/* AIVIC_FUNCTION_BUNDLE_END owner=validateDocumentAmount */

/* AIVIC_FUNCTION_BUNDLE_START owner=validateDocumentDetails exports=validateDocumentDetails */
const __aivicBundle_9_validateDocumentDetails = (() => {
  function validateDocumentDetails(documentData: {
    documentId: string;
    customerId: string;
    customerName: string;
    totalAmount: number;
    lineItems: LineItem[];
    documentType: string;
    issueDate: string;
  }): {
    status: string;
    isValid: boolean;
    errorMessage?: string;
    lineItemCount: number;
    validationDetails: {
      hasLineItems: boolean;
      amountValidation: boolean;
    };
  } {
    if (documentData["documentId"] === undefined || documentData["documentId"] === null) { throw new Error("documentId is required"); }
    if (documentData["customerId"] === undefined || documentData["customerId"] === null) { throw new Error("customerId is required"); }
    if (documentData["customerName"] === undefined || documentData["customerName"] === null) { throw new Error("customerName is required"); }
    if (documentData["documentType"] === undefined || documentData["documentType"] === null) { throw new Error("documentType is required"); }
    if (documentData["issueDate"] === undefined || documentData["issueDate"] === null) { throw new Error("issueDate is required"); }
    const lineItemCount = documentData.lineItems?.length ?? 0;
    const hasLineItems = lineItemCount > 0;
  
    if (!hasLineItems) {
      return {
        status: 'NG',
        isValid: false,
        errorMessage: '明細行が存在しません',
        lineItemCount: 0,
        validationDetails: {
          hasLineItems: false,
          amountValidation: false,
        },
      };
    }
  
    const amountValidation = validateDocumentAmountInternal(
      documentData.lineItems,
      documentData.totalAmount
    );
  
    return {
      status: 'OK',
      isValid: true,
      lineItemCount,
      validationDetails: {
        hasLineItems: true,
        amountValidation,
      },
    };
  }
  
  function validateDocumentAmountInternal(
    lineItems: LineItem[],
    totalAmount: number
  ): boolean {
    if (!lineItems || lineItems.length === 0) {
      return false;
    }
  
    const calculatedTotal = lineItems.reduce((sum, item) => {
      const itemTotal = (item.totalPrice ?? item.quantity * item.unitPrice);
      return sum + itemTotal;
    }, 0);
  
    return calculatedTotal > 0 && totalAmount > 0;
  }
  return { validateDocumentDetails };
})();
export const validateDocumentDetails = __aivicBundle_9_validateDocumentDetails.validateDocumentDetails;
/* AIVIC_FUNCTION_BUNDLE_END owner=validateDocumentDetails */

/* AIVIC_FUNCTION_BUNDLE_START owner=validateDocumentLines exports=validateDocumentLines */
const __aivicBundle_10_validateDocumentLines = (() => {
  function validateDocumentLines(documentData: {
    customerId: string;
    customerName: string;
    invoiceAmount: number;
    lineCount: number;
    lines: Array<{
      lineNumber: number;
      productName: string;
      quantity: number;
      unitPrice: number;
      lineAmount: number;
    }>;
    invoiceDate: string;
  }): {
    status: string;
    lineCount: number;
    message?: string;
    isProcessable: boolean;
    warnings: string[];
  } {
    if (documentData["customerId"] === undefined || documentData["customerId"] === null) { throw new Error("customerId is required"); }
    if (documentData["customerName"] === undefined || documentData["customerName"] === null) { throw new Error("customerName is required"); }
    if (documentData["invoiceAmount"] === undefined || documentData["invoiceAmount"] === null) { throw new Error("invoiceAmount is required"); }
    if (documentData["lines"] === undefined || documentData["lines"] === null) { throw new Error("lines is required"); }
    if (documentData["invoiceDate"] === undefined || documentData["invoiceDate"] === null) { throw new Error("invoiceDate is required"); }
    const warnings: string[] = [];
    let status = 'ok';
    let message: string | undefined;
  
    // 業務ロジック: 明細行数が1000行以上の場合は警告を返す
    if (documentData.lineCount >= 1000) {
      status = 'warning';
      message = '明細行数が多いため内容を確認してください';
      warnings.push(`${documentData.lineCount}行以上の明細行が含まれています`);
    }
  
    return {
      status,
      lineCount: documentData.lineCount,
      ...(message !== undefined && { message }),
      isProcessable: true,
      warnings,
    };
  }
  return { validateDocumentLines };
})();
export const validateDocumentLines = __aivicBundle_10_validateDocumentLines.validateDocumentLines;
/* AIVIC_FUNCTION_BUNDLE_END owner=validateDocumentLines */

/* AIVIC_FUNCTION_BUNDLE_START owner=generateQuotationOrderInvoice exports=generateQuotationOrderInvoice */
const __aivicBundle_11_generateQuotationOrderInvoice = (() => {
  function generateQuotationOrderInvoice(dealData: any): DocumentSet {
    // Validate required customer information
    const customerId = dealData.customerId || '';
    const customerName = dealData.customerName || '';
    
    if (!customerId || !customerName) {
      throw new Error('顧客情報が見つかりません');
    }
  
    // Validate required amount
    const amount = dealData.amount ?? dealData.dealAmount;
    if (amount === null || amount === undefined || amount <= 0) {
      throw new Error('金額が見つかりません');
    }
  
    // Extract line items
    const lineItems = dealData.lineItems || dealData.items || [];
    
    // Calculate subtotal from line items or use deal amount
    let subtotal = 0;
    const formattedItems: Array<{
      itemName: string;
      quantity: number;
      unitPrice: number;
      subtotal: number;
    }> = [];
  
    if (lineItems.length > 0) {
      lineItems.forEach((item: any) => {
        const itemName = item.productName || item.itemName || item.description || '';
        const quantity = item.quantity || 0;
        const unitPrice = item.unitPrice || 0;
        const itemSubtotal = quantity * unitPrice;
        
        subtotal += itemSubtotal;
        formattedItems.push({
          itemName,
          quantity,
          unitPrice,
          subtotal: itemSubtotal
        });
      });
    } else {
      subtotal = amount;
    }
  
    // Calculate tax (use provided taxRate or default to 10%)
    const taxRate = dealData.taxRate ?? 0.1;
    const tax = Math.round(subtotal * taxRate);
    const total = subtotal + tax;
  
    // Extract customer contact information
    const customerAddress = dealData.customerAddress || '';
    const customerPhone = dealData.customerPhone || '';
    const customerEmail = dealData.customerEmail || '';
    const dealId = dealData.dealId || '';
  
    // Generate document numbers
    const quotationNumber = `QT-${dealId}-${Date.now()}`;
    const orderNumber = `OR-${dealId}-${Date.now()}`;
    const invoiceNumber = `IV-${dealId}-${Date.now()}`;
  
    // Create base document structure
    const baseDocument = {
      customerName,
      customerId,
      customerAddress,
      customerPhone,
      customerEmail,
      subtotal,
      tax,
      total,
      amount: total,
      items: formattedItems,
      lineItems: formattedItems,
      dealId
    };
  
    return {
      quotation: {
        documentType: '見積書',
        ...baseDocument,
        quotationNumber
      },
      order: {
        documentType: '注文書',
        ...baseDocument,
        orderNumber
      },
      invoice: {
        documentType: '請求書',
        ...baseDocument,
        invoiceNumber
      }
    };
  }
  return { generateQuotationOrderInvoice };
})();
export const generateQuotationOrderInvoice = __aivicBundle_11_generateQuotationOrderInvoice.generateQuotationOrderInvoice;
/* AIVIC_FUNCTION_BUNDLE_END owner=generateQuotationOrderInvoice */

/* AIVIC_FUNCTION_BUNDLE_START owner=generateEstimate exports=generateEstimate */
const __aivicBundle_12_generateEstimate = (() => {
  interface GenerateEstimateInput {
    deal_id?: string;
    dealId?: string;
    customer_name?: string;
    customerName?: string;
    customer_postal_code?: string;
    customerPostalCode?: string;
    customer_address?: string;
    customerAddress?: string;
    line_items?: LineItem[];
    lineItems?: LineItem[];
    estimate_date?: string;
    estimateDate?: string;
    deal_amount?: number;
    dealAmount?: number;
    deal_status?: string;
    dealStatus?: string;
    deal_details?: LineItem[];
    dealDetails?: LineItem[];
    totalAmount?: number;
    total_amount?: number;
    dealName?: string;
    customerId?: string;
    dealDate?: string;
    createdDate?: Date;
    invoiceLineItems?: LineItem[];
    lineId?: string;
    item_id?: string;
    customer_id?: string;
    customer_phone?: string;
    deal_date?: string;
    estimated_invoice_date?: string;
  }
  
  interface GenerateEstimateOutput {
    document_type?: string;
    documentType?: string;
    estimate_number?: string;
    estimateNumber?: string;
    estimate_date?: string;
    estimateDate?: string;
    customer_name?: string;
    customerName?: string;
    customer_postal_code?: string;
    customerPostalCode?: string;
    customer_address?: string;
    customerAddress?: string;
    subtotal?: number;
    tax_amount?: number;
    taxAmount?: number;
    total_amount?: number;
    totalAmount?: number;
    line_items?: LineItem[];
    lineItems?: LineItem[];
    header?: {
      company_name: string;
      company_address: string;
      company_phone: string;
    };
    footer?: {
      payment_terms: string;
      notes: string;
    };
    format_version?: string;
    formatVersion?: string;
    estimateId?: string;
    status?: string;
    errorMessage?: string;
    createdAt?: string;
    details?: LineItem[];
    dealId?: string;
  }
  
   function generateEstimate(dealData: GenerateEstimateInput): GenerateEstimateOutput {
    // Extract normalized field values (handle both snake_case and camelCase)
    const dealId = dealData.deal_id || dealData.dealId || "";
    const customerName = dealData.customer_name || dealData.customerName || "";
    const customerPostalCode = dealData.customer_postal_code || dealData.customerPostalCode || "";
    const customerAddress = dealData.customer_address || dealData.customerAddress || "";
    const estimateDate = dealData.estimate_date || dealData.estimateDate || "";
  
    // Handle line items from multiple possible sources
    let lineItems: LineItem[] = [];
    if (dealData.line_items && Array.isArray(dealData.line_items)) {
      lineItems = dealData.line_items;
    } else if (dealData.lineItems && Array.isArray(dealData.lineItems)) {
      lineItems = dealData.lineItems;
    } else if (dealData.deal_details && Array.isArray(dealData.deal_details)) {
      lineItems = dealData.deal_details;
    } else if (dealData.dealDetails && Array.isArray(dealData.dealDetails)) {
      lineItems = dealData.dealDetails;
    } else if (dealData.invoiceLineItems && Array.isArray(dealData.invoiceLineItems)) {
      lineItems = dealData.invoiceLineItems;
    }
  
    // Generate estimate ID
    const estimateId = randomUUID();
  
    // Calculate subtotal and tax
    let subtotal = 0;
    let taxAmount = 0;
  
    const processedLineItems: LineItem[] = lineItems.map((item) => {
      const itemSubtotal = (item.quantity || 0) * (item.unitPrice || 0);
      const itemTaxRate = item.taxRate || 0;
      const itemTax = itemSubtotal * itemTaxRate;
  
      subtotal += itemSubtotal;
      taxAmount += itemTax;
  
      return {
        ...item,
        totalPrice: itemSubtotal + itemTax,
        lineAmount: itemSubtotal,
      };
    });
  
    const totalAmount = subtotal + taxAmount;
  
    // Generate estimate number based on date
    const dateStr = estimateDate.replace(/-/g, "");
    const sequenceNum = String(lineItems.length).padStart(4, "0");
    const estimateNumber = `EST-${dateStr}-${sequenceNum}`;
  
    // Build the result object with both snake_case and camelCase keys for compatibility
    const result: GenerateEstimateOutput = {
      document_type: "見積書",
      documentType: "見積書",
      estimate_number: estimateNumber,
      estimateNumber: estimateNumber,
      estimate_date: estimateDate,
      estimateDate: estimateDate,
      customer_name: customerName,
      customerName: customerName,
      customer_postal_code: customerPostalCode,
      customerPostalCode: customerPostalCode,
      customer_address: customerAddress,
      customerAddress: customerAddress,
      subtotal: subtotal,
      tax_amount: taxAmount,
      taxAmount: taxAmount,
      total_amount: totalAmount,
      totalAmount: totalAmount,
      line_items: processedLineItems,
      lineItems: processedLineItems,
      details: processedLineItems,
      header: {
        company_name: "営業管理システム",
        company_address: "東京都渋谷区",
        company_phone: "03-XXXX-XXXX",
      },
      footer: {
        payment_terms: "末日払い",
        notes: "本見積書は有効期限30日間です。",
      },
      format_version: "1.0",
      formatVersion: "1.0",
      estimateId: estimateId,
      dealId: dealId,
      status: "有効",
      createdAt: new Date().toISOString(),
    };
  
    return result;
  }
  return { generateEstimate };
})();
export const generateEstimate: (...args: any[]) => any = (...args: any[]) => (__aivicBundle_12_generateEstimate.generateEstimate as (...args: any[]) => any)(...args);
/* AIVIC_FUNCTION_BUNDLE_END owner=generateEstimate */

/* AIVIC_FUNCTION_BUNDLE_START owner=generateOrder exports=generateOrder */
const __aivicBundle_13_generateOrder = (() => {
  function generateOrder(
    dealData: any
  ): {
    documentType?: string;
    document_type?: string;
    orderId?: string;
    order_number?: string;
    order_date?: string;
    customerName?: string;
    customer_name?: string;
    totalAmount?: number;
    total_amount?: number;
    subtotal?: number;
    tax?: number;
    tax_amount?: number;
    status?: string;
    details?: Array<{
      lineId?: string;
      productName?: string;
      quantity?: number;
      unitPrice?: number;
      lineAmount?: number;
    }>;
    line_items?: Array<{
      product_name?: string;
      productName?: string;
      quantity: number;
      unit_price?: number;
      unitPrice: number;
      subtotal?: number;
    }>;
    items?: Array<{
      itemName: string;
      quantity: number;
      unitPrice: number;
      subtotal: number;
    }>;
    dealId?: string;
    deal_id?: string;
    lineItems?: Array<{
      lineId?: number | string;
      productName: string;
      quantity: number;
      unitPrice: number;
    }>;
    errorMessage?: undefined;
  } {
    if (!dealData) {
      return {};
    }
  
    // Normalize input: support both camelCase and snake_case
    const dealId = dealData.dealId || dealData.deal_id;
    const customerName = dealData.customerName || dealData.customer_name;
    const orderDate =
      dealData.order_date || dealData.dealDate || new Date().toISOString().split("T")[0];
  
    // Extract line items from various possible input formats
    let lineItems: Array<{
      lineId?: string | number;
      productName: string;
      quantity: number;
      unitPrice: number;
      lineAmount?: number;
    }> = [];
  
    if (dealData.dealDetails && Array.isArray(dealData.dealDetails)) {
      lineItems = dealData.dealDetails;
    } else if (dealData.lineItems && Array.isArray(dealData.lineItems)) {
      lineItems = dealData.lineItems;
    } else if (dealData.line_items && Array.isArray(dealData.line_items)) {
      lineItems = dealData.line_items.map((item: any) => ({
        lineId: item.lineId || item.line_id,
        productName: item.product_name || item.productName,
        quantity: item.quantity,
        unitPrice: item.unit_price || item.unitPrice,
      }));
    } else if (dealData.items && Array.isArray(dealData.items)) {
      lineItems = dealData.items.map((item: any) => ({
        productName: item.itemName || item.product_name || item.productName,
        quantity: item.quantity,
        unitPrice: item.unit_price || item.unitPrice,
      }));
    } else if (dealData.invoiceLineItems && Array.isArray(dealData.invoiceLineItems)) {
      lineItems = dealData.invoiceLineItems.map((item: any) => ({
        lineId: item.lineId,
        productName: item.productName,
        quantity: item.quantity,
        unitPrice: item.unitPrice,
      }));
    }
  
    // Calculate subtotal and tax
    const subtotal = lineItems.reduce((sum, item) => {
      return sum + item.quantity * item.unitPrice;
    }, 0);
  
    const taxRate = 0.1; // 10% tax rate
    const taxAmount = Math.round(subtotal * taxRate);
    const totalAmount = subtotal + taxAmount;
  
    // Generate order number using UUID
    const uuidPart = randomUUID().replace(/-/g, "").substring(0, 4);
    const dateStr = orderDate.replace(/-/g, "");
    const orderNumber = `ORD-${dateStr}-${uuidPart}`;
  
    // Build details array for compatibility with test expectations
    const details = lineItems.map((item, index) => ({
      lineId: String(item.lineId || `LINE-${String(index + 1).padStart(3, "0")}`),
      productName: item.productName,
      quantity: item.quantity,
      unitPrice: item.unitPrice,
      lineAmount: item.quantity * item.unitPrice,
    }));
  
    // Build line_items array for snake_case compatibility
    const lineItemsOutput = lineItems.map((item) => ({
      product_name: item.productName,
      productName: item.productName,
      quantity: item.quantity,
      unit_price: item.unitPrice,
      unitPrice: item.unitPrice,
      subtotal: item.quantity * item.unitPrice,
    }));
  
    // Build items array for camelCase compatibility
    const itemsOutput = lineItems.map((item) => ({
      itemName: item.productName,
      quantity: item.quantity,
      unitPrice: item.unitPrice,
      subtotal: item.quantity * item.unitPrice,
    }));
  
    // Build line_items array with numeric lineId for test compatibility
    const lineItemsWithId = lineItems.map((item, index) => ({
      lineId: typeof item.lineId === "number" ? item.lineId : index + 1,
      productName: item.productName,
      quantity: item.quantity,
      unitPrice: item.unitPrice,
    }));
  
    return {
      documentType: "注文書",
      document_type: "注文書",
      orderId: `ORD-${dealId}`,
      order_number: orderNumber,
      order_date: orderDate,
      customerName: customerName,
      customer_name: customerName,
      totalAmount: totalAmount,
      total_amount: totalAmount,
      subtotal: subtotal,
      tax: taxAmount,
      tax_amount: taxAmount,
      status: "有効",
      details: details,
      line_items: lineItemsOutput,
      items: itemsOutput,
      dealId: dealId,
      deal_id: dealId,
      lineItems: lineItemsWithId,
    };
  }
  return { generateOrder };
})();
export const generateOrder: (...args: any[]) => any = (...args: any[]) => (__aivicBundle_13_generateOrder.generateOrder as (...args: any[]) => any)(...args);
/* AIVIC_FUNCTION_BUNDLE_END owner=generateOrder */

/* AIVIC_FUNCTION_BUNDLE_START owner=generateInvoice exports=generateInvoice */
const __aivicBundle_14_generateInvoice = (() => {
  interface GenerateInvoiceInput {
    customerId?: string;
    customer_id?: string;
    customerName?: string;
    customer_name?: string;
    dealAmount?: number;
    deal_amount?: number;
    dealStatus?: string;
    deal_status?: string;
    dealId?: string;
    deal_id?: string;
    dealDetails?: Array<{
      productId?: string;
      product_id?: string;
      productName?: string;
      product_name?: string;
      quantity: number;
      unitPrice?: number;
      unit_price?: number;
      lineAmount?: number;
      line_amount?: number;
      taxRate?: number;
      tax_rate?: number;
      lineId?: string | number;
      item_id?: string;
    }>;
    deal_details?: Array<any>;
    invoiceDetails?: Array<any>;
    order_number?: string;
    invoice_date?: string;
    due_date?: string;
    customer_postal_code?: string;
    customer_address?: string;
    customer_phone?: string;
    dealName?: string;
    dealDate?: string;
    lineItems?: Array<any>;
    line_items?: Array<any>;
  }
  
  interface GenerateInvoiceOutput {
    [key: string]: any;
  }
  
   function generateInvoice(
    dealData: GenerateInvoiceInput
  ): GenerateInvoiceOutput {
    const customerId =
      dealData.customerId || dealData.customer_id || "";
    const customerName =
      dealData.customerName || dealData.customer_name || "";
    const dealId = dealData.dealId || dealData.deal_id || "";
    const invoiceDate = dealData.invoice_date || "";
    const dueDate = dealData.due_date || "";
    const customerPostalCode = dealData.customer_postal_code || "";
    const customerAddress = dealData.customer_address || "";
    const customerPhone = dealData.customer_phone || "";
  
    if (!customerName || customerName.trim() === "") {
      throw new Error("顧客名は必須項目です");
    }
    if (!customerId || customerId.trim() === "") {
      throw new Error("顧客IDは必須項目です");
    }
  
    let lineItems: Array<{
      productId?: string;
      productName: string;
      quantity: number;
      unitPrice: number;
      lineAmount: number;
      taxRate: number;
      lineId?: string | number;
    }> = [];
  
    const details =
      dealData.dealDetails ||
      dealData.deal_details ||
      dealData.invoiceDetails ||
      dealData.lineItems ||
      dealData.line_items ||
      [];
  
    if (Array.isArray(details) && details.length > 0) {
      lineItems = details.map((item: any) => {
        const productName =
          item.productName || item.product_name || "";
        const quantity = item.quantity || 0;
        const unitPrice =
          item.unitPrice || item.unit_price || 0;
        const lineAmount = quantity * unitPrice;
        const taxRate = item.taxRate || item.tax_rate || 0.1;
        const lineId = item.lineId || item.item_id;
  
        return {
          productId: item.productId || item.product_id,
          productName,
          quantity,
          unitPrice,
          lineAmount,
          taxRate,
          lineId,
        };
      });
    }
  
    const subtotal = lineItems.reduce(
      (sum, item) => sum + item.lineAmount,
      0
    );
    const taxRate = lineItems.length > 0 ? lineItems[0].taxRate : 0.1;
    const taxAmount = Math.round(subtotal * taxRate);
    const totalAmount = subtotal + taxAmount;
  
    const invoiceId = randomUUID();
    const timestamp = new Date().toISOString().split("T")[0].replace(/-/g, "");
    const invoiceNumberSuffix = invoiceId.substring(0, 4).toUpperCase();
    const invoiceNumber = `INV-${timestamp}-${invoiceNumberSuffix}`;
  
    const output: GenerateInvoiceOutput = {
      invoiceNumber,
      invoice_number: invoiceNumber,
      invoiceId,
      invoice_id: invoiceId,
      customerId,
      customer_id: customerId,
      customerName,
      customer_name: customerName,
      invoiceAmount: totalAmount,
      invoice_amount: totalAmount,
      invoiceStatus: "発行済み",
      invoice_status: "発行済み",
      status: "有効",
      createdAt: new Date().toISOString(),
      created_at: new Date().toISOString(),
      dealId,
      deal_id: dealId,
      subtotal,
      tax_amount: taxAmount,
      total_amount: totalAmount,
      totalAmount,
      document_type: "請求書",
      invoice_date: invoiceDate,
      due_date: dueDate,
      customer_postal_code: customerPostalCode,
      customer_address: customerAddress,
      customer_phone: customerPhone,
      format_version: "1.0",
      invoiceDetails: lineItems.map((item) => ({
        productId: item.productId,
        productName: item.productName,
        quantity: item.quantity,
        unitPrice: item.unitPrice,
        lineAmount: item.lineAmount,
      })),
      details: lineItems.map((item) => ({
        lineAmount: item.lineAmount,
      })),
      lineItems: lineItems.map((item) => ({
        lineId: item.lineId,
        productName: item.productName,
        quantity: item.quantity,
        unitPrice: item.unitPrice,
      })),
      header: {
        company_name: "発行会社",
        company_address: customerAddress,
        company_phone: customerPhone,
      },
      amount_section: {
        subtotal_label: "小計",
        tax_label: "消費税",
      },
      footer: {},
    };
  
    if (lineItems.length > 0) {
      output.invoice_line_items = lineItems.map((item, index) => ({
        line_id: item.lineId || index + 1,
        product_name: item.productName,
        quantity: item.quantity,
        unit_price: item.unitPrice,
        subtotal: item.lineAmount,
        tax_amount: Math.round(item.lineAmount * item.taxRate),
        total: item.lineAmount + Math.round(item.lineAmount * item.taxRate),
        tax_rate: item.taxRate,
        line_order: index + 1,
      }));
    }
  
    return output;
  }
  return { generateInvoice };
})();
export const generateInvoice: (...args: any[]) => any = (...args: any[]) => (__aivicBundle_14_generateInvoice.generateInvoice as (...args: any[]) => any)(...args);
/* AIVIC_FUNCTION_BUNDLE_END owner=generateInvoice */

/* AIVIC_FUNCTION_BUNDLE_START owner=generateInvoiceFromUnbilledDeal exports=generateInvoiceFromUnbilledDeal */
const __aivicBundle_15_generateInvoiceFromUnbilledDeal = (() => {
  interface GenerateInvoiceFromUnbilledDealInput {
    dealId: string;
    customerId: string;
    customerName: string;
    customerCode?: string;
    dealAmount: number;
    dealStatus: string;
    dealDate: string;
    dueDate?: string;
    lineItems: Array<{
      lineId: string;
      productId: string;
      productName: string;
      quantity: number;
      unitPrice: number;
      totalPrice: number;
      taxRate: number;
    }>;
    billingStatus: string;
  }
  
  interface GenerateInvoiceFromUnbilledDealOutput {
    customerId: string;
    customerName: string;
    customerCode?: string;
    subtotalAmount: number;
    taxAmount: number;
    totalAmount: number;
    lineItems: Array<{
      productId: string;
      productName: string;
      quantity: number;
      unitPrice: number;
      totalPrice: number;
    }>;
    invoiceStatus: string;
    invoiceId: string;
    referredDealId: string;
    generatedAt: string;
  }
  
   function generateInvoiceFromUnbilledDeal(
    unbilledDeal: GenerateInvoiceFromUnbilledDealInput
  ): GenerateInvoiceFromUnbilledDealOutput {
    // 顧客情報を抽出
    const customerId = unbilledDeal.customerId;
    const customerName = unbilledDeal.customerName;
    const customerCode = unbilledDeal.customerCode;
  
    // 金額を計算
    const subtotalAmount = unbilledDeal.dealAmount;
  
    // 税額を計算（lineItems の taxRate から加重平均を求める）
    let totalTaxAmount = 0;
    for (const lineItem of unbilledDeal.lineItems) {
      const lineTaxAmount = lineItem.totalPrice * lineItem.taxRate;
      totalTaxAmount += lineTaxAmount;
    }
    const taxAmount = totalTaxAmount;
  
    // 合計金額を計算
    const totalAmount = subtotalAmount + taxAmount;
  
    // 明細行を抽出（税率情報は除外）
    const lineItems = unbilledDeal.lineItems.map((item) => ({
      productId: item.productId,
      productName: item.productName,
      quantity: item.quantity,
      unitPrice: item.unitPrice,
      totalPrice: item.totalPrice,
    }));
  
    // 請求書IDを生成
    const invoiceId = randomUUID();
  
    // 生成日時を取得
    const generatedAt = new Date().toISOString();
  
    return {
      customerId,
      customerName,
      ...(customerCode !== undefined && { customerCode }),
      subtotalAmount,
      taxAmount,
      totalAmount,
      lineItems,
      invoiceStatus: "下書き",
      invoiceId,
      referredDealId: unbilledDeal.dealId,
      generatedAt,
    };
  }
  return { generateInvoiceFromUnbilledDeal };
})();
export const generateInvoiceFromUnbilledDeal = __aivicBundle_15_generateInvoiceFromUnbilledDeal.generateInvoiceFromUnbilledDeal;
/* AIVIC_FUNCTION_BUNDLE_END owner=generateInvoiceFromUnbilledDeal */

/* AIVIC_FUNCTION_BUNDLE_START owner=validateInvoiceFormat exports=validateInvoiceFormat */
const __aivicBundle_16_validateInvoiceFormat = (() => {
  function validateInvoiceFormat(input: {
    invoice: {
      document_type: string;
      invoice_number: string;
      invoice_date: string;
      due_date: string;
      customer_name: string;
      customer_postal_code?: string;
      customer_address?: string;
      subtotal: number;
      tax_amount: number;
      total_amount: number;
      line_items?: Array<any>;
      header?: {
        company_name: string;
        company_address: string;
        company_phone: string;
      };
      amount_section?: {
        subtotal_label: string;
        subtotal_value: number;
        tax_label: string;
        tax_value: number;
        total_label: string;
        total_value: number;
      };
      footer?: {
        payment_terms: string;
        notes: string;
        signature_line?: string;
      };
      format_version: string;
    };
    format_rules: {
      header_required: boolean;
      amount_section_required: boolean;
      footer_required: boolean;
      date_format: string;
      document_number_pattern: string;
      tax_rate: number;
    };
  }): {
    is_valid: boolean;
    validation_errors: string[];
    header_valid: boolean;
    amount_section_valid: boolean;
    footer_valid: boolean;
    date_format_valid: boolean;
    document_number_valid: boolean;
    line_items_valid: boolean;
    consistency_score: number;
  } {
    const errors: string[] = [];
    let headerValid = true;
    let amountSectionValid = true;
    let footerValid = true;
    let dateFormatValid = true;
    let documentNumberValid = true;
    let lineItemsValid = true;
  
    // Validate header
    if (input.format_rules.header_required) {
      if (!input.invoice.header) {
        errors.push('ヘッダが必須ですが存在しません');
        headerValid = false;
      } else {
        const header = input.invoice.header;
        if (!header.company_name || !header.company_address || !header.company_phone) {
          errors.push('ヘッダの必須フィールドが不足しています');
          headerValid = false;
        }
      }
    } else if (input.invoice.header) {
      headerValid = true;
    }
  
    // Validate amount section
    if (input.format_rules.amount_section_required) {
      if (!input.invoice.amount_section) {
        errors.push('金額セクションが必須ですが存在しません');
        amountSectionValid = false;
      } else {
        const amountSection = input.invoice.amount_section;
        if (
          amountSection.subtotal_value !== input.invoice.subtotal ||
          amountSection.tax_value !== input.invoice.tax_amount ||
          amountSection.total_value !== input.invoice.total_amount
        ) {
          errors.push('金額セクションの値が請求書の金額と一致しません');
          amountSectionValid = false;
        }
      }
    } else if (input.invoice.amount_section) {
      amountSectionValid = true;
    }
  
    // Validate footer
    if (input.format_rules.footer_required) {
      if (!input.invoice.footer) {
        errors.push('フッタが必須ですが存在しません');
        footerValid = false;
      } else {
        const footer = input.invoice.footer;
        if (!footer.payment_terms || !footer.notes) {
          errors.push('フッタの必須フィールドが不足しています');
          footerValid = false;
        }
      }
    } else if (input.invoice.footer) {
      footerValid = true;
    }
  
    // Validate date format
    const dateFormatPattern = input.format_rules.date_format === 'YYYY-MM-DD'
      ? /^\d{4}-\d{2}-\d{2}$/
      : /^\d{4}-\d{2}-\d{2}$/;
  
    if (!dateFormatPattern.test(input.invoice.invoice_date)) {
      errors.push('日付形式が不正');
      dateFormatValid = false;
    }
  
    if (!dateFormatPattern.test(input.invoice.due_date)) {
      errors.push('期限日の日付形式が不正');
      dateFormatValid = false;
    }
  
    // Validate document number format
    const documentNumberRegex = new RegExp(input.format_rules.document_number_pattern);
    if (!documentNumberRegex.test(input.invoice.invoice_number)) {
      errors.push('請求書番号形式が不正');
      documentNumberValid = false;
    }
  
    // Validate line items
    if (!input.invoice.line_items || input.invoice.line_items.length === 0) {
      errors.push('明細行が空');
      lineItemsValid = false;
    } else {
      lineItemsValid = true;
    }
  
    // Validate amount consistency
    const expectedTax = input.invoice.subtotal * input.format_rules.tax_rate;
    const expectedTotal = input.invoice.subtotal + input.invoice.tax_amount;
  
    if (Math.abs(input.invoice.tax_amount - expectedTax) > 0.01) {
      errors.push('消費税の計算が不正です');
    }
  
    if (Math.abs(input.invoice.total_amount - expectedTotal) > 0.01) {
      errors.push('合計金額の計算が不正です');
    }
  
    // Calculate consistency score
    const totalChecks = 8;
    const passedChecks =
      (headerValid ? 1 : 0) +
      (amountSectionValid ? 1 : 0) +
      (footerValid ? 1 : 0) +
      (dateFormatValid ? 1 : 0) +
      (documentNumberValid ? 1 : 0) +
      (lineItemsValid ? 1 : 0) +
      (input.invoice.document_type === '請求書' ? 1 : 0) +
      (input.invoice.format_version === '1.0' ? 1 : 0);
  
    const consistencyScore = Math.round((passedChecks / totalChecks) * 100);
  
    const isValid =
      errors.length === 0 &&
      headerValid &&
      amountSectionValid &&
      footerValid &&
      dateFormatValid &&
      documentNumberValid &&
      lineItemsValid;
  
    return {
      is_valid: isValid,
      validation_errors: errors,
      header_valid: headerValid,
      amount_section_valid: amountSectionValid,
      footer_valid: footerValid,
      date_format_valid: dateFormatValid,
      document_number_valid: documentNumberValid,
      line_items_valid: lineItemsValid,
      consistency_score: consistencyScore,
    };
  }
  return { validateInvoiceFormat };
})();
export const validateInvoiceFormat: (...args: any[]) => any = (...args: any[]) => (__aivicBundle_16_validateInvoiceFormat.validateInvoiceFormat as (...args: any[]) => any)(...args);
/* AIVIC_FUNCTION_BUNDLE_END owner=validateInvoiceFormat */

/* AIVIC_FUNCTION_BUNDLE_START owner=generateInvoiceFromDeal exports=generateInvoiceFromDeal */
const __aivicBundle_17_generateInvoiceFromDeal = (() => {
  interface GenerateInvoiceFromDealInput {
    deal_id: string;
    customer_id: string;
    customer_name: string;
    status: string;
    line_items: Array<{
      line_id: string;
      product_name: string;
      quantity: number;
      unit_price: number;
      tax_rate: number;
      line_order: number;
    }>;
  }
  
  interface GenerateInvoiceFromDealLineItem {
    line_id: string;
    product_name: string;
    quantity: number;
    unit_price: number;
    subtotal: number;
    tax_amount: number;
    total: number;
    tax_rate: number;
    line_order: number;
  }
  
  interface GenerateInvoiceFromDealOutput {
    invoice_id: string;
    customer_id: string;
    customer_name: string;
    deal_id: string;
    status: string;
    subtotal: number;
    tax_amount: number;
    total_amount: number;
    invoice_line_items: GenerateInvoiceFromDealLineItem[];
  }
  
   function generateInvoiceFromDeal(
    dealData: GenerateInvoiceFromDealInput
  ): GenerateInvoiceFromDealOutput {
    const invoiceLineItems: GenerateInvoiceFromDealLineItem[] = dealData.line_items.map(
      (item) => {
        const subtotal = item.quantity * item.unit_price;
        const tax_amount = Math.round(subtotal * item.tax_rate * 100) / 100;
        const total = subtotal + tax_amount;
  
        return {
          line_id: item.line_id,
          product_name: item.product_name,
          quantity: item.quantity,
          unit_price: item.unit_price,
          subtotal,
          tax_amount,
          total,
          tax_rate: item.tax_rate,
          line_order: item.line_order,
        };
      }
    );
  
    const subtotal = invoiceLineItems.reduce(
      (sum, item) => sum + item.subtotal,
      0
    );
    const tax_amount = invoiceLineItems.reduce(
      (sum, item) => sum + item.tax_amount,
      0
    );
    const total_amount = subtotal + tax_amount;
  
    return {
      invoice_id: randomUUID(),
      customer_id: dealData.customer_id,
      customer_name: dealData.customer_name,
      deal_id: dealData.deal_id,
      status: dealData.status,
      subtotal,
      tax_amount,
      total_amount,
      invoice_line_items: invoiceLineItems,
    };
  }
  return { generateInvoiceFromDeal };
})();
export const generateInvoiceFromDeal = __aivicBundle_17_generateInvoiceFromDeal.generateInvoiceFromDeal;
/* AIVIC_FUNCTION_BUNDLE_END owner=generateInvoiceFromDeal */

/* AIVIC_FUNCTION_BUNDLE_START owner=determineInvoicingTiming exports=determineInvoicingTiming */
const __aivicBundle_18_determineInvoicingTiming = (() => {
  function determineInvoicingTiming(dealRecord: {
    dealId: string;
    customerId: string;
    dealAmount: number;
    dealStatus: string;
    invoicingType: string;
    invoicingScheduledDate: string;
    createdAt: string;
    lastUpdatedAt: string;
  }): {
    dealId: string;
    invoicingType: string;
    extractionStatusConfirmed: boolean;
    dealStatus: string;
    confirmationTimestamp: string;
  } {
    if (dealRecord["customerId"] === undefined || dealRecord["customerId"] === null) { throw new Error("customerId is required"); }
    if (dealRecord["dealAmount"] === undefined || dealRecord["dealAmount"] === null) { throw new Error("dealAmount is required"); }
    if (dealRecord["dealStatus"] === undefined || dealRecord["dealStatus"] === null) { throw new Error("dealStatus is required"); }
    if (dealRecord["invoicingScheduledDate"] === undefined || dealRecord["invoicingScheduledDate"] === null) { throw new Error("invoicingScheduledDate is required"); }
    if (dealRecord["createdAt"] === undefined || dealRecord["createdAt"] === null) { throw new Error("createdAt is required"); }
    const confirmationTimestamp = dealRecord.lastUpdatedAt || new Date().toISOString();
  
    return {
      dealId: dealRecord.dealId,
      invoicingType: dealRecord.invoicingType,
      extractionStatusConfirmed: true,
      dealStatus: "抽出対象確定",
      confirmationTimestamp: confirmationTimestamp,
    };
  }
  return { determineInvoicingTiming };
})();
export const determineInvoicingTiming = __aivicBundle_18_determineInvoicingTiming.determineInvoicingTiming;
/* AIVIC_FUNCTION_BUNDLE_END owner=determineInvoicingTiming */

/* AIVIC_FUNCTION_BUNDLE_START owner=determineBillingExecutionTiming exports=determineBillingExecutionTiming */
const __aivicBundle_19_determineBillingExecutionTiming = (() => {
  function determineBillingExecutionTiming(
    dealRecord: any,
    currentDate?: Date | string
  ): BillingExecutionResult {
    const now = currentDate
      ? new Date(currentDate)
      : new Date();
  
    // Handle null/undefined input
    if (!dealRecord) {
      return {
        billingType: '',
        shouldExecute: false,
        executionTiming: '',
        matched_records_count: 0,
      };
    }
  
    // Determine billing type from input
    const billingType = dealRecord.billingType || dealRecord.billing_type;
  
    if (!billingType) {
      throw new Error('請求タイプが設定されていません。商談の契約情報を確認してください。');
    }
  
    // Parse timezone offset
    const timezoneOffset = dealRecord.timezone_offset || '+09:00';
    const offsetMatch = timezoneOffset.match(/([+-])(\d{2}):?(\d{2})/);
    const offsetHours = offsetMatch
      ? parseInt(offsetMatch[1] + offsetMatch[2]) + parseInt(offsetMatch[3]) / 60
      : 9;
  
    // Calculate local date from UTC
    const localDate = new Date(now.getTime() + offsetHours * 60 * 60 * 1000);
    const localDateStr = localDate.toISOString().split('T')[0];
  
    // Determine execution timing and shouldExecute based on billing type
    let shouldExecute = false;
    let executionTiming = billingType;
    
    let reason: string | undefined;
    let executionTimestamp: string | undefined;
    let adjustedExecutionDay: number | undefined;
  
    if (billingType === 'AFTER_DELIVERY' || billingType === 'ADHOC_AFTER_DELIVERY') {
      const deliveryDate = dealRecord.deliveryDate
        ? new Date(dealRecord.deliveryDate)
        : null;
  
      if (deliveryDate) {
        shouldExecute = now >= deliveryDate;
        executionTiming = billingType;
  
        if (shouldExecute) {
          const executionTimeUtc = dealRecord.execution_time_utc || '10:00:00';
          const [hours, minutes, seconds] = executionTimeUtc.split(':').map(Number);
          const execDate = new Date(localDateStr);
          execDate.setUTCHours(hours - offsetHours, minutes, seconds, 0);
          executionTimestamp = execDate.toISOString().replace('Z', timezoneOffset);
        }
      }
    } else if (billingType === 'CUSTOM') {
      const customBillingRule = dealRecord.customBillingRule;
  
      if (customBillingRule && customBillingRule.billingDate) {
        const billingDate = new Date(customBillingRule.billingDate);
        shouldExecute = now >= billingDate;
        executionTiming = 'CUSTOM';
  
        if (shouldExecute) {
          const executionTimeUtc = dealRecord.execution_time_utc || '10:00:00';
          const [hours, minutes, seconds] = executionTimeUtc.split(':').map(Number);
          const execDate = new Date(localDateStr);
          execDate.setUTCHours(hours - offsetHours, minutes, seconds, 0);
          executionTimestamp = execDate.toISOString().replace('Z', timezoneOffset);
        }
      }
    } else if (billingType === 'MONTHLY' || billingType === 'REGULAR_MONTHLY') {
      const executionDay = dealRecord.execution_day || 1;
      const currentDay = localDate.getUTCDate();
      const currentMonth = localDate.getUTCMonth();
      const currentYear = localDate.getUTCFullYear();
  
      // Handle month-end adjustment for months with fewer days
      let adjustedDay = executionDay;
      const daysInMonth = new Date(currentYear, currentMonth + 1, 0).getUTCDate();
      if (executionDay > daysInMonth) {
        adjustedDay = daysInMonth;
      }
  
      shouldExecute = currentDay === adjustedDay;
      executionTiming = billingType;
  
      if (shouldExecute) {
        const executionTimeUtc = dealRecord.execution_time_utc || '09:00:00';
        const [hours, minutes, seconds] = executionTimeUtc.split(':').map(Number);
        const execDate = new Date(localDateStr);
        execDate.setUTCHours(hours - offsetHours, minutes, seconds, 0);
        executionTimestamp = execDate.toISOString().replace('Z', timezoneOffset);
      }
  
      if (adjustedDay !== executionDay) {
        adjustedExecutionDay = adjustedDay;
      }
    } else if (billingType === 'PREPAY_ADVANCE') {
      const advanceDays = dealRecord.advance_days_before_due || 0;
      const deliveryDate = dealRecord.deliveryDate
        ? new Date(dealRecord.deliveryDate)
        : null;
  
      if (deliveryDate) {
        const billingDueDate = new Date(deliveryDate);
        billingDueDate.setUTCDate(billingDueDate.getUTCDate() - advanceDays);
        shouldExecute = now >= billingDueDate;
        executionTiming = 'PREPAY_ADVANCE';
  
        if (shouldExecute) {
          const executionTimeUtc = dealRecord.execution_time_utc || '08:00:00';
          const [hours, minutes, seconds] = executionTimeUtc.split(':').map(Number);
          const execDate = new Date(localDateStr);
          execDate.setUTCHours(hours - offsetHours, minutes, seconds, 0);
          executionTimestamp = execDate.toISOString().replace('Z', timezoneOffset);
        }
      }
    }
  
    // Build result object with both camelCase and snake_case properties for test compatibility
    const result: any = {
      billingType,
      shouldExecute,
      shouldExecuteBilling: shouldExecute,
      executionTiming,
      matched_records_count: 0,
      billing_type: billingType,
      should_execute: shouldExecute,
      local_date: localDateStr,
    };
  
    if (executionTimestamp) {
      result.execution_timestamp = executionTimestamp;
    }
  
    if (adjustedExecutionDay !== undefined) {
      result.execution_day_adjusted = adjustedExecutionDay;
    }
  
    if (reason) {
      result.reason = reason;
    }
  
    if (!shouldExecute && !executionTimestamp) {
      result.reason = '実行時刻に未到達です。';
    }
  
    // Add log entry if execution is happening
    if (shouldExecute && executionTimestamp) {
      result.log_entry = {
        timestamp: executionTimestamp,
        billing_type: billingType,
        execution_result: 'EXECUTED',
        target_deals_count: 0,
      };
    }
  
    // Add matched deal IDs array
    if (dealRecord.dealId) {
      result.matched_deal_ids = [dealRecord.dealId];
    } else {
      result.matched_deal_ids = [];
    }
  
    return result;
  }
  return { determineBillingExecutionTiming };
})();
export const determineBillingExecutionTiming = __aivicBundle_19_determineBillingExecutionTiming.determineBillingExecutionTiming;
/* AIVIC_FUNCTION_BUNDLE_END owner=determineBillingExecutionTiming */

/* AIVIC_FUNCTION_BUNDLE_START owner=extractDealData exports=extractDealData */
const __aivicBundle_20_extractDealData = (() => {
  function extractDealData(
    dealRecords: Array<{
      deal_id: string;
      customer_id: string;
      status: string;
      amount: number;
      deal_date: string;
      contract_date?: string | null;
    }>,
    extractionCriteria: {
      status: string;
      min_amount: number;
      period_start: string;
      period_end: string;
    }
  ): {
    extracted_count: number;
    total_amount: number;
    deals: Array<{
      deal_id: string;
      customer_id: string;
      status: string;
      amount: number;
      contract_date?: string;
    }>;
  } {
    const periodStart = new Date(extractionCriteria.period_start);
    const periodEnd = new Date(extractionCriteria.period_end);
  
    const filteredDeals = dealRecords.filter((deal) => {
      // ステータスが一致するか確認
      if (deal.status !== extractionCriteria.status) {
        return false;
      }
  
      // 金額が最小金額以上か確認
      if (deal.amount < extractionCriteria.min_amount) {
        return false;
      }
  
      // contract_date が存在し、期間内か確認
      if (deal.contract_date) {
        const contractDate = new Date(deal.contract_date);
        if (contractDate < periodStart || contractDate > periodEnd) {
          return false;
        }
      } else {
        // contract_date が null または undefined の場合は除外
        return false;
      }
  
      return true;
    });
  
    const totalAmount = filteredDeals.reduce((sum, deal) => sum + deal.amount, 0);
  
    const deals = filteredDeals.map((deal) => ({
      deal_id: deal.deal_id,
      customer_id: deal.customer_id,
      status: deal.status,
      amount: deal.amount,
      contract_date: deal.contract_date,
    }));
  
    return {
      extracted_count: filteredDeals.length,
      total_amount: totalAmount,
      deals,
    };
  }
  return { extractDealData };
})();
export const extractDealData = __aivicBundle_20_extractDealData.extractDealData;
/* AIVIC_FUNCTION_BUNDLE_END owner=extractDealData */

/* AIVIC_FUNCTION_BUNDLE_START owner=extractBillingTargetData exports=extractBillingTargetData */
const __aivicBundle_21_extractBillingTargetData = (() => {
  function extractBillingTargetData(
    input: any,
    criteria?: any
  ): ExtractionResult {
    // Normalize input: handle both direct array and object with billing_data
    let billingData: Array<any> = [];
    let minAmount = 0;
    let maxAmount = Number.MAX_SAFE_INTEGER;
    let statusFilter: string | undefined;
    let billingPeriodStart: string | undefined;
    let billingPeriodEnd: string | undefined;
    let billingStatus: string | undefined;
    let customerSegment: string | undefined;
  
    // Parse first argument
    if (Array.isArray(input)) {
      billingData = input;
    } else if (input && typeof input === "object") {
      billingData = input.billing_data || [];
      minAmount = input.min_amount !== undefined ? input.min_amount : 0;
      maxAmount =
        input.max_amount !== undefined ? input.max_amount : Number.MAX_SAFE_INTEGER;
      statusFilter = input.status_filter;
      billingPeriodStart = input.billingPeriodStart;
      billingPeriodEnd = input.billingPeriodEnd;
      billingStatus = input.billingStatus;
      customerSegment = input.customerSegment;
    }
  
    // Parse second argument (criteria)
    if (criteria && typeof criteria === "object") {
      if (criteria.billing_status) billingStatus = criteria.billing_status;
      if (criteria.period_start) billingPeriodStart = criteria.period_start;
      if (criteria.period_end) billingPeriodEnd = criteria.period_end;
      if (criteria.customer_type) customerSegment = criteria.customer_type;
      if (criteria.min_sales_amount !== undefined) {
        minAmount = criteria.min_sales_amount;
      }
    }
  
    // Filter records based on criteria
    const filtered = billingData.filter((record: any) => {
      // Amount range filter (check both 'amount' and 'sales_amount' fields)
      const recordAmount = record.amount !== undefined ? record.amount : record.sales_amount || 0;
      if (recordAmount < minAmount || recordAmount > maxAmount) {
        return false;
      }
  
      // Status filter (check both 'status' and 'billing_status' fields)
      if (statusFilter) {
        const recordStatus = record.status || record.billing_status;
        if (recordStatus !== statusFilter) {
          return false;
        }
      }
  
      // Billing status filter
      if (billingStatus) {
        if (record.billing_status !== billingStatus) {
          return false;
        }
      }
  
      // Period filter (check deal_date or billing_date)
      if (billingPeriodStart || billingPeriodEnd) {
        const recordDate = record.deal_date || record.billing_date;
        if (billingPeriodStart && recordDate < billingPeriodStart) {
          return false;
        }
        if (billingPeriodEnd && recordDate > billingPeriodEnd) {
          return false;
        }
      }
  
      // Customer segment/type filter
      if (customerSegment) {
        if (record.customer_type !== customerSegment) {
          return false;
        }
      }
  
      return true;
    });
  
    // If no records match and we have filtering criteria, return empty result
    if (filtered.length === 0) {
      return {
        records: [],
        totalCount: 0,
        isDownloadEnabled: false,
        errorMessage: null,
      };
    }
  
    // Generate timestamp for export filename
    const now = new Date();
    const dateStr = now.toISOString().slice(0, 10).replace(/-/g, "");
    const timeStr = now.toISOString().slice(11, 19).replace(/:/g, "");
    const exportFilename = `billing_data_${dateStr}_${timeStr}.csv`;
  
    // Determine output format based on input structure
    const hasExtractedRecordsKey =
      input && typeof input === "object" && !Array.isArray(input) && input.billing_data;
    
  
    if (hasExtractedRecordsKey || statusFilter) {
      // Return format with extracted_records, total_count, validation_status
      return {
        extracted_records: filtered,
        total_count: filtered.length,
        validation_status: "success",
        export_format: "csv",
        export_filename: exportFilename,
      };
    } else {
      // Return format with records, totalCount, isDownloadEnabled
      return {
        records: filtered,
        totalCount: filtered.length,
        isDownloadEnabled: filtered.length > 0,
        errorMessage: null,
        extracted_count: filtered.length,
        validation_status: "success",
        export_format: "csv",
        export_filename: exportFilename,
      };
    }
  }
  return { extractBillingTargetData };
})();
export const extractBillingTargetData: (...args: any[]) => any = (...args: any[]) => (__aivicBundle_21_extractBillingTargetData.extractBillingTargetData as (...args: any[]) => any)(...args);
/* AIVIC_FUNCTION_BUNDLE_END owner=extractBillingTargetData */

/* AIVIC_FUNCTION_BUNDLE_START owner=validateQuotationData exports=validateQuotationData */
const __aivicBundle_22_validateQuotationData = (() => {
  function validateQuotationData(input: {
    deal_id: string;
    customer_name: string;
    product_name: string;
    agreement_date: string;
    agreement_amount: number;
    sales_owner: string;
  }): {
    is_valid: boolean;
    status: string;
    message: string;
    deal_id: string;
    validation_result: {
      has_all_required_fields: boolean;
      amount_in_valid_range: boolean;
      amount_min: number;
      amount_max: number;
      validated_amount: number;
    };
  } {
    const AMOUNT_MIN = 100000;
    const AMOUNT_MAX = 50000000;
    const ISO_DATE_PATTERN = /^\d{4}-\d{2}-\d{2}$/;
  
    // 必須項目の完全性チェック
    const requiredFields = [
      'deal_id',
      'customer_name',
      'product_name',
      'agreement_date',
      'sales_owner',
    ];
  
    const missingFields = requiredFields.filter((field) => {
      const value = input[field as keyof typeof input];
      return value === '' || value === null || value === undefined;
    });
  
    if (missingFields.length > 0) {
      throw new Error(`必須項目が不足しています: ${missingFields.join(', ')}`);
    }
  
    // 日付形式チェック（ISO 8601 YYYY-MM-DD）
    if (!ISO_DATE_PATTERN.test(input.agreement_date)) {
      throw new Error(`日付形式が不正です。ISO 8601形式（YYYY-MM-DD）で指定してください: ${input.agreement_date}`);
    }
  
    // 金額範囲チェック
    if (
      input.agreement_amount < AMOUNT_MIN ||
      input.agreement_amount > AMOUNT_MAX
    ) {
      throw new Error(
        `金額が有効範囲外です。${AMOUNT_MIN}円～${AMOUNT_MAX}円の範囲で指定してください。指定金額: ${input.agreement_amount}円`
      );
    }
  
    // 全チェック合格時の結果
    return {
      is_valid: true,
      status: '承認',
      message: '承認',
      deal_id: input.deal_id,
      validation_result: {
        has_all_required_fields: true,
        amount_in_valid_range: true,
        amount_min: AMOUNT_MIN,
        amount_max: AMOUNT_MAX,
        validated_amount: input.agreement_amount,
      },
    };
  }
  return { validateQuotationData };
})();
export const validateQuotationData = __aivicBundle_22_validateQuotationData.validateQuotationData;
/* AIVIC_FUNCTION_BUNDLE_END owner=validateQuotationData */

/* AIVIC_FUNCTION_BUNDLE_START owner=validateBillingTargetData exports=validateBillingTargetData */
const __aivicBundle_23_validateBillingTargetData = (() => {
  function validateBillingTargetData(
    input:
      | {
          deal_id: string;
          deal_name: string;
          customer_name: string;
          customer_id: string;
          amount: number;
          invoice_date: string;
          line_items: Array<{
            item_id: string;
            item_name: string;
            quantity: number;
            unit_price: number;
            subtotal: number;
          }>;
        }
      | Array<{
          billingId: string;
          customerId: string;
          billingAmount: number;
          billingDate: string;
          itemCount: number;
          status: string;
        }>
  ): ValidationCheckResult {
    // 単一オブジェクト（deal）の場合
    if (!Array.isArray(input)) {
      const deal = input as {
        deal_id: string;
        deal_name: string;
        customer_name: string;
        customer_id: string;
        amount: number;
        invoice_date: string;
        line_items: Array<{
          item_id: string;
          item_name: string;
          quantity: number;
          unit_price: number;
          subtotal: number;
        }>;
      };
  
      // 必須項目の検証
      if (!deal.customer_name || deal.customer_name.trim() === "") {
        throw new Error("顧客名が必須です");
      }
  
      if (!deal.amount || deal.amount <= 0) {
        throw new Error("金額が必須です");
      }
  
      if (!deal.line_items || deal.line_items.length === 0) {
        throw new Error("明細が必須です");
      }
  
      return {
        is_valid: true,
        status: "承認",
        message: "承認",
      };
    }
  
    // 配列（複数の請求データ）の場合
    const billingRecords = input as Array<{
      billingId: string;
      customerId: string;
      billingAmount: number;
      billingDate: string;
      itemCount: number;
      status: string;
    }>;
  
    // 重複検出用のキーマップ
    const duplicateKeyMap = new Map<
      string,
      Array<{ billingId: string; index: number }>
    >();
    const duplicateGroups: Array<{
      key: string;
      records: Array<{ billingId: string; index: number }>;
    }> = [];
  
    // 重複キーの生成と検出
    billingRecords.forEach((record, index) => {
      const duplicateKey = `${record.customerId}_${record.billingAmount}_${record.billingDate}`;
  
      if (!duplicateKeyMap.has(duplicateKey)) {
        duplicateKeyMap.set(duplicateKey, []);
      }
      duplicateKeyMap.get(duplicateKey)!.push({
        billingId: record.billingId,
        index,
      });
    });
  
    // 重複グループの抽出（2件以上のグループのみ）
    duplicateKeyMap.forEach((records, key) => {
      if (records.length > 1) {
        duplicateGroups.push({ key, records });
      }
    });
  
    const hasDuplicates = duplicateGroups.length > 0;
    const totalDuplicateRecords = duplicateGroups.reduce(
      (sum, group) => sum + group.records.length,
      0
    );
  
    // データ検証詳細の構築
    const dataValidationDetails: Array<{
      billingId: string;
      isValid: boolean;
      approvalStatus: string;
      reason: string | null;
    }> = [];
  
    const duplicateRecordIndices = new Set<number>();
    duplicateGroups.forEach((group) => {
      group.records.forEach((record) => {
        duplicateRecordIndices.add(record.index);
      });
    });
  
    billingRecords.forEach((record, index) => {
      if (duplicateRecordIndices.has(index)) {
        dataValidationDetails.push({
          billingId: record.billingId,
          isValid: false,
          approvalStatus: "rejected",
          reason: "duplicate_entry",
        });
      } else {
        dataValidationDetails.push({
          billingId: record.billingId,
          isValid: true,
          approvalStatus: "approved",
          reason: null,
        });
      }
    });
  
    // 検証概要の計算
    const validRecords = dataValidationDetails.filter((d) => d.isValid).length;
    const invalidRecords = dataValidationDetails.filter((d) => !d.isValid).length;
    const approvedCount = dataValidationDetails.filter(
      (d) => d.approvalStatus === "approved"
    ).length;
    const rejectedCount = dataValidationDetails.filter(
      (d) => d.approvalStatus === "rejected"
    ).length;
    const validationPassRate =
      billingRecords.length > 0
        ? Math.round((validRecords / billingRecords.length) * 1000) / 1000
        : 0;
  
    // 重複詳細情報の構築
    const duplicateDetails: Array<{
      duplicateKey: string;
      affectedBillingIds: string[];
      duplicateFieldsCount: number;
      duplicateFields: string[];
    }> = duplicateGroups.map((group) => ({
      duplicateKey: group.key,
      affectedBillingIds: group.records.map((r) => r.billingId),
      duplicateFieldsCount: 3,
      duplicateFields: ["customerId", "billingAmount", "billingDate"],
    }));
  
    return {
      is_valid: !hasDuplicates,
      status: hasDuplicates ? "不承認" : "承認",
      message: hasDuplicates ? "重複データが検出されました" : "承認",
      isDuplicate: hasDuplicates,
      duplicateCount: totalDuplicateRecords,
      duplicateDetails,
      approvalStatus: hasDuplicates ? "rejected" : "approved",
      rejectionReason: hasDuplicates ? "duplicate_detected" : null,
      dataValidationDetails,
      validationSummary: {
        totalRecords: billingRecords.length,
        validRecords,
        invalidRecords,
        approvedCount,
        rejectedCount,
        validationPassRate,
      },
    };
  }
  return { validateBillingTargetData };
})();
export const validateBillingTargetData: (...args: any[]) => any = (...args: any[]) => (__aivicBundle_23_validateBillingTargetData.validateBillingTargetData as (...args: any[]) => any)(...args);
/* AIVIC_FUNCTION_BUNDLE_END owner=validateBillingTargetData */

/* AIVIC_FUNCTION_BUNDLE_START owner=validateBillingDataReasonableness exports=validateBillingDataReasonableness */
const __aivicBundle_24_validateBillingDataReasonableness = (() => {
  function validateBillingDataReasonableness(input: {
    deal_id: string;
    customer_id: string;
    customer_name: string;
    amount: number;
    line_count: number;
    invoice_date: string;
  }): { is_valid: boolean; error_message: string | null } {
    if (input["deal_id"] === undefined || input["deal_id"] === null) { throw new Error("deal_id is required"); }
    if (input["customer_id"] === undefined || input["customer_id"] === null) { throw new Error("customer_id is required"); }
    if (input["customer_name"] === undefined || input["customer_name"] === null) { throw new Error("customer_name is required"); }
    if (input["line_count"] === undefined || input["line_count"] === null) { throw new Error("line_count is required"); }
    if (input["invoice_date"] === undefined || input["invoice_date"] === null) { throw new Error("invoice_date is required"); }
    const MIN_AMOUNT = 1;
    const MAX_AMOUNT = 1000000000;
  
    if (input.amount < MIN_AMOUNT) {
      if (input.amount < 0) {
        return {
          is_valid: false,
          error_message: '金額がマイナスです',
        };
      }
      return {
        is_valid: false,
        error_message: '金額は1円以上である必要があります',
      };
    }
  
    if (input.amount > MAX_AMOUNT) {
      return {
        is_valid: false,
        error_message: '金額が上限を超えています',
      };
    }
  
    return {
      is_valid: true,
      error_message: null,
    };
  }
  return { validateBillingDataReasonableness };
})();
export const validateBillingDataReasonableness = __aivicBundle_24_validateBillingDataReasonableness.validateBillingDataReasonableness;
/* AIVIC_FUNCTION_BUNDLE_END owner=validateBillingDataReasonableness */

/* AIVIC_FUNCTION_BUNDLE_START owner=calculateTotalCost exports=calculateTotalCost */
const __aivicBundle_25_calculateTotalCost = (() => {
  function calculateTotalCost(input: CostComparisonInput): number {
    const annualSalesforcelicenseCost = input.salesforceMonthlyFee * input.userCount;
    const totalCost = annualSalesforcelicenseCost + input.initialConstructionCost + input.annualMaintenanceCost;
    return totalCost;
  }
  return { calculateTotalCost };
})();
export const calculateTotalCost = __aivicBundle_25_calculateTotalCost.calculateTotalCost;
/* AIVIC_FUNCTION_BUNDLE_END owner=calculateTotalCost */

/* AIVIC_FUNCTION_BUNDLE_START owner=generateLicenseCostComparisonTable exports=generateLicenseCostComparisonTable */
const __aivicBundle_26_generateLicenseCostComparisonTable = (() => {
  function generateLicenseCostComparisonTable(input: {
    fiscalYears: FiscalYearCost[];
  }): LicenseCostComparisonResult {
    const { fiscalYears } = input;
  
    if (!fiscalYears || fiscalYears.length === 0) {
      return {
        comparisonTable: [],
        grandTotalLicenseCost: 0,
        grandTotalOperationCost: 0,
        grandTotalCost: 0,
        averageAnnualCost: 0,
      };
    }
  
    let cumulativeLicenseCost = 0;
    let cumulativeOperationCost = 0;
    let grandTotalLicenseCost = 0;
    let grandTotalOperationCost = 0;
  
    const comparisonTable: ComparisonTableRow[] = fiscalYears.map((fiscal) => {
      cumulativeLicenseCost += fiscal.annualLicenseCost;
      cumulativeOperationCost += fiscal.annualOperationCost;
  
      const yearlyTotalCost =
        fiscal.annualLicenseCost + fiscal.annualOperationCost;
      const cumulativeTotalCost =
        cumulativeLicenseCost + cumulativeOperationCost;
  
      grandTotalLicenseCost = cumulativeLicenseCost;
      grandTotalOperationCost = cumulativeOperationCost;
  
      return {
        year: fiscal.year,
        annualLicenseCost: fiscal.annualLicenseCost,
        annualOperationCost: fiscal.annualOperationCost,
        yearlyTotalCost,
        cumulativeLicenseCost,
        cumulativeOperationCost,
        cumulativeTotalCost,
      };
    });
  
    const grandTotalCost = grandTotalLicenseCost + grandTotalOperationCost;
    const averageAnnualCost =
      fiscalYears.length > 0 ? grandTotalCost / fiscalYears.length : 0;
  
    return {
      comparisonTable,
      grandTotalLicenseCost,
      grandTotalOperationCost,
      grandTotalCost,
      averageAnnualCost,
    };
  }
  return { generateLicenseCostComparisonTable };
})();
export const generateLicenseCostComparisonTable = __aivicBundle_26_generateLicenseCostComparisonTable.generateLicenseCostComparisonTable;
/* AIVIC_FUNCTION_BUNDLE_END owner=generateLicenseCostComparisonTable */

/* AIVIC_FUNCTION_BUNDLE_START owner=calculateInitialConstructionCost exports=calculateInitialConstructionCost */
const __aivicBundle_27_calculateInitialConstructionCost = (() => {
  function calculateInitialConstructionCost(input: InitialConstructionCostInput): void {
    if (input["developmentScale"] === undefined || input["developmentScale"] === null) { throw new Error("developmentScale is required"); }
    if (input["developmentDays"] === undefined || input["developmentDays"] === null) { throw new Error("developmentDays is required"); }
    if (input["teamSize"] === undefined || input["teamSize"] === null) { throw new Error("teamSize is required"); }
    if (input.developmentScale === undefined || input.developmentScale === null || String(input.developmentScale).trim() === "") {
      throw new Error("developmentScale is required");
    }
    if (input.developmentDays === undefined || input.developmentDays === null) {
      throw new Error("developmentDays is required");
    }
    if (input.teamSize === undefined || input.teamSize === null) {
      throw new Error("teamSize is required");
    }
    if (input.initialConstructionCost < 0) {
      throw new Error("初期構築コストが負の値です");
    }
    const costPerDay = input.initialConstructionCost / Math.max(input.developmentDays, 1);
    const costPerTeamMember = input.initialConstructionCost / Math.max(input.teamSize, 1);
    const scaleMultiplier = input.developmentScale === "small" ? 0.8 : input.developmentScale === "medium" ? 1.0 : 1.2;
    const adjustedCost = input.initialConstructionCost * scaleMultiplier;
    void costPerDay;
    void costPerTeamMember;
    void adjustedCost;
  }
  return { calculateInitialConstructionCost };
})();
export const calculateInitialConstructionCost = __aivicBundle_27_calculateInitialConstructionCost.calculateInitialConstructionCost;
/* AIVIC_FUNCTION_BUNDLE_END owner=calculateInitialConstructionCost */

/* AIVIC_FUNCTION_BUNDLE_START owner=calculateLicenseCostComparison exports=calculateLicenseCostComparison */
const __aivicBundle_28_calculateLicenseCostComparison = (() => {
  function calculateLicenseCostComparison(
    input: LicenseCostComparisonInput
  ): LicenseCostComparisonOutput {
    // annualMaintenanceCost が null または undefined の場合、比較計算をスキップ
    if (input.annualMaintenanceCost === null || input.annualMaintenanceCost === undefined) {
      return {
        comparisonSkipped: true,
        warningMessage: '年間保守運用コストが入力されていません',
        comparisonResult: null,
        hasError: false,
      };
    }
  
    // 3年間の総コスト計算
    const THREE_YEARS = 3;
    
    // Salesforce ライセンス費用の3年間総コスト
    const totalSalesforceThreeYearCost = input.salesforceLicenseCost * THREE_YEARS;
    
    // 自社開発システムコストの3年間総コスト
    // = 初期構築コスト + (年間保守運用コスト × 3年)
    const totalDevelopmentThreeYearCost =
      input.initialConstructionCost +
      input.annualMaintenanceCost * THREE_YEARS;
    
    // コスト削減額
    const costSavings = totalSalesforceThreeYearCost - totalDevelopmentThreeYearCost;
  
    return {
      comparisonSkipped: false,
      warningMessage: null,
      comparisonResult: {
        totalSalesforceThreeYearCost,
        totalDevelopmentThreeYearCost,
        costSavings,
      },
      hasError: false,
    };
  }
  return { calculateLicenseCostComparison };
})();
export const calculateLicenseCostComparison = __aivicBundle_28_calculateLicenseCostComparison.calculateLicenseCostComparison;
/* AIVIC_FUNCTION_BUNDLE_END owner=calculateLicenseCostComparison */
